export const OPS_OBSERVABILITY_SCRIPT_A = `    (() => {
      const $ = id => document.getElementById(id);
      const base = location.pathname.replace(/\\/ops-observability\\/?$/, '');
      // Canonical views are listed first; legacy names remain parseable so old
      // bookmarks (#rules/#database/#session-traces) open the corresponding
      // accordion in the unified workbench instead of falling back to a blank tab.
      const viewNames = ['overview','service-levels','operator-metrics','data-health','database','skill-loop','evolution','investigate','alerts','traces','platform','metrics','rules','channels','agent-traces','session-traces','model-pool','settings'];
      const overviewScopedViews = ['overview','traces'];
      // Keep old deep links usable while the workbench exposes one canonical
      // set of top-level views.  Object/table/learning names were used by the
      // earlier observability console and should open the matching accordion
      // instead of silently falling back to the overview.
      const viewAliases = {metrics:'alerts',rules:'alerts',channels:'alerts',objects:'alerts',object:'alerts','alert-objects':'alerts','agent-traces':'traces','session-traces':'traces','model-pool':'platform',settings:'platform','platform-settings':'platform','skill-flywheel':'skill-loop','skill-governance':'skill-loop',learning:'skill-loop',skills:'skill-loop',postgres:'database','postgresql':'database'};
      const state = { overview:null, overviewHours:24, config:null, remediation:null, actions:null, learning:null, operatorMetrics:null, modelPool:null, objects:null, objectSelection:null, objectDetail:null, objectDetailLoading:false, objectSearch:'', objectTeam:'all', objectOwnerTeam:'all', objectLabel:'all', objectType:'all', objectArchived:'all', database:null, databaseHours:24, databaseLoading:false, databaseLoadedAt:0, databaseAiLoading:false, databaseAiResult:null, databaseTableSelection:null, databaseTableDetail:null, databaseTablePage:1, databaseTableLoading:false, databaseTableSortColumn:'', databaseTableSortDirection:'asc', traceEnvironment:null, traceOutcome:null, investigationOverview:null, investigationOutcome:null, investigationQuery:'', pendingRemediate:null, view:'overview', viewSource:'overview', category:'all', statusFilter:'all', search:'', editingKey:null, editorDirty:false, editorReturnFocus:null, templateEditing:false, accessRendered:false };
      const viewMeta = {overview:['运营 / 可观测中心','生产可观测与告警','先判断生产影响，再处理事故、维护告警，最后下钻到链路证据。'],investigate:['可观测中心 / 事故调查','事故调查','关联异常趋势、代表证据与影响范围，形成可复核的根因假设。'],alerts:['可观测中心 / 告警','告警策略','管理指标、日志与拨测规则，验证阈值并安全配置通知。'],traces:['可观测中心 / 证据','链路追踪','从原生 Trace 与会话链路定位慢请求、失败步骤和模型路由。'],'operator-metrics':['可观测中心 / 数据','运营指标','按天查看 token、新增用户、DAU、对话次数和 Agent Run。'],'data-health':['可观测中心 / 数据','数据健康','检查关键业务数据是否持续入库，并核对数量、趋势与最近写入。'],database:['可观测中心 / 数据','数据库','从表目录和关系图下钻，并通过脱敏只读查询获取证据。'],'skill-loop':['可观测中心 / 学习与进化','Skill 数据闭环','把埋点采集、运行反馈、候选审核和发布回流放在同一条可追溯链路。'],evolution:['可观测中心 / 学习与进化','每日自我进化','查看证据聚合、质量闸门和可审核候选；候选不会自动上线。'],platform:['可观测中心 / 设置','系统设置','管理评估器、Canary 真实业务拨测与安全进化边界。'],metrics:['可观测中心 / 告警','指标与数据源','核对系统指标的数据源、状态和阈值。'],rules:['可观测中心 / 告警','告警策略','按指标、日志和拨测筛选，完成数据源到通知的策略闭环。'],channels:['可观测中心 / 告警','通知模板','先确认投递状态，再按需编辑降噪策略与渠道凭据。'],'agent-traces':['可观测中心 / 证据','Agent 原生 Trace','从真实 Agent 执行记录定位模型、工具和持久化问题。'],'session-traces':['可观测中心 / 证据','会话 Trace','按会话重放用户到 Agent 的完整链路。'],'model-pool':['可观测中心 / 设置','模型路由池','查看模型健康与路由配置。'],settings:['可观测中心 / 设置','系统配置','配置评估器、Canary 真实业务拨测和日志签名。'],'service-levels':['可观测中心 / SLO','服务水平','用 SLO 和错误预算衡量用户可感知的可靠性。']};
      const categoryNames = {metric:'指标',log:'日志',probe:'拨测'};
      const statusNames = {healthy:'正常',observing:'Pending',warning:'告警',critical:'严重',stale:'数据过期',disabled:'已停用',open:'进行中',acknowledged:'已确认',silenced:'已静默',resolved:'已恢复',running:'运行中',no_candidate:'暂无候选',candidate_ready:'待审核',rejected:'已拒绝',blocked:'已阻塞',error:'失败',never:'未运行'};
      const severityNames = {critical:'严重',warning:'警告'};
      const fieldNames = {windowMinutes:'查询窗口（分钟）',minSamples:'最少样本数',threshold:'告警阈值',criticalThreshold:'严重阈值',ratePercent:'失败率阈值（%）',openAfter:'Pending 连续评估次数',resolveAfter:'连续恢复次数'};
      const make = (tag, cls, value) => { const node=document.createElement(tag); if(cls)node.className=cls; if(value!==undefined&&value!==null)node.textContent=String(value); return node; };
      const add = (parent, tag, cls, value) => { const node=make(tag,cls,value); parent.appendChild(node); return node; };
      const fmt = value => Number(value||0).toLocaleString();
      const pct = value => value==null?'—':(Number(value)*100).toFixed(1)+'%';
      const when = value => {if(!value)return '—';const date=new Date(value);return Number.isFinite(date.getTime())?date.toLocaleString('zh-CN',{hour12:false}):'—'};
      function studioSessionHeaders(){try{const session=localStorage.getItem('rdk_sso_session_mirror');return session?{'X-RDK-Sso-Session':session}:{}}catch{return {}}}
      const apiHeaders = mutation => Object.assign({'content-type':'application/json'},studioSessionHeaders(),mutation?{'X-RDK-Ops-Action':'observability'}:{});
      function toast(message, ok=true){const node=$('toast');node.textContent=message;node.className='toast show '+(ok?'ok':'bad');clearTimeout(toast.timer);toast.timer=setTimeout(()=>{node.className='toast'},3600)}
      function setFeedback(id,message,ok=true){const node=$(id);if(!node)return;node.textContent=message;node.className='feedback '+(ok?'ok':'bad')}
      function projectTelemetryState(kind,label){const next=['live','stale','error','unauthorized'].includes(kind)?kind:'unknown';const header=$('headerTelemetryStatus');if(header){header.className='header-live '+next;header.textContent=label||({live:'Telemetry 已接入',stale:'Telemetry 可能过期',error:'Telemetry 加载失败',unauthorized:'Telemetry 未授权',unknown:'Telemetry 未确认'})[next]}const scope=$('scopeStatus');if(scope){scope.className='scope-status '+next;scope.textContent=next==='live'?'数据持续接入':next==='stale'?'数据可能过期':next==='unauthorized'?'当前账号无权限':next==='error'?'数据加载失败':'等待真实数据'}}
      function applyOverviewSnapshot(overview){state.overview=overview||null;const alerting=state.overview&&state.overview.alerting;if(!alerting||!alerting.lastCheckedAt)projectTelemetryState('unknown');else if(alerting.status==='stale')projectTelemetryState('stale');else projectTelemetryState('live');if(state.overview&&typeof renderOverview==='function')renderOverview();if(typeof updateGlobalContext==='function')updateGlobalContext(state.overview)}
      function syncScopeVisibility(name){const scope=$('overviewScopeBar');if(scope)scope.classList.toggle('hidden',!overviewScopedViews.includes(name))}
      function friendlyError(message){const labels={feishu_contact_point_not_configured:'请先填写飞书 Webhook URL',webhook_contact_point_not_configured:'请先填写通用 Webhook URL',notification_delivery_disabled:'请先启用真实通知并关闭影子模式',not_authorized:'当前账号没有运营配置权限',remediation_cooldown:'该剧本近期已执行，处于冷却期，请稍后重试',remediation_already_running:'已有自愈正在执行，请等待其完成',remediation_store_unavailable:'审计数据库不可用，暂无法执行自愈',remediation_start_failed:'自愈执行单元启动失败',unknown_remediation_playbook:'未知的自愈剧本',action_store_unavailable:'行动审计数据库暂不可用，请稍后重试',action_evidence_proof_invalid:'证据包已过期或已变化，请重新研判',action_evidence_proof_required:'请从 AI 事故副驾生成带证据的行动',action_approval_expired:'审批已过期，请重新审批',action_state_conflict:'行动状态已被其他人更新，请刷新后继续',action_execution_failed:'白名单剧本执行失败，请查看后置验证',action_verification_failed:'后置验证未通过，请查看失败证据并加入回归集',action_completion_requires_approval:'该行动尚未完成审批',ai_sql_provider_unavailable:'当前账号没有可用的 AI 模型配置',ai_sql_schema_unavailable:'AI 脱敏查询层尚未就绪，请稍后重试',ai_sql_generation_failed:'AI 生成 SQL 失败，请重试',ai_sql_invalid_response:'AI 返回的 SQL 格式无效，请换一种问法',ai_sql_execution_failed:'生成的 SQL 执行失败，请换一种问法',ai_sql_query_in_progress:'已有数据库查询正在执行',ai_sql_rate_limited:'操作太频繁，请稍后再试',ai_sql_question_invalid:'请描述要查询的问题',ai_sql_export_format_invalid:'导出格式只支持 JSON 或 CSV',ai_sql_not_read_only:'只允许执行只读 SQL',ai_sql_unsafe_syntax:'生成的 SQL 未通过安全检查',ai_sql_schema_blocked:'只能查询脱敏视图',ai_sql_schema_required:'查询必须使用 ops_ai 脱敏视图',ai_sql_relation_blocked:'查询访问了未授权数据表',ai_sql_function_blocked:'查询使用了不安全函数'};return labels[message]||message}
      function section(title,hint){const node=make('section','panel section');const head=make('div','section-head');const box=make('div');add(box,'h2','',title);if(hint)add(box,'div','hint',hint);head.appendChild(box);node.appendChild(head);return node}
      function field(parent,id,labelText,value,type='text',full=false){const box=make('div','field'+(full?' full':''));const label=add(box,'label','',labelText);label.htmlFor=id;const input=make(type==='textarea'?'textarea':'input');input.id=id;if(type!=='textarea')input.type=type;if(type==='password'){input.autocomplete='new-password';input.name='ops-secret-'+id;input.dataset.lpignore='true';input.dataset['1pIgnore']='true'}input.value=value==null?'':String(value);box.appendChild(input);parent.appendChild(box);return input}
      function selectField(parent,id,labelText,value,options,full=false){const box=make('div','field'+(full?' full':''));const label=add(box,'label','',labelText);label.htmlFor=id;const select=make('select');select.id=id;options.forEach(optionData=>{const option=make('option','',optionData[1]);option.value=optionData[0];option.selected=optionData[0]===value;select.appendChild(option)});box.appendChild(select);parent.appendChild(box);return select}
      function switchField(parent,id,labelText,checked){const label=make('label','switch');const input=make('input');input.type='checkbox';input.id=id;input.checked=Boolean(checked);label.appendChild(input);label.appendChild(document.createTextNode(labelText));parent.appendChild(label);return input}
      async function request(path, options){const response=await fetch(base+path,Object.assign({credentials:'same-origin',headers:apiHeaders(Boolean(options&&options.method&&options.method!=='GET'))},options||{}));if(response.status===401||response.status===403){renderAccess();throw new Error('not_authorized')}const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.message||data.error||(data.result&&data.result.error)||('HTTP '+response.status));return data}
      function renderAccess(){projectTelemetryState('unauthorized');if(state.accessRendered)return;state.accessRendered=true;const box=make('section','panel access');box.dataset.accessScreen='true';add(box,'h2','','需要运营账号登录');add(box,'p','','当前浏览器没有可用的 RDK Studio 运营会话。请先在同一浏览器登录工作台，再回到本页。');const link=add(box,'a','btn primary','打开 RDK Studio 登录');link.href=base+'/';link.target='_blank';link.rel='noopener';document.querySelectorAll('.view').forEach(node=>node.classList.add('hidden'));const main=document.querySelector('main');main.appendChild(box);const fresh=$('fresh');if(fresh)fresh.textContent='真实数据和配置受运营账号权限保护'}
      function updateViewHeader(source,name){const meta=viewMeta[source]||viewMeta[name]||viewMeta.overview;[['pageKicker',meta[0]],['pageTitle',meta[1]],['pageIntro',meta[2]]].forEach(item=>{const node=$(item[0]);if(node)node.textContent=item[1]});document.title='RDK Studio · '+meta[1]}
      const navGroupByView={investigate:'core',alerts:'core',traces:'core','operator-metrics':'data','data-health':'data',database:'data','skill-loop':'learning',evolution:'learning',platform:'advanced','service-levels':'core'};
      function openNavGroupForView(name){const groupName=navGroupByView[name]||'';document.querySelectorAll('.nav-group').forEach(group=>{group.open=Boolean(groupName&&group.dataset.navGroup===groupName)})}
      function initNavGroups(){document.querySelectorAll('.nav-group').forEach(group=>group.addEventListener('toggle',()=>{if(group.open)document.querySelectorAll('.nav-group').forEach(other=>{if(other!==group)other.open=false})}))}
      function setView(requested, updateHash=true){const source=requested;const name=viewAliases[requested]||requested;if(!viewNames.includes(name))return setView('overview',updateHash);state.view=name;state.viewSource=source;updateViewHeader(source,name);syncScopeVisibility(name);openNavGroupForView(name);const activeView=document.querySelector('[data-view="'+source+'"]')?source:name;document.querySelectorAll('[data-view]').forEach(button=>{const active=button.dataset.view===activeView;button.classList.toggle('active',active);if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current')});viewNames.forEach(view=>{const node=$('view-'+view);if(node)node.classList.toggle('hidden',view!==name)});if(updateHash)history.replaceState(null,'','#'+source);if(name==='investigate'&&typeof renderInvestigation==='function')renderInvestigation(state.investigationOverview||state.overview);if(name==='service-levels')renderServiceLevels();if(name==='operator-metrics'&&typeof loadOperatorMetrics==='function')loadOperatorMetrics(false);if((name==='data-health'||name==='database')&&typeof loadPostgresDashboard==='function')loadPostgresDashboard();if((name==='skill-loop'||name==='evolution')&&typeof renderLearningModules==='function')renderLearningModules();if(name==='alerts'){if(typeof renderMetrics==='function')renderMetrics();if(typeof renderObjects==='function')renderObjects();renderRules();renderChannels();const section=source==='metrics'?$('alerts-metrics'):['objects','object','alert-objects'].includes(source)?$('alerts-objects'):source==='channels'?$('alerts-channels'):$('alerts-rules');if(section)section.open=true}if(name==='traces'){if(typeof renderNativeTraces==='function')renderNativeTraces();renderSessionTraces();if(source==='session-traces'&&$('traces-session'))$('traces-session').open=true}if(name==='platform'){renderSettings();renderEvolution();if(source==='model-pool'&&typeof renderModelPool==='function')renderModelPool();const section=source==='model-pool'?$('platform-model'):$('platform-settings');if(section)section.open=true}}
      function renderLoadPanel(root,label,error){if(!root)return;root.replaceChildren();const panel=make('section','panel load-state '+(error?'error':'loading'));panel.setAttribute('role',error?'alert':'status');panel.setAttribute('aria-live','polite');add(panel,'div','load-state-icon',error?'!':'');const copy=make('div');add(copy,'strong','',error?label:'正在加载'+label+'…');add(copy,'span','',error?'请检查网络或运营权限后重试。':'已发起真实数据请求，请稍候。');panel.appendChild(copy);if(error){const retry=add(panel,'button','btn','重试');retry.type='button';retry.addEventListener('click',()=>loadAll(true))}root.appendChild(panel)}
      function renderInitialLoading(){if(state.config)return;renderLoadPanel($('metricsContent'),'指标与数据源',false);renderLoadPanel($('rulesList'),'告警策略',false);renderLoadPanel($('templateSummary'),'通知模板',false);renderLoadPanel($('settingsContent'),'系统设置',false)}
      function renderInitialError(message){if(state.config)return;const label='加载失败：'+friendlyError(message);renderLoadPanel($('metricsContent'),label,true);renderLoadPanel($('rulesList'),label,true);renderLoadPanel($('templateSummary'),label,true);renderLoadPanel($('settingsContent'),label,true)}
      // 会话 Trace：懒加载嵌入 /session-trace 产品页（首次切到该 tab 才建 iframe），base 前缀与本页 fetch 同源。
      function renderSessionTraces(){const box=$('sessionTraceEmbed');if(!box||box.dataset.loaded)return;box.dataset.loaded='1';const frame=document.createElement('iframe');frame.src=base+'/session-trace';frame.title='会话 Trace 查看';frame.loading='lazy';frame.style.cssText='width:100%;height:76vh;border:1px solid rgba(148,163,184,.25);border-radius:12px;background:#fff';box.appendChild(frame)}
      function overviewNumber(value){const parsed=Number(value);return Number.isFinite(parsed)?parsed:0}
      function overviewChecks(o){return Array.isArray(o&&o.checks)?o.checks:[]}
      function overviewIncidents(o){return Array.isArray(o&&o.incidents)?o.incidents:[]}
      function checkStatus(key){return overviewChecks(state.overview).find(check=>check.key===key)}
      function conditionText(def,rule){if(def.key==='ai-run-degraded-rate')return '样本 ≥ '+rule.minSamples+'，失败/部分完成率 ≥ '+rule.ratePercent+'%，且异常数 ≥ '+rule.threshold;if(def.key==='llm-token-budget')return rule.windowMinutes+' 分钟内 token 总量 ≥ '+Number(rule.threshold).toLocaleString();if(def.key==='api-5xx-spike')return rule.windowMinutes+' 分钟内计数 ≥ '+rule.threshold+'，客户端错误需独立样本 ≥ '+rule.minSamples;if(def.key==='disk-space')return '磁盘使用率 ≥ '+rule.threshold+'%';if(def.key==='slo-error-budget-burn')return '1h / 6h 错误预算燃烧率 ≥ '+rule.threshold+'x';if(def.key==='external-tls')return '证书剩余天数 < '+rule.threshold+' 天';if(def.category==='probe')return '不可用，或耗时 ≥ '+rule.threshold+' ms';return rule.windowMinutes+' 分钟窗口内计数 ≥ '+rule.threshold}
      function criticalText(def,rule){if(def.key==='external-tls')return '证书校验失败立即视为严重';if(def.key==='disk-space')return '严重：≥ '+rule.criticalThreshold+'%';if(def.key==='slo-error-budget-burn')return '严重燃烧：≥ '+rule.criticalThreshold+'x';if(def.category==='probe')return '严重延迟：≥ '+rule.criticalThreshold+' ms';return '严重阈值：'+rule.criticalThreshold}
      function resolvedChannel(rule){return rule.notificationChannel==='default'?state.config.notification.channel:rule.notificationChannel}
      function channelConfigured(rule){const channel=resolvedChannel(rule);if(channel==='none')return false;if(channel==='feishu')return state.config.notification.feishuWebhookConfigured;return state.config.notification.genericWebhookConfigured}
      function channelText(rule){if(rule.notificationChannel==='none')return '不发送';const channel=resolvedChannel(rule);const label=channel==='feishu'?'飞书机器人':'通用 Webhook';return (rule.notificationChannel==='default'?'默认 · ':'')+label+(channelConfigured(rule)?'':'（未配置）')}
      function dataSourceName(def){if(def.key.startsWith('external-'))return '106.53 异地探针';if(def.key.startsWith('synthetic-'))return 'RDK Studio 真实业务链路';if(def.key==='slo-error-budget-burn')return 'SLO 错误预算引擎';if(def.key==='agent-model-target-degraded')return '3100/3101 gateway target-health';if(def.key==='nginx-5xx-log')return 'Nginx access.log';if(def.key==='postgres-error-log'||def.key==='central-database')return 'PostgreSQL';if(def.key==='service-crash-signature'||def.key==='process-unhandled-error'||def.key==='internal-health')return 'systemd / 本机';if(def.category==='metric')return 'RDK 运营遥测';return '独立巡检 Worker'}
      function targetName(def){return def.key.startsWith('external-')?'rdkstudio.d-robotics.cc':'production / 47.110'}
      function renderRuleSummary(definitions){const root=$('ruleSummary');root.replaceChildren();const enabled=definitions.filter(def=>state.config.rules[def.key].enabled).length;const firing=definitions.filter(def=>['warning','critical'].includes(checkStatus(def.key)?.status)).length;const pending=definitions.filter(def=>checkStatus(def.key)?.status==='observing').length;const routed=definitions.filter(def=>state.config.rules[def.key].enabled&&channelConfigured(state.config.rules[def.key])).length;[['全部策略',definitions.length,'','指标 / 日志 / 拨测'],['生效策略',enabled,'good',(definitions.length-enabled)+' 条停用'],['触发中',firing+pending,(firing+pending)?'bad':'good',firing+' 告警 · '+pending+' Pending'],['可投递',routed,routed?'good':'warn','已绑定有效发送模板']].forEach(item=>{const card=make('div','panel summary-card');add(card,'div','summary-label',item[0]);add(card,'div','summary-value '+item[2],item[1]);add(card,'div','summary-note',item[3]);root.appendChild(card)})}
      function renderMetrics(){if(!state.config)return;const definitions=state.config.definitions.filter(def=>def.category==='metric');$('metricCount').textContent=String(definitions.length);const panel=make('section','panel metric-catalog');const head=make('div','metric-head');['指标名称','数据源','当前状态','告警阈值','严重阈值','查询窗口','操作'].forEach(value=>add(head,'div','',value));panel.appendChild(head);definitions.forEach(def=>{const rule=state.config.rules[def.key];const check=checkStatus(def.key);const status=rule.enabled?(check?.status||'healthy'):'disabled';const row=make('article','metric-row');const name=make('div');add(name,'div','rule-title',def.title);add(name,'div','metric-source',def.key);row.appendChild(name);const source=make('div');add(source,'div','',dataSourceName(def));add(source,'div','metric-source',def.description);row.appendChild(source);const stateCell=make('div','metric-status');stateCell.appendChild(make('span','state-dot '+status));add(stateCell,'span','',statusNames[status]||status);row.appendChild(stateCell);add(row,'div','',conditionText(def,rule));add(row,'div','',criticalText(def,rule));add(row,'div','',rule.windowMinutes?rule.windowMinutes+' 分钟':'每 60 秒');const edit=add(row,'button','icon-btn','✎');edit.type='button';edit.title='编辑指标阈值';edit.setAttribute('aria-label','编辑 '+def.title);edit.addEventListener('click',()=>openEditor(def.key));row.appendChild(edit);panel.appendChild(row)});const root=$('metricsContent');root.replaceChildren(panel)}
      function updateFilterSummary(){const count=(state.category==='all'?0:1)+(state.statusFilter==='all'?0:1);$('filterText').textContent=count?'筛选('+count+')':'筛选';$('filterTrigger').classList.toggle('active',count>0)}
      function renderRules(){if(!state.config)return;const definitions=state.config.definitions;$('ruleCount').textContent=String(definitions.length);renderRuleSummary(definitions);updateFilterSummary();const search=state.search.toLowerCase();const shown=definitions.filter(def=>{const rule=state.config.rules[def.key];const categoryMatch=state.category==='all'||def.category===state.category;const statusMatch=state.statusFilter==='all'||(state.statusFilter==='enabled'?rule.enabled:!rule.enabled);const searchMatch=!search||(def.title+' '+def.description+' '+def.key+' '+dataSourceName(def)).toLowerCase().includes(search);return categoryMatch&&statusMatch&&searchMatch});const root=$('rulesList');root.replaceChildren();if(!shown.length){root.appendChild(make('div','empty','没有匹配的告警策略'));return}shown.forEach(def=>{const rule=state.config.rules[def.key];const check=checkStatus(def.key);const status=rule.enabled?(check?.status||'healthy'):'disabled';const row=make('article','rule-row');const main=make('div','rule-main');main.appendChild(make('span','state-dot '+status));const titleBox=make('div');add(titleBox,'div','rule-title',def.title);add(titleBox,'div','rule-meta',dataSourceName(def)+' · '+def.key);main.appendChild(titleBox);row.appendChild(main);row.appendChild(make('span','category-chip type-'+def.category,categoryNames[def.category]));const condition=make('div','rule-condition',conditionText(def,rule));add(condition,'small','',criticalText(def,rule));row.appendChild(condition);const evaluation=make('div','rule-eval','每 60 秒');add(evaluation,'small','','持续 '+rule.openAfter+' 次 · 恢复 '+rule.resolveAfter+' 次');row.appendChild(evaluation);row.appendChild(make('div','channel-chip '+(!channelConfigured(rule)?'silent':''),channelText(rule)));const toggle=make('button','strategy-toggle '+(rule.enabled?'on':''),rule.enabled?'开启':'关闭');toggle.type='button';toggle.title=(rule.enabled?'停用':'启用')+'此告警策略';toggle.setAttribute('aria-label',(rule.enabled?'停用 ':'启用 ')+def.title);toggle.setAttribute('aria-pressed',String(rule.enabled));toggle.addEventListener('click',()=>toggleRule(def.key,!rule.enabled,toggle));row.appendChild(toggle);const action=make('div','row-action');const edit=add(action,'button','icon-btn','✎');edit.type='button';edit.title='编辑策略';edit.setAttribute('aria-label','编辑 '+def.title);edit.addEventListener('click',()=>openEditor(def.key));row.appendChild(action);root.appendChild(row)})}
`;
