export const OPS_OBSERVABILITY_SCRIPT_OBJECTS = `      function objectSelectionKey(item){return [item.team||'',item.objectType||'',item.objectId].join('\\u0000')}
      function objectTitle(item){return item.profile?.displayName||item.objectName||item.objectId}
      function objectSubtitle(item){const parts=[];if(item.team)parts.push('团队 '+item.team);if(item.objectType)parts.push('类型 '+item.objectType);if(item.profile?.ownerTeam)parts.push('负责人 '+item.profile.ownerTeam);return parts.length?parts.join(' · '):'未标注团队 / 类型'}
      function objectDetailTitle(detail){return detail.object.profile?.displayName||detail.object.objectName||detail.object.objectId}
      function objectDetailSubtitle(detail){const parts=[];if(detail.object.team)parts.push('团队 '+detail.object.team);if(detail.object.objectType)parts.push('类型 '+detail.object.objectType);if(detail.object.profile?.updatedBy)parts.push('更新人 '+detail.object.profile.updatedBy);return parts.length?parts.join(' · '):'对象详情'}
      function objectMatches(item,search){if(!search)return true;const haystack=[item.objectId,item.objectName,item.team,item.objectType,item.profile?.displayName,item.profile?.ownerTeam,item.profile?.description,...(item.profile?.labels||[])].map(value=>String(value||'').toLowerCase()).join(' ');return haystack.includes(search)}
      let icObjType=null;
      function renderObjects(){const root=$('objectsContent');if(!root)return;if(!state.config){root.replaceChildren(make('div','signals-empty','正在加载策略与巡检状态…'));return}function objType(name){if(name.indexOf('网关')>=0||name.indexOf('Nginx')>=0)return '网关';if(name.indexOf('PostgreSQL')>=0)return '数据库';if(name.indexOf('本机')>=0)return '服务器';if(name.indexOf('遥测')>=0)return '应用';if(name.indexOf('拨测')>=0)return '拨测';if(name.indexOf('SLO')>=0)return '可靠性';return '巡检'}const groups={};state.config.definitions.forEach(def=>{const name=dataSourceName(def);const key=objType(name)+'/'+name;if(!groups[key])groups[key]={type:objType(name),name:name,rules:0,firing:0,lastCheck:null};groups[key].rules++});overviewChecks(state.overview).forEach(check=>{const name=dataSourceName({key:check.key,category:check.category});const g=groups[objType(name)+'/'+name];if(!g)return;const st=checkStatus(check.key);if(st&&['warning','critical'].includes(st.status))g.firing++;if(check.checkedAt&&(!g.lastCheck||check.checkedAt>g.lastCheck))g.lastCheck=check.checkedAt});root.replaceChildren();const types={};Object.values(groups).forEach(g=>{types[g.type]=1});const bar=make('div','ic-tabs');bar.style.margin='2px 0 12px';[['全部',null]].concat(Object.keys(types).map(t=>[t,t])).forEach(pair=>{const b=add(bar,'button','ic-tab'+((icObjType||null)===pair[1]?' is-active':''),pair[0]);b.type='button';b.addEventListener('click',()=>{icObjType=pair[1];renderObjects()})});root.appendChild(bar);const grid=make('div','objects-grid');const list=make('section','panel object-list');const head=make('div','object-head');['监控对象','分类','覆盖规则','进行中事故','最近检查'].forEach(v=>add(head,'div','',v));list.appendChild(head);const entries=Object.values(groups).filter(g=>!icObjType||g.type===icObjType);entries.forEach(g=>{const row=make('div','object-row');add(row,'div','rule-title',g.name);add(row,'div','',g.type);add(row,'div','',g.rules+' 条规则');add(row,'div','',g.firing?g.firing+' 条触发中':'正常');add(row,'div','',g.lastCheck?when(g.lastCheck):'—');list.appendChild(row)});if(!entries.length)list.appendChild(make('div','empty','没有匹配的对象'));grid.appendChild(list);const detail=make('section','panel object-detail');add(detail,'div','object-detail-empty','共 '+entries.length+' 个监控对象 · 对象由告警规则的数据源自动聚合并按分类归档；应用接入 OTLP 后将扩展 run 与 trace 维度。');grid.appendChild(detail);root.appendChild(grid)}
      function objectFilterValues(){const catalog=state.objects&&Array.isArray(state.objects.objects)?state.objects.objects:[];return {ownerTeams:[...new Set(catalog.map(item=>item.profile?.ownerTeam).filter(Boolean))].sort(),labels:[...new Set(catalog.flatMap(item=>item.profile?.labels||[]).filter(Boolean))].sort()}}
      function appendObjectFilter(toolbar,id,current,allLabel,values,onChange){if($(id))return;const select=make('select');select.id=id;select.className='object-filter';[[ 'all',allLabel ],...values.map(value=>[value,value])].forEach(([value,label])=>{const option=make('option','',label);option.value=value;option.selected=value===current;select.appendChild(option)});select.addEventListener('change',event=>onChange(event.target.value));toolbar.appendChild(select)}
      renderObjects=function(){const original=state.objects;if(original&&Array.isArray(original.objects)){const scoped=original.objects.filter(item=>(state.objectOwnerTeam==='all'||item.profile?.ownerTeam===state.objectOwnerTeam)&&(state.objectLabel==='all'||(item.profile?.labels||[]).includes(state.objectLabel)));state.objects=Object.assign({},original,{objects:scoped})}renderObjectsBase();state.objects=original;const toolbar=document.querySelector('.object-toolbar');if(!toolbar)return;const values=objectFilterValues();appendObjectFilter(toolbar,'objectOwnerTeam',state.objectOwnerTeam,'全部负责人组',values.ownerTeams,value=>{state.objectOwnerTeam=value;renderObjects()});appendObjectFilter(toolbar,'objectLabel',state.objectLabel,'全部标签',values.labels,value=>{state.objectLabel=value;renderObjects()})};
      async function openObject(item){if(!item)return;state.objectSelection={team:item.team,objectType:item.objectType,objectId:item.objectId};state.objectDetailLoading=true;renderObjects();try{const query=new URLSearchParams({windowMinutes:'1440'});if(item.team)query.set('team',item.team);if(item.objectType)query.set('objectType',item.objectType);const data=await request('/api/ops/observability/objects/'+encodeURIComponent(item.objectId)+'?'+query.toString());state.objectDetail=data.detail}catch(error){state.objectDetail=null;toast('对象详情加载失败：'+friendlyError(error.message),false)}finally{state.objectDetailLoading=false;renderObjects()}}
`;
