/** Database relationship graph for the standalone operations page. */
export const OPS_OBSERVABILITY_SCRIPT_DATABASE_GRAPH = `
      function renderDatabaseRelationshipGraph(data){
        const graph=data.relationshipGraph||{};const panel=make('section','panel database-relationship-panel');
        const summary=graph.summary||{};panel.appendChild(databasePanelHead('数据库关系图','当前部署是一个中心 PostgreSQL；按 schema、业务表、外键与 ops_ai 脱敏投影展开，避免把“逻辑库”误认为独立物理库。',fmt(summary.foreignKeyCount||0)+' 条外键关系'));
        const body=make('div','database-relationship-body');const stats=make('div','database-relationship-stats');[['物理数据库',graph.databaseName||'当前数据库'],['业务表',fmt(summary.tableCount||0)],['脱敏视图',fmt(summary.maskedViewCount||0)],['外键',fmt(summary.foreignKeyCount||0)]].forEach(item=>{const card=make('article','database-relationship-stat');add(card,'span','',item[0]);add(card,'strong','',item[1]);stats.appendChild(card)});body.appendChild(stats);
        const canvas=make('div','database-relationship-canvas');const rootNode=(graph.nodes||[]).find(node=>node.kind==='database');const schemas=(graph.nodes||[]).filter(node=>node.kind==='schema');const tables=(graph.nodes||[]).filter(node=>node.kind==='table');
        const columnA=make('div','database-relationship-column');add(columnA,'div','database-relationship-column-label','物理层');if(rootNode){const node=make('article','database-relationship-node database-relationship-node-database');add(node,'strong','',rootNode.label||'中心 PostgreSQL');add(node,'span','',rootNode.description||'');columnA.appendChild(node)}canvas.appendChild(columnA);
        const columnB=make('div','database-relationship-column');add(columnB,'div','database-relationship-column-label','逻辑 schema');schemas.forEach(schema=>{const node=make('article','database-relationship-node database-relationship-node-schema');add(node,'strong','',schema.label||schema.schemaName||'schema');add(node,'span','',schema.description||'');columnB.appendChild(node)});canvas.appendChild(columnB);
        const columnC=make('div','database-relationship-column database-relationship-table-column');add(columnC,'div','database-relationship-column-label','业务表与投影');const groups={};tables.forEach(table=>{const group=table.description||'产品数据';(groups[group]||(groups[group]=[])).push(table)});Object.keys(groups).sort().forEach(group=>{const groupBox=make('details','database-relationship-group');const groupSummary=make('summary');add(groupSummary,'strong','',group);add(groupSummary,'span','',groups[group].length+' 张表');groupBox.appendChild(groupSummary);const nodes=make('div','database-relationship-group-nodes');groups[group].forEach(table=>{const node=make('article','database-relationship-node database-relationship-node-table');add(node,'strong','',table.label||'表');add(node,'span','',fmt(table.estimatedRows||0)+' 行估算');nodes.appendChild(node)});groupBox.appendChild(nodes);columnC.appendChild(groupBox)});if(!tables.length)columnC.appendChild(make('div','database-relationship-empty','未读取到业务表元数据'));canvas.appendChild(columnC);body.appendChild(canvas);
        const relationEdges=(graph.edges||[]).filter(edge=>edge.kind==='foreign_key'||edge.kind==='masked_view');const relations=make('details','database-relationship-relations');const relationSummary=make('summary');add(relationSummary,'strong','','关键关系');add(relationSummary,'span','',relationEdges.length+' 条，按需展开');relations.appendChild(relationSummary);const relationList=make('div','database-relationship-relation-list');if(!relationEdges.length)add(relationList,'div','database-relationship-empty','当前数据库没有可展示的外键；ops_ai 脱敏层仍由中心库统一供给。');relationEdges.slice(0,80).forEach(edge=>{const row=make('div','database-relationship-relation');const source=(graph.nodes||[]).find(node=>node.id===edge.source);const target=(graph.nodes||[]).find(node=>node.id===edge.target);add(row,'code','',source?source.label:edge.source);add(row,'span','database-relationship-arrow',edge.kind==='masked_view'?'⇢':'→');add(row,'code','',target?target.label:edge.target);add(row,'small','',edge.label||edge.kind);relationList.appendChild(row)});relations.appendChild(relationList);body.appendChild(relations);if(summary.truncated)add(body,'div','database-relationship-note','表数量较多，图中只保留前 80 张表及其外键端点；请用下方“全部表与维护状态”查看完整目录。');panel.appendChild(body);return panel;
      }
`;
