/** 模型池控制面：与可观测数据同页，但所有写操作仍走运营权限 + 网关 admin API。 */
export const OPS_OBSERVABILITY_SCRIPT_MODEL_POOL = `
      async function loadModelPool(){
        try{const data=await request('/api/ops/observability/model-pool');state.modelPool=data;renderModelPool()}catch(error){if(error.message!=='not_authorized')toast('模型池加载失败：'+friendlyError(error.message),false)}}
      function modelStateName(value){return ({healthy:'正常',half_open:'半开',cooldown:'冷却',degraded:'退化'})[value]||value||'未知'}
      function modelStateClass(value){return value==='healthy'?'good':(value==='cooldown'?'bad':(value==='half_open'?'warn':''))}
      function modelTargetName(target){return (target.frontendModels&&target.frontendModels[0])||target.label||target.model}
      function renderModelPool(){
        const root=$('modelPoolContent');if(!root)return;root.replaceChildren();
        if(!state.modelPool){add(root,'div','empty','正在读取模型池状态…');loadModelPool();return}
        const health=state.modelPool.health||{};const config=state.modelPool.config||{};const targets=health.targets||[];const summary=health.summary||{};const mapping=config.modelMapping||{};const protectedFrontendModel=state.modelPool.protectedFrontendModel||'';
        const head=make('div','model-pool-toolbar');const copy=make('div');add(copy,'h2','','模型池状态与路由控制');add(copy,'p','','实时读取 3100/3101 网关状态；变更会写入网关配置并记录运营审计。');head.appendChild(copy);const refresh=add(head,'button','btn','刷新模型池');refresh.type='button';refresh.addEventListener('click',()=>loadModelPool());root.appendChild(head);
        const cards=make('div','metrics model-pool-summary');[['目标总数',summary.totalTargets||0,''],['健康',summary.healthy||0,'good'],['冷却',summary.cooldown||0,summary.cooldown?'bad':'good'],['网关并发',(health.queue&&health.queue.inFlight||0)+' / '+(health.queue&&health.queue.maxInFlight||0),'']].forEach(item=>{const card=make('div','panel metric');add(card,'div','label',item[0]);add(card,'div','value '+item[2],item[1]);add(card,'div','detail','Redis 状态同步');cards.appendChild(card)});root.appendChild(cards);
        const table=make('section','panel table-panel');const title=make('div','table-title');add(title,'h2','','上游目标');add(title,'div','hint','Key 只显示脱敏指纹；“探测”使用当前已加载配置，不接受浏览器直接传 Key。');table.appendChild(title);const scroll=make('div','scroll');const tableEl=make('table');const tr=make('tr');['目标','状态','成功率','延迟 P95','并发','角色','操作'].forEach(v=>add(tr,'th','',v));tableEl.appendChild(tr);targets.forEach(target=>{const row=make('tr');const name=make('td');add(name,'strong','',target.label||target.model);add(name,'div','metric-source',target.model+' · '+target.baseUrl);if(target.credentialFingerprint)add(name,'div','metric-source','Key '+target.credentialFingerprint);row.appendChild(name);const stateCell=make('td');add(stateCell,'span','status-chip '+modelStateClass(target.state),modelStateName(target.state));if(target.lastHealthError)add(stateCell,'div','metric-source',target.lastHealthError);row.appendChild(stateCell);add(row,'td','',target.successRate==null?'—':(Number(target.successRate)*100).toFixed(1)+'%');add(row,'td','',target.latencyP95Ms==null?'—':fmt(target.latencyP95Ms)+' ms');add(row,'td','',(target.inFlight||0)+' / '+(target.maxInFlight||0));add(row,'td','',((target.roles||[]).join('、')||'—'));const action=make('td');const probe=add(action,'button','btn','探测');probe.type='button';probe.addEventListener('click',async()=>{probe.disabled=true;probe.textContent='探测中…';try{await request('/api/ops/observability/model-pool/probe',{method:'POST',body:JSON.stringify({model:modelTargetName(target)})});toast('已完成 '+modelTargetName(target)+' 真实探测');await loadModelPool()}catch(error){toast('探测失败：'+friendlyError(error.message),false)}finally{probe.disabled=false;probe.textContent='探测'}});row.appendChild(action);tableEl.appendChild(row)});scroll.appendChild(tableEl);table.appendChild(scroll);root.appendChild(table);
        const route=make('section','panel model-pool-editor');const routeHead=make('div','section-head');const routeBox=make('div');add(routeBox,'h2','','调整模型优先级');add(routeBox,'div','hint','填写备用映射名称，按从高到低排列；Agent 主路由受保护，避免被临时操作覆盖。');routeHead.appendChild(routeBox);route.appendChild(routeHead);const routeFields=make('div','fields');const editableModels=Object.keys(mapping).filter(k=>k!==protectedFrontendModel);const modelSelect=selectField(routeFields,'modelPoolFrontend','模型映射',editableModels[0]||'',editableModels.map(k=>[k,k]));const fallbackInput=field(routeFields,'modelPoolFallbacks','备用顺序','','text',true);const weightInput=field(routeFields,'modelPoolWeight','主目标权重','','number');route.appendChild(routeFields);const routeFeedback=add(route,'div','feedback','');routeFeedback.id='modelPoolRouteFeedback';const routeButton=add(route,'button','btn primary','保存路由顺序');routeButton.type='button';const syncRoute=()=>{const current=mapping[modelSelect.value]||{};fallbackInput.value=(current.fallbacks||[]).map(v=>typeof v==='string'?v:(v&&v.ref)||'').filter(Boolean).join(', ');weightInput.value=current.weight==null?'':String(current.weight)};modelSelect.addEventListener('change',syncRoute);syncRoute();routeButton.addEventListener('click',async()=>{const fallbacks=fallbackInput.value.split(',').map(v=>v.trim()).filter(Boolean);const weight=weightInput.value.trim()===''?undefined:Number(weightInput.value);if(new Set(fallbacks).size!==fallbacks.length){setFeedback('modelPoolRouteFeedback','备用目标不能重复',false);return}routeButton.disabled=true;try{await request('/api/ops/observability/model-pool/routing',{method:'PUT',body:JSON.stringify({frontendModel:modelSelect.value,fallbacks,weight})});toast('模型优先级已更新');await loadModelPool()}catch(error){setFeedback('modelPoolRouteFeedback','保存失败：'+friendlyError(error.message),false)}finally{routeButton.disabled=false}});root.appendChild(route);
        const replace=make('section','panel model-pool-editor');const replaceHead=make('div','section-head');const replaceBox=make('div');add(replaceBox,'h2','','替换模型目标');add(replaceBox,'div','hint','需要输入完整 HTTPS 地址、模型名和新 Key。提交前会对新目标做一次真实预探测，失败则不写入网关；替换会保存旧目标快照，可用下方回滚恢复。');replaceHead.appendChild(replaceBox);replace.appendChild(replaceHead);const replaceFields=make('div','fields');const replaceModel=selectField(replaceFields,'modelPoolReplace','要替换的映射',editableModels[0]||'',editableModels.map(k=>[k,k]));const replaceBase=field(replaceFields,'modelPoolBase','Base URL','','url');const replaceName=field(replaceFields,'modelPoolModel','上游模型','','text');const replaceLabel=field(replaceFields,'modelPoolLabel','展示名称','','text');const replaceKey=field(replaceFields,'modelPoolKey','API Key（仅本次提交）','','password',true);replace.appendChild(replaceFields);const replaceButton=add(replace,'button','btn','提交替换');replaceButton.type='button';replaceButton.addEventListener('click',async()=>{if(replaceModel.value===protectedFrontendModel){toast('Agent 主路由受保护，请替换具体备用映射',false);return}if(!replaceBase.value.startsWith('https://')||!replaceName.value.trim()||replaceKey.value.length<20){toast('请填写有效 HTTPS 地址、模型名和 Key',false);return}if(!window.confirm('确认替换 '+replaceModel.value+'？将先预探测新目标，通过后才写入网关配置。旧目标会存快照（不含 Key），可随时回滚。'))return;replaceButton.disabled=true;try{await request('/api/ops/observability/model-pool/replace',{method:'PUT',body:JSON.stringify({confirm:'REPLACE',frontendModel:replaceModel.value,target:{baseUrl:replaceBase.value.trim(),model:replaceName.value.trim(),label:replaceLabel.value.trim(),apiKey:replaceKey.value}})});replaceKey.value='';toast('模型目标已替换（预探测通过）。如需恢复，使用下方回滚。');await loadModelPool()}catch(error){const detail=error&&error.preflight?('预探测 '+(error.preflight.errorCategory||'失败')+' · HTTP '+(error.preflight.status==null?'—':error.preflight.status)+' · '+(error.preflight.elapsedMs||0)+'ms，未写入网关'):friendlyError(error.message);toast('替换失败：'+detail,false)}finally{replaceButton.disabled=false}});root.appendChild(replace);
        const rollback=make('section','panel model-pool-editor');const rollbackHead=make('div','section-head');const rollbackBox=make('div');add(rollbackBox,'h2','','回滚最近一次替换');add(rollbackBox,'div','hint','按替换前快照恢复旧目标；快照不保存 Key，需要重新输入原 Key 才能回滚。回滚前同样先预探测。');rollbackHead.appendChild(rollbackBox);rollback.appendChild(rollbackHead);const rollbackFields=make('div','fields');const rollbackModel=selectField(rollbackFields,'modelPoolRollback','要回滚的映射',editableModels[0]||'',editableModels.map(k=>[k,k]));const rollbackKey=field(rollbackFields,'modelPoolRollbackKey','原目标 API Key（仅本次提交）','','password',true);rollback.appendChild(rollbackFields);const rollbackFeedback=add(rollback,'div','feedback','');rollbackFeedback.id='modelPoolRollbackFeedback';const rollbackButton=add(rollback,'button','btn','回滚到替换前目标');rollbackButton.type='button';rollbackButton.addEventListener('click',async()=>{if(!window.confirm('确认回滚 '+rollbackModel.value+' 到最近一次替换前的目标？'))return;rollbackButton.disabled=true;try{await request('/api/ops/observability/model-pool/rollback',{method:'POST',body:JSON.stringify({confirm:'ROLLBACK',frontendModel:rollbackModel.value,apiKey:rollbackKey.value})});rollbackKey.value='';setFeedback('modelPoolRollbackFeedback','已回滚',true);toast('已回滚到替换前目标（预探测通过）');await loadModelPool()}catch(error){const detail=friendlyError(error.message);const snap=error&&error.snapshot&&error.snapshot.previous?('替换前快照：'+(error.snapshot.previous.model||'?')+' @ '+(error.snapshot.previous.baseUrl||'?')+'（'+(error.snapshot.occurredAt||'时间未知')+'）'):'没有可用的替换前快照';setFeedback('modelPoolRollbackFeedback','回滚未完成：'+detail+' · '+snap,false)}finally{rollbackButton.disabled=false}});root.appendChild(rollback);
      }
      // 手动展开“模型池”折叠区时也要渲染内容，不能只在 #model-pool 深链进入时才画。
      const modelPoolDisclosure=$('platform-model');if(modelPoolDisclosure)modelPoolDisclosure.addEventListener('toggle',()=>{if(!modelPoolDisclosure.open)return;const content=$('modelPoolContent');if(content&&content.childElementCount)return;renderModelPool()});
`;
