/**
 * Product design layer for the observability workspace.
 *
 * The existing page styles own component behaviour and responsive fallbacks.
 * This final layer owns the visual hierarchy: a calm operations shell, one
 * impact-first status surface, readable rule density, and a focused editor.
 */
export const OPS_OBSERVABILITY_PRODUCT_STYLE = `
    .model-pool-topo{padding:14px 16px}.mp-topo-svg{display:block;width:100%;height:auto}.mp-node{cursor:pointer}.mp-node-rect{fill:var(--panel2);stroke:var(--line)}.mp-node:hover .mp-node-rect{stroke:var(--blue)}.mp-locked .mp-node-rect{stroke-dasharray:4 3}.mp-node-title{font-size:12px;font-weight:600;fill:var(--text)}.mp-node-sub{font-size:10px;fill:var(--muted)}.mp-edge-primary{fill:none;stroke:var(--blue);stroke-opacity:.75;stroke-linecap:round}.mp-edge-fallback{fill:none;stroke:var(--muted);stroke-width:1.4;stroke-dasharray:5 5;stroke-opacity:.6;stroke-linecap:round}.mp-edge-weight{font-size:10px;font-weight:600;fill:var(--blue);paint-order:stroke;stroke:var(--panel);stroke-width:3px}.mp-edge-order{font-size:10px;font-weight:600;fill:var(--muted);paint-order:stroke;stroke:var(--panel);stroke-width:3px}.mp-node-accent{fill:var(--blue);opacity:.4}.mp-state-dot{stroke:var(--line)}.mp-state-dot.mp-state-healthy{fill:var(--c27)}.mp-state-dot.mp-state-half_open,.mp-state-dot.mp-state-degraded{fill:var(--orange)}.mp-state-dot.mp-state-cooldown{fill:var(--red)}.mp-state-dot.mp-state-unknown,.mp-state-dot.mp-state-missing{fill:var(--muted)}.mp-node-rect.mp-state-missing{stroke-dasharray:4 3}
    .mp-bar{height:5px;margin-top:5px;border-radius:999px;background:var(--panel2);overflow:hidden}.mp-bar-fill{display:block;height:100%;border-radius:999px;background:var(--blue)}.mp-bar-fill.mp-bar-good{background:var(--c27)}.mp-bar-fill.mp-bar-warn{background:var(--orange)}.mp-bar-fill.mp-bar-bad{background:var(--red)}
    .mp-route-row{display:grid;grid-template-columns:minmax(180px,1.2fr) 130px minmax(220px,2fr) auto;gap:12px;align-items:end;padding:12px 0;border-top:1px solid var(--line)}.model-pool-routes .mp-route-row:first-of-type{border-top:0}.mp-route-row.locked{opacity:.75}.mp-route-info strong{font-size:13px}.mp-route-field{display:flex;flex-direction:column;gap:4px}.mp-route-field label{font-size:11px;color:var(--muted)}.mp-route-field input{min-height:32px;padding:6px 9px;border:1px solid var(--line);border-radius:8px;background:var(--panel);color:var(--text);font:inherit;font-size:12px}.mp-route-row.mp-flash{animation:mpFlash 1.5s ease 1}@keyframes mpFlash{0%,55%{background:var(--panel2)}100%{background:transparent}}
    @media(max-width:900px){.mp-route-row{grid-template-columns:1fr 1fr}.mp-route-field.grow{grid-column:1/-1}}
    @scope (body.ops-observability){
    :scope{
      /* color-scheme 由 :root（亮）与 html[data-theme="dark"]（暗）统管，这里不再钉死 light，
         否则暗色下原生控件仍是亮色外观。 */
      --bg:var(--c327);
      --panel:var(--c378);
      --panel2:var(--c111);
      --line:var(--c379);
      --line2:var(--c380);
      --text:var(--c381);
      --muted:var(--c382);
      --green:var(--c383);
      --green-strong:var(--c384);
      --green-soft:var(--c385);
      --orange:var(--c386);
      --red:var(--c387);
      --blue:var(--c388);
      --purple:var(--c389);
      --shell:var(--c390);
      --shell-soft:var(--c391);
      --shadow:0 10px 30px var(--c392),0 1px 2px var(--c393);
      --shadow-soft:0 1px 2px var(--c394);
    }
    :scope{scrollbar-gutter:stable;background:var(--bg);font:14px/1.55 Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;letter-spacing:-.005em}
    button,input,select,textarea{font:inherit}
    button{transition:background-color .16s ease,border-color .16s ease,color .16s ease,box-shadow .16s ease,transform .16s ease}
    ::selection{background:var(--c395);color:var(--c396)}

    header{height:60px;padding:0 24px;gap:16px;background:var(--shell-head);color:var(--c2);border-bottom:1px solid var(--c6);box-shadow:0 1px 0 var(--c397)}
    .brand{min-width:184px;gap:10px}.brand-mark{width:32px;height:32px;border-radius:9px;background:linear-gradient(145deg,var(--c398),var(--c383));box-shadow:inset 0 1px 0 var(--c399),0 6px 16px var(--c400);font:800 16px/1 ui-monospace,SFMono-Regular,Menlo,monospace}.brand-copy{font-size:14px;font-weight:720;letter-spacing:.015em}.brand-copy small{margin-top:3px;color:var(--c401);font-size:9px;font-weight:540;letter-spacing:.06em;text-transform:uppercase}
    .header-context{display:flex;align-items:center;gap:10px;margin-left:18px;color:var(--c402);font-size:11px}.header-product{color:var(--c403);font-weight:650;letter-spacing:.08em}.header-divider{width:1px;height:15px;background:var(--c404)}.header-live{display:inline-flex;align-items:center;gap:7px;margin-left:auto;padding:6px 10px;border:1px solid var(--c7);border-radius:999px;background:var(--c405);color:var(--c406);font-size:11px}.header-live:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--c407);box-shadow:0 0 0 3px var(--c408)}.header-live.live:before{background:var(--c373);box-shadow:0 0 0 3px var(--c409)}.header-live.stale:before{background:var(--c410);box-shadow:0 0 0 3px var(--c411)}.header-live.error:before,.header-live.unauthorized:before{background:var(--c412);box-shadow:0 0 0 3px var(--c413)}

    .app-shell{grid-template-columns:216px minmax(0,1fr);min-height:calc(100vh - 60px)}
    .side-nav{top:60px;height:calc(100vh - 60px);padding:16px 12px;background:var(--panel);border-right:1px solid var(--line);box-shadow:none}
    .global-nav{gap:3px;margin-bottom:14px;padding-bottom:14px;border-bottom-color:var(--c6)}
    .global-nav .nav-section,.nav-title,.nav-section{color:var(--c416);font-size:10px;font-weight:700;letter-spacing:.12em;text-transform:uppercase}
    .global-tab{min-height:38px;padding:9px 10px;border-radius:8px;color:var(--c417);font-size:12px}.global-tab:before{width:16px;border-left:2px solid var(--c418)}.global-tab:hover{background:var(--c419);color:var(--c2)}.global-tab.active{background:var(--c420);color:var(--c421)}.global-tab.active:before{border-color:var(--c373)}
    .nav-title{padding:0 9px 9px}.nav-title-secondary{border-top-color:var(--c6)}
    .nav-primary .module-tab{min-height:40px;background:transparent;color:var(--text);box-shadow:none}.nav-primary .module-tab:before{color:var(--c424)}.nav-primary .module-tab .tab-count{background:var(--c425);color:var(--c426)}.nav-primary .module-tab.active{background:var(--c422);box-shadow:inset 3px 0 0 var(--c373)}
    .nav-group{border-top:1px solid var(--line)}
    .nav-section-toggle{position:relative;display:flex;align-items:center;gap:8px;min-height:36px;margin-top:4px;padding:8px 10px;border-radius:8px;color:var(--c428);font-size:12px;font-weight:650;cursor:pointer;list-style:none;user-select:none}
    .nav-section-toggle::-webkit-details-marker{display:none}
    .nav-section-toggle:hover{background:var(--c419);color:var(--c428)}
    .nav-section-toggle:focus-visible{outline:2px solid var(--c424);outline-offset:1px}
    .nav-toggle-caret{flex:0 0 auto;width:0;height:0;border-left:4px solid var(--muted);border-top:4px solid transparent;border-bottom:4px solid transparent;border-right:0;transition:transform .16s ease}
    .nav-group[open]>.nav-section-toggle>.nav-toggle-caret{transform:rotate(90deg)}
    .nav-toggle-label{flex:1 1 auto;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
    .nav-group-alert{flex:0 0 auto;min-width:18px;padding:1px 6px;border-radius:999px;background:var(--c430);color:var(--c431);font-size:10px;font-weight:700;text-align:center}
    .nav-group.has-alert>.nav-section-toggle{color:var(--c432)}
    .nav-group-items{display:grid;gap:2px;margin:2px 0 4px;padding-left:10px;border-left:1px solid var(--c433)}
    .module-tab{min-height:39px;padding:9px 10px;border-radius:8px;color:var(--c434);font-size:12px}.module-tab:before{color:var(--c435)}.module-tab:hover{background:var(--c419);color:var(--c434)}.module-tab.active{background:var(--c422);color:var(--c436);box-shadow:inset 3px 0 0 var(--c373)}.module-tab.active:before{color:var(--c424)}.tab-count{background:var(--panel2);color:var(--muted);font-size:11px}.module-tab.active .tab-count{background:var(--c438);color:var(--c436)}

    main{display:block;min-width:0;padding:24px 28px 48px}
    .view{grid-column:1/-1}
    .page-head{align-items:center;margin:0 0 16px}.page-kicker{margin-bottom:5px;color:var(--c439);font-size:10px;font-weight:700;letter-spacing:.09em;text-transform:uppercase}.page-head h1{margin:0 0 6px;font-size:26px;line-height:1.25;font-weight:720;letter-spacing:-.035em}.page-head .page-intro{max-width:760px;margin-top:0!important;color:var(--c440)!important;font-size:13px!important}.page-head-actions{align-self:center;gap:8px}
    .env-pill{height:34px;padding:5px 11px;border-color:var(--c441);border-radius:999px;background:var(--c2);color:var(--c442);font-size:10px;font-weight:650;box-shadow:var(--shadow-soft)}.env-pill:before{background:var(--c443);box-shadow:0 0 0 3px var(--c444)}
    .btn{height:36px;padding:5px 13px;border-color:var(--c445);border-radius:8px;background:var(--c2);font-size:12px;font-weight:620;box-shadow:0 1px 1px var(--c446)}.btn:hover{border-color:var(--c447);background:var(--c194);color:var(--green);box-shadow:0 3px 10px var(--c448);transform:translateY(-1px)}.btn:active{transform:translateY(0)}.btn.primary{background:var(--green);border-color:var(--green);color:var(--c2);box-shadow:0 5px 14px var(--c449)}.btn.primary:hover{background:var(--green-strong);border-color:var(--green-strong);color:var(--c2)}.btn:disabled{transform:none;box-shadow:none}

    /* Single context band: 页头是唯一的标题层，状态事实与操作控件都收在右侧，
       不再叠加 workspace-toolbar / global-command-bar 第二、第三条横带。 */
    .page-head-actions{display:flex;flex-direction:column;align-items:flex-end;gap:8px}
    .page-head-controls{display:flex;align-items:center;gap:8px;flex-wrap:wrap;justify-content:flex-end}
    .scope-control{display:inline-flex;align-items:center;gap:7px;font-size:12px;color:var(--muted)}.scope-control select{height:32px;border-color:var(--line2);border-radius:6px;font-size:12px;background:var(--c2);font-weight:600}.scope-control.hidden{display:none}
    .scope-status{display:none}
    .workspace-facts{display:flex;align-items:center;justify-content:flex-end;gap:14px;color:var(--muted);font-size:11px;white-space:nowrap}
    #fresh{color:var(--muted);font-size:11px}
    .workspace-fact{display:inline-flex;align-items:center;gap:5px}.workspace-fact:before{content:'';width:6px;height:6px;border-radius:50%;background:var(--c19)}.workspace-fact.warn:before{background:var(--orange)}.workspace-fact.bad:before{background:var(--red)}.workspace-fact strong{color:var(--text);font-size:11px}
    header .domain-switcher{margin:0;padding:3px;flex-shrink:0;background:var(--c6);border-color:var(--c7);border-radius:8px}header .domain-hint{display:none}header .domain-tab{padding:5px 12px;color:var(--c5)}header .domain-tab[aria-selected="true"]{background:var(--green);color:var(--c2);box-shadow:none}
    header .global-search-trigger{flex:0 1 320px;width:auto;min-width:170px;min-height:34px;margin-left:auto;padding:5px 10px;border-color:var(--c7);border-radius:7px;background:var(--c6);color:var(--c5);box-shadow:none}header .global-search-trigger:before{width:20px;height:20px;background:transparent;color:var(--c5);font-size:18px}header .global-search-copy strong{font-size:12px;font-weight:500}header .global-search-copy small{display:none}header .global-search-trigger kbd{padding:1px 5px;background:var(--c6);color:var(--c5);border-color:var(--c7)}
    header .theme-toggle{margin:0;height:32px;min-width:32px;background:transparent;color:var(--c2);border-color:var(--c7)}header .header-live{flex-shrink:0;margin:0;padding:6px 10px;border:1px solid var(--c7);background:var(--c405);color:var(--c406);white-space:nowrap;font-size:11px}
    .module-switcher{gap:24px;padding:0;border:0;border-bottom:1px solid var(--line);border-radius:0;background:transparent;margin:0 0 16px;flex-wrap:nowrap;overflow:auto}.module-switch-tab{flex:0 0 auto;min-height:42px;padding:8px 2px 11px;border-radius:0;border-bottom:2px solid transparent;font-size:13px;white-space:nowrap}.module-switch-tab small{display:none}.module-switch-tab.is-active{background:transparent;color:var(--green);border-bottom-color:var(--green)}.module-switch-tab:focus-visible{outline:2px solid var(--green);outline-offset:-2px}

    .panel{border:1px solid var(--line);border-radius:12px;background:var(--c2);box-shadow:var(--shadow-soft)}.section,.action-center,.coverage-panel,.impact-panel,.north-star-panel,.incident-section{padding:20px}.section-head{margin-bottom:16px}.section-head h2,.table-title h2{font-size:15px;font-weight:700;letter-spacing:-.01em}.hint{margin-top:4px;color:var(--c458);font-size:11px}.section-head .right{color:var(--c459);font-size:11px}
    .detail-sections{margin-top:14px;border-color:var(--line);border-radius:12px;background:var(--c2);box-shadow:var(--shadow-soft)}.detail-summary{min-height:52px;padding:14px 18px;color:var(--c460);font-size:13px;list-style:none}.detail-summary::-webkit-details-marker{display:none}.detail-summary:after{content:"⌄";margin-left:auto;color:var(--c461);font-size:14px;transition:transform .16s ease}.detail-sections[open]>.detail-summary:after{transform:rotate(180deg)}.detail-summary strong{font-weight:700}.detail-summary span{color:var(--c462);font-size:11px}.detail-sections[open]>.detail-summary{border-bottom-color:var(--line);background:var(--c141)}.detail-sections>*:not(.detail-summary){margin:16px}

    .situation-hero{min-height:116px;padding:22px 24px;border:0;border-radius:14px;background:linear-gradient(130deg,var(--c463) 0%,var(--c464) 68%,var(--c465) 100%);box-shadow:0 14px 32px var(--c466)}.situation-hero.warning,.situation-hero.stale,.situation-hero.critical{border:0}.situation-hero:after{right:-50px;top:-90px;width:260px;height:260px;background:radial-gradient(circle,var(--c467),transparent 68%)}.situation-hero .hero-icon{width:48px;height:48px;border:1px solid var(--c7);background:var(--c7);color:var(--c2);box-shadow:inset 0 1px 0 var(--c7)}.situation-hero.warning .hero-icon,.situation-hero.stale .hero-icon{background:var(--c468);color:var(--c469)}.situation-hero.critical .hero-icon{background:var(--c470);color:var(--c471)}.situation-hero .hero-title{color:var(--c2);font-size:21px;font-weight:700}.situation-hero .hero-detail{margin-top:5px;color:var(--c472);font-size:12px}.situation-hero .right{position:relative;color:var(--c473);font-size:11px}.situation-meta span{border:1px solid var(--c7);background:var(--c474);color:var(--c475)}.situation-hero .hero-cta{position:relative;z-index:1;height:34px;margin-top:12px;border-color:var(--c476);background:var(--c2);color:var(--c477);box-shadow:none}.situation-hero .hero-cta:hover{border-color:var(--c2);background:var(--c478);color:var(--c479)}
    .north-star-grid{gap:10px}.north-star-card{min-height:136px;padding:15px;border-color:var(--c480);border-radius:10px;background:var(--c113)}.north-star-card:hover{border-color:var(--c481);box-shadow:0 5px 14px var(--c482)}.north-star-head strong{font-size:12px}.north-star-value{font-size:28px;letter-spacing:-.025em}.north-star-meta,.north-star-target{font-size:10px}.north-star-bar{height:6px}
    .unified-focus{grid-template-columns:minmax(0,1.32fr) minmax(320px,.68fr);gap:14px}.action-list,.signal-coverage{gap:8px}.action-row,.signal-row{border-color:var(--c483);border-radius:9px;background:var(--c113)}.action-row:hover,.signal-row:hover{border-color:var(--c484);background:var(--c57)}.action-copy strong,.signal-name{font-size:12px}.action-copy small,.signal-stat span{font-size:10px}.action-row .btn{height:31px;font-size:10px}
    .pulse-grid{gap:12px}.pulse-card,button.pulse-card{min-height:142px;padding:16px 17px;border:1px solid var(--line);border-top:1px solid var(--line);border-left:4px solid var(--c443);border-radius:12px;background:var(--c2)}.pulse-card.warning,button.pulse-card.warning{border-left-color:var(--orange)}.pulse-card.critical,button.pulse-card.critical{border-left-color:var(--red)}.pulse-card:hover{border-color:var(--c485);box-shadow:0 8px 22px var(--c392);transform:translateY(-2px)}.pulse-label strong{font-size:12px}.pulse-value{font-size:27px;font-weight:720;letter-spacing:-.025em}.pulse-detail{font-size:10px;line-height:1.5}.pulse-link{font-size:10px;font-weight:650}
    .incident-grid{gap:12px}.incident-card{padding:17px;border-radius:10px}.incident-title{font-size:14px}.incident-summary{font-size:12px}.incident-sub,.incident-note{font-size:11px}.incident-fact{min-height:62px;padding:11px}.incident-fact span{font-size:10px}.incident-fact strong{font-size:12px}
    .metrics{gap:10px}.metric{min-height:96px;padding:16px}.metric .label{font-size:11px}.metric .value{font-size:27px;font-weight:700;letter-spacing:-.02em}.metric .detail{font-size:11px}.impact-grid{align-items:start}.impact-panel{align-self:start}.impact-health-metrics{grid-template-columns:repeat(3,minmax(0,1fr));margin-bottom:0}.impact-health-metrics .metric{min-width:0;min-height:92px;padding:13px}.impact-health-metrics .metric .value{font-size:20px;line-height:1.2;overflow-wrap:anywhere}.impact-health-metrics .metric .detail{line-height:1.4;overflow-wrap:anywhere}.incident-grid.single{grid-template-columns:minmax(0,760px);justify-content:start}.rule-mobile-meta,.rule-expand{display:none}.row-action{display:flex;justify-content:flex-end;gap:4px}

    #alerts-rules[open]{border-color:var(--c156)}.rule-summary{gap:10px;margin:16px}.summary-card{min-height:98px;padding:16px;border:1px solid var(--c486);border-radius:10px;box-shadow:none}.summary-label{color:var(--c487);font-size:11px;font-weight:620}.summary-value{margin-top:4px;color:var(--c488);font-size:28px;font-weight:720;letter-spacing:-.025em}.summary-note{margin-top:3px;font-size:10px}.strategy-card{margin:16px!important;padding:0;border:1px solid var(--c489);border-radius:11px;box-shadow:none}.strategy-card .toolbar{min-height:58px;margin:0;padding:12px 14px;border-bottom:1px solid var(--line);background:var(--c113)}.strategy-card .rules-panel{margin:0}.search-wrap{width:420px}.search{height:36px;border-color:var(--c490);border-radius:8px;font-size:12px}.search-wrap:before{top:7px;color:var(--c491)}.filter-trigger{height:36px}.filter-popover{top:44px;border-color:var(--c492);border-radius:11px;box-shadow:0 18px 42px var(--c493)}
    .rules-head,.rule-row{grid-template-columns:minmax(250px,1.45fr) 78px minmax(210px,1.15fr) 128px 152px 132px 76px 48px;gap:13px;min-width:1160px}.rules-head{position:sticky;top:0;z-index:4;padding:11px 16px;background:var(--c494);color:var(--c495);font-size:10px;font-weight:720;letter-spacing:.065em;text-transform:uppercase}.rule-row{min-height:76px;padding:13px 16px;background:var(--c2)}.rule-row:hover{background:var(--c194)}.rule-main{gap:11px}.state-dot{width:9px;height:9px;margin-top:5px;box-shadow:0 0 0 3px var(--c496)}.state-dot.warning,.state-dot.observing{box-shadow:0 0 0 3px var(--c497)}.state-dot.critical,.state-dot.stale{box-shadow:0 0 0 3px var(--c498)}.rule-title{color:var(--c499);font-size:12px;font-weight:700}.rule-meta{margin-top:4px;color:var(--c500);font:10px/1.35 ui-monospace,SFMono-Regular,Menlo,monospace}.rule-condition{color:var(--c501);font-size:11px;font-weight:600;line-height:1.45}.rule-condition small,.rule-eval small{margin-top:3px;font-size:10px;font-weight:500}.category-chip,.channel-chip,.status-chip{border-radius:999px;padding:3px 8px;font-size:10px;font-weight:650}.rule-eval{font-size:11px;font-weight:650}.strategy-toggle{width:54px;height:26px;border-radius:999px;font-size:10px;font-weight:700}.icon-btn{width:34px;height:34px;border:1px solid transparent;border-radius:8px;font-size:15px}.icon-btn:hover{border-color:var(--c502);background:var(--c503)}.rules-result-meta{padding:9px 16px;background:var(--c141);font-size:11px}
    .catalog-guide{padding:13px 16px}.catalog-guide strong{font-size:13px}.catalog-guide span{font-size:11px}.metric-head,.metric-row{font-size:11px}.metric-row{min-height:64px}.metric-source{font-size:10px}

    .drawer-backdrop{background:var(--c504);backdrop-filter:blur(4px)}.drawer{width:min(920px,100%);background:var(--c91);box-shadow:-24px 0 70px var(--c505)}.drawer-head{min-height:78px;padding:18px 22px;border-bottom-color:var(--c506)}.drawer-head h2{font-size:21px;font-weight:720;letter-spacing:-.02em}.drawer-head p{margin-top:4px;font:10px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace}.drawer-body{padding:18px 20px 28px;gap:14px}.editor-stepper{top:-18px;gap:6px;padding:9px 0 10px;background:var(--c91);border-bottom:0}.editor-step-link{min-height:36px;border:1px solid var(--c452);border-radius:8px!important;background:var(--c2);color:var(--c507);font-size:10px;font-weight:650}.editor-step-link:hover{border-color:var(--c508);background:var(--c503);color:var(--green)}.editor-section{padding:18px;border:1px solid var(--c489);border-radius:11px;box-shadow:var(--shadow-soft)}.editor-section h3{margin-bottom:4px;font-size:14px;font-weight:720}.editor-section>p{margin-bottom:14px;font-size:10px}.source-grid{gap:9px}.source-item{padding:11px;border-color:var(--c480);border-radius:8px}.source-item span{font-size:9px}.source-item strong{margin-top:3px;font-size:11px}.expression{padding:12px;border-color:var(--c509);border-radius:8px;background:var(--c510);color:var(--c511);font-size:11px;line-height:1.55}.rule-flow{gap:8px;margin-top:12px}.flow-step{padding:10px 8px;border-color:var(--c480);border-radius:8px;background:var(--c44);font-size:9px}.flow-step strong{font-size:10px}.recommendation{padding:10px 11px;border:1px solid var(--c512);border-radius:8px;background:var(--c513);font-size:10px}.field{gap:6px}.field label{color:var(--c514);font-size:11px;font-weight:620}.field input,.field select,.field textarea{min-height:39px;padding:8px 10px;border-color:var(--c490);border-radius:8px;font-size:12px}.field textarea{min-height:100px}.live-check{padding:13px;border-radius:8px}.live-check strong{font-size:12px}.live-check span{font-size:10px}.drawer-foot{min-height:66px;padding:14px 20px;border-top-color:var(--c506);box-shadow:0 -8px 20px var(--c515)}.drawer-foot .btn{height:38px}

    .toast{right:24px;bottom:24px;padding:12px 14px;border-radius:10px;box-shadow:0 16px 40px var(--c516)}
    .shell-status{border:1px solid var(--line);border-radius:12px;background:var(--c2)}.shell-status strong{font-size:13px}.shell-status small{font-size:10px}

    @media(max-width:1240px){
      main{grid-template-columns:1fr;padding:24px 22px 48px}.rules-head,.rule-row{grid-template-columns:minmax(230px,1.35fr) 72px minmax(200px,1fr) 124px 78px 48px}.rules-head>:nth-child(5),.rule-row>:nth-child(5),.rules-head>:nth-child(6),.rule-row>.rule-audit{display:none}
    }
    @media(max-width:1024px){
      .app-shell{grid-template-columns:204px minmax(0,1fr)}.side-nav{padding:14px 9px}.page-head{align-items:flex-start;flex-direction:column}.page-head h1{font-size:27px}.page-head-actions{margin-left:0;align-items:flex-start}.unified-focus{grid-template-columns:1fr}.pulse-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.rules-head{display:none}.rule-row{grid-template-columns:1fr auto;min-width:0;margin:10px;border:1px solid var(--line);border-radius:10px}.rule-row>:nth-child(2),.rule-row>:nth-child(3),.rule-row>:nth-child(4),.rule-row>:nth-child(5),.rule-row>:nth-child(6){grid-column:1/-1}.rule-row>:nth-child(5){display:block}.drawer-body{grid-template-columns:1fr 1fr}.model-pool-editor .fields{grid-template-columns:repeat(2,minmax(0,1fr))}
    }
    @media(max-width:720px){
      header{height:58px;padding:0 14px}.header-context,.header-live,.brand-copy small{display:none}.app-shell{display:block;min-height:calc(100vh - 58px)}.side-nav{position:static;width:100%;height:auto;padding:8px;background:var(--shell-side);border-right:0;border-bottom:1px solid var(--c6)}.global-nav{display:flex;overflow:auto;margin-bottom:7px;padding-bottom:7px}.global-nav .nav-section,.nav-title{display:none}.module-tabs{display:block}main{padding:20px 14px 40px}.page-head h1{font-size:25px}.page-head-actions{width:100%;overflow:auto}.north-star-grid,.pulse-grid,.metrics,.check-grid,.channel-grid,.settings-grid,.template-summary,.model-pool-editor .fields{grid-template-columns:1fr}.rule-summary{grid-template-columns:repeat(2,minmax(0,1fr));margin:10px}.summary-card{min-height:82px;padding:12px}.summary-value{font-size:24px}.situation-hero{align-items:flex-start;padding:19px}.situation-hero .right{display:none}.drawer-body{grid-template-columns:1fr;padding:14px}.drawer-head{padding:15px}.drawer-foot{padding:11px 12px;flex-wrap:wrap}.drawer-foot .feedback{order:-1;flex:1 0 100%}.editor-stepper{top:-14px;grid-template-columns:repeat(2,minmax(0,1fr))}.search-wrap{width:100%}.filter-anchor{align-self:flex-start}
      .side-nav{padding:7px 8px;overflow:hidden}.global-nav{margin:0;padding:0 0 7px;border:0;gap:5px}.global-tab{min-height:34px;flex:0 0 auto;padding:7px 9px}.nav-primary .module-tab{min-height:36px}.nav-group{border-top-color:var(--c517)}.nav-section-toggle{min-height:36px;margin-top:6px;font-size:11px}.nav-group-items{gap:1px;margin:1px 0 3px;padding-left:8px}.module-tab{min-height:34px;padding:7px 10px;font-size:11px}
      .strategy-card .toolbar{position:sticky;top:58px;z-index:16;align-items:stretch;margin:0;padding:10px 11px;background:var(--c261);box-shadow:0 7px 18px var(--c392);backdrop-filter:blur(12px)}.strategy-card .toolbar .search-wrap{flex:1 1 220px}.rule-row{align-items:start;padding:12px;margin:8px}.rule-mobile-meta{display:block;margin-top:4px;color:var(--c518);font-size:11px}.rule-expand{display:inline-grid;place-items:center}.rule-row>.category-chip,.rule-row>.rule-condition,.rule-row>.rule-eval,.rule-row>.channel-chip,.rule-row>.strategy-toggle,.rule-row>.rule-audit{display:none!important}.rule-row.expanded>.category-chip,.rule-row.expanded>.rule-condition,.rule-row.expanded>.rule-eval,.rule-row.expanded>.channel-chip{display:grid!important;grid-column:1/-1;grid-template-columns:92px minmax(0,1fr);gap:8px;width:100%;padding-top:8px;border-top:1px solid var(--line)}.rule-row.expanded>.strategy-toggle{display:block!important;grid-column:1/-1;justify-self:start;margin-top:5px}.row-action{grid-column:2;grid-row:1;align-items:center}.impact-health-metrics{grid-template-columns:1fr}
    }
    .nav-primary{display:grid;gap:3px}.module-tab{font-size:13px}.module-tab:before{content:"◦";flex:0 0 20px;font-size:15px}.module-tab[data-view="operator-metrics"]:before{content:"↗"}.module-tab[data-view="alerts"]:before{content:"◫"}.module-tab[data-view="traces"]:before{content:"⌁"}.module-tab[data-view="signals"]:before{content:"⌕"}.module-tab[data-view="devices"]:before{content:"▣"}.module-tab[data-view="model-pool"]:before{content:"◇"}.module-tab[data-view="platform"]:before{content:"⚙"}
    @media(max-width:1240px){header{gap:12px;padding:0 18px}.brand{min-width:172px}header .header-live{display:none}.page-head{flex-direction:row}.page-head-actions{margin-left:auto;align-self:center}}
    @media(min-width:521px) and (max-width:900px){.app-shell{grid-template-columns:184px minmax(0,1fr)}.side-nav{position:sticky;top:60px;height:calc(100vh - 60px);padding:12px 8px}.nav-group-items{display:grid}.nav-toggle-label,.nav-group-alert{display:initial}.nav-section-toggle{font-size:12px;justify-content:flex-start}.module-tab{height:auto;min-height:38px;justify-content:flex-start;font-size:12px}.tab-count{display:inline-flex}.nav-group-items{padding-left:4px}.brand{min-width:148px}.brand-copy small{display:none}header{gap:8px}header .global-search-trigger{min-width:100px}header .global-search-trigger kbd{display:none}}
    @media(max-width:720px){header{height:60px;padding:0 12px;gap:8px}.brand{min-width:0}.brand-copy{font-size:12px}.brand-mark{width:28px;height:28px}header .domain-tab{padding:5px 8px}header .global-search-trigger{min-width:32px;flex:0 0 32px;padding:4px;margin-left:auto;justify-content:center}header .global-search-copy,header .global-search-trigger kbd{display:none}.page-head{flex-direction:column;align-items:flex-start;gap:12px}.page-head-actions{margin-left:0;align-self:flex-start;width:auto;overflow:visible}.page-head h1{font-size:24px}main{padding:20px 16px 36px}.workspace-facts{justify-content:flex-start;flex-wrap:wrap;white-space:normal}.workspace-fact{font-size:11px}#fresh{font-size:10px}.module-switcher{gap:20px}.module-switch-tab{flex:0 0 auto}}
    @media(prefers-reduced-motion:reduce){button{transition:none}.detail-summary:after{transition:none}}

    /* Quiet the shell and make the first scan path explicit: context → scope → action. */
    @media(min-width:1241px){main{width:100%;max-width:1480px;margin:0 auto;padding:28px 36px 56px}}
    .page-head{margin-bottom:20px}.page-head h1{font-size:26px}.page-head .page-intro{max-width:820px}
    .side-nav{padding-top:18px}.nav-primary .module-tab{min-height:42px}.nav-group{margin-top:10px}.nav-section-toggle{min-height:40px}
    .panel{box-shadow:var(--shadow-soft)}
    /* The incident center renders seven KPI cards followed by one visual block. Keep
       the visual block on its own row so its height cannot stretch the KPI row. */
    #incidentSummary{grid-template-columns:repeat(4,minmax(0,1fr));align-items:stretch}
    #incidentSummary .ic-viz{grid-column:1/-1;display:grid;grid-template-columns:repeat(2,minmax(180px,1fr)) minmax(260px,1.4fr);align-items:center;gap:20px;margin-top:2px;padding:16px 4px 4px}
    #incidentSummary .ic-trend{min-width:0}
    @media(max-width:900px){#incidentSummary{grid-template-columns:repeat(2,minmax(0,1fr))}#incidentSummary .ic-viz{grid-template-columns:1fr 1fr}}
    @media(max-width:520px){.page-head{margin-bottom:14px}.page-head h1{font-size:24px}.workspace-fact{min-height:26px;padding:3px 8px}#incidentSummary .ic-viz{grid-template-columns:1fr;gap:12px}}

      /* Hierarchy pass: 页头收敛为单层平静横带（标题 + 右侧事实/控件），不再做
         渐变卡片；层次由「页头 → 模块 tab → 面板」三级结构本身承担。 */
      main{position:relative;background:linear-gradient(180deg,var(--c327) 0%,color-mix(in srgb,var(--c327) 92%,var(--c378)) 58%,var(--c327) 100%)}
      main:before{content:"";position:absolute;inset:0 0 auto;height:220px;pointer-events:none;background:radial-gradient(ellipse at 76% 0%,color-mix(in srgb,var(--green) 7%,transparent),transparent 64%);opacity:.9}
      main>*{position:relative}
      .page-head{padding:0 0 14px;margin-bottom:18px;border-bottom:1px solid var(--line)}
      .page-kicker{color:var(--green);font-size:10px}.page-head .page-intro{font-size:13px!important;color:var(--text)!important;opacity:.78}
      .page-head-actions .btn{min-width:88px}.page-head-actions .btn.primary{box-shadow:0 8px 18px color-mix(in srgb,var(--green) 24%,transparent)}
      .domain-note{position:relative;margin:0 0 14px;padding:12px 16px;border:1px solid color-mix(in srgb,var(--blue) 20%,var(--line));border-left:3px solid var(--blue);border-radius:10px;background:color-mix(in srgb,var(--blue) 6%,var(--panel));box-shadow:var(--shadow-soft);font-size:11px}.domain-note strong{color:var(--blue);font-weight:720}
      .view-actions{display:flex;align-items:center;gap:12px;margin:0 0 14px}.view-actions-note{color:var(--muted);font-size:11px}.view-actions .btn{margin-left:auto}
      .overview-stack{gap:16px}.overview-stack>.panel,.overview-stack>details,.overview-stack>.incident-section{position:relative;border-color:color-mix(in srgb,var(--text) 10%,var(--line));box-shadow:0 8px 20px color-mix(in srgb,var(--text) 4%,transparent)}.overview-stack>.panel:before,.overview-stack>details:before,.overview-stack>.incident-section:before{content:"";position:absolute;left:0;top:14px;bottom:14px;width:3px;border-radius:3px;background:color-mix(in srgb,var(--green) 58%,transparent)}
      .section-head{position:relative}.section-head h2:before{content:"";display:inline-block;width:6px;height:6px;margin:0 8px 2px 0;border-radius:50%;background:var(--green);box-shadow:0 0 0 3px color-mix(in srgb,var(--green) 12%,transparent)}
      .panel{border-color:color-mix(in srgb,var(--text) 10%,var(--line));box-shadow:0 7px 18px color-mix(in srgb,var(--text) 5%,transparent),inset 0 1px 0 color-mix(in srgb,var(--c2) 68%,transparent)}
      .situation-hero{box-shadow:0 16px 34px color-mix(in srgb,var(--green) 18%,transparent)}
      .north-star-card,.pulse-card,button.pulse-card,.incident-card,.check,.metric,.summary-card{box-shadow:0 4px 12px color-mix(in srgb,var(--text) 4%,transparent)}
      .north-star-card:hover,.pulse-card:hover,button.pulse-card:hover,.incident-card:hover{transform:translateY(-2px);box-shadow:0 10px 24px color-mix(in srgb,var(--text) 9%,transparent)}
      .rules-head,.metric-head,.template-head{background:linear-gradient(180deg,color-mix(in srgb,var(--panel2) 86%,var(--green)),var(--panel2));border-bottom-color:color-mix(in srgb,var(--green) 13%,var(--line))}
      .rule-row,.metric-row,.template-row{transition:background .16s ease,box-shadow .16s ease}.rule-row:hover,.metric-row:hover,.template-row:hover{box-shadow:inset 3px 0 0 var(--green)}
      .shell-status{padding:20px 22px!important;background:linear-gradient(110deg,var(--panel),color-mix(in srgb,var(--panel) 93%,var(--blue)));box-shadow:var(--shadow)}.shell-status strong{font-size:14px}.shell-status small{margin-top:3px}
      @media(max-width:720px){.page-head{padding-bottom:12px}.page-head h1{font-size:24px}.overview-stack{gap:12px}}
    }
    /* The dark palette uses --c2 for the panel surface, so header content needs
       explicit on-shell colors instead of inheriting the panel token. These
       selectors live outside the scoped block so the html theme attribute can
       participate in the match. */
    html[data-theme="dark"] body.ops-observability header{color:var(--c381)}
    html[data-theme="dark"] body.ops-observability .brand-copy{color:var(--c381)}
    html[data-theme="dark"] body.ops-observability .brand-copy small{color:var(--c401)}
    html[data-theme="dark"] body.ops-observability header .domain-switcher{background:var(--c391);border-color:var(--c397)}
    html[data-theme="dark"] body.ops-observability header .domain-tab{color:var(--c401)}
    html[data-theme="dark"] body.ops-observability header .global-search-trigger{border-color:var(--c397);background:var(--c391);color:var(--c401)}
    html[data-theme="dark"] body.ops-observability header .global-search-trigger:before{color:var(--c401)}
    html[data-theme="dark"] body.ops-observability header .global-search-trigger kbd{background:var(--c391);border-color:var(--c397);color:var(--c401)}
    html[data-theme="dark"] body.ops-observability header .theme-toggle{color:var(--c381);border-color:var(--c397)}
`;
