/** Visual layer for the evidence-first AI SRE action queue. */
export const OPS_OBSERVABILITY_ACTION_LOOP_STYLE = `
    @scope (body.ops-observability){
      .action-loop-panel{padding:18px 20px;border:1px solid #d8e5e1;border-radius:13px;background:linear-gradient(135deg,#f8fcfb 0%,#fff 58%,#fbf9ff 100%);box-shadow:0 8px 24px rgba(16,36,31,.055)}
      .action-loop-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.action-loop-identity{display:flex;gap:11px;min-width:0}.action-loop-orb{display:grid;place-items:center;flex:0 0 38px;width:38px;height:38px;border:1px solid #cde6de;border-radius:11px;background:linear-gradient(145deg,#e4f6f0,#eef0ff);color:#087a67;font-size:10px;font-weight:800;letter-spacing:.05em}.action-loop-kicker{color:#087a67;font-size:9px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.action-loop-head h2{margin:2px 0 0;color:#182a26;font-size:16px;letter-spacing:-.015em}.action-loop-head p{max-width:760px;margin:4px 0 0;color:#63736e;font-size:11px;line-height:1.5}.action-loop-head-actions{display:flex;align-items:center;gap:8px;flex:0 0 auto}.action-loop-count{padding:5px 8px;border:1px solid #dbe6e2;border-radius:999px;background:#fff;color:#63736e;font-size:10px;white-space:nowrap}.action-loop-count.warn{border-color:#f0d5ad;background:#fff8eb;color:#9b5b12}.action-loop-refresh{height:32px;padding:4px 10px;font-size:10px}
      .action-loop-flow{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px;margin:15px 0 14px;padding:7px;border:1px solid #e2ebe8;border-radius:9px;background:#f5f9f7}.action-loop-flow-step{display:flex;align-items:center;justify-content:center;gap:6px;min-height:27px;border-radius:6px;color:#687873;font-size:9px;font-weight:650}.action-loop-flow-step:after{content:'→';margin-left:auto;color:#aab8b3}.action-loop-flow-step:last-child:after{display:none}.action-loop-flow-step.is-active{background:#e4f4ef;color:#087a67}.action-loop-flow-step.is-safe{background:#f0edff;color:#6551a7}
      .action-loop-list{display:grid;gap:9px}.action-loop-card{padding:13px 14px;border:1px solid #dfe8e5;border-radius:10px;background:#fff;transition:border-color .16s ease,box-shadow .16s ease}.action-loop-card:hover{border-color:#bcd9d0;box-shadow:0 5px 16px rgba(16,36,31,.06)}.action-loop-card[data-status='pending_approval']{border-left:3px solid #c96b12}.action-loop-card[data-status='executing']{border-left:3px solid #2368b5}.action-loop-card[data-status='succeeded']{border-left:3px solid #087a67}.action-loop-card[data-status='failed'],.action-loop-card[data-status='verification_failed']{border-left:3px solid #d34852}.action-loop-card[data-status='denied']{border-left:3px solid #899591;background:#fbfcfc}
      .action-loop-card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.action-loop-card-title{display:flex;align-items:flex-start;gap:8px;min-width:0}.action-loop-card-title h3{margin:0;color:#23332f;font-size:12px;line-height:1.4}.action-loop-card-title p{margin:3px 0 0;color:#687873;font-size:10px;line-height:1.45}.action-loop-type{padding:3px 6px;border-radius:5px;background:#eef4f2;color:#4f6a62;font-size:8px;font-weight:750;white-space:nowrap}.action-loop-status{padding:4px 8px;border-radius:999px;background:#f0f3f2;color:#66736f;font-size:9px;font-weight:700;white-space:nowrap}.action-loop-status.pending_approval{background:#fff0dc;color:#9b5b12}.action-loop-status.approved{background:#e9f0ff;color:#315e9e}.action-loop-status.executing{background:#e8f1ff;color:#2368b5}.action-loop-status.succeeded{background:#e4f4ef;color:#087a67}.action-loop-status.failed,.action-loop-status.verification_failed{background:#feecee;color:#b83e48}.action-loop-status.denied{background:#f0f2f1;color:#77827e}
      .action-loop-meta{display:flex;flex-wrap:wrap;gap:6px 12px;margin-top:9px;color:#77847f;font:9px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace}.action-loop-meta span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.action-loop-rationale{margin:9px 0 0;padding:8px 10px;border-radius:7px;background:#f7faf9;color:#4f5f5a;font-size:10px;line-height:1.5}.action-loop-evidence{display:flex;align-items:center;flex-wrap:wrap;gap:5px;margin-top:9px}.action-loop-evidence-label{color:#74827d;font-size:9px;font-weight:650}.action-loop-ref{max-width:230px;padding:3px 7px;border:1px solid #d8e8e2;border-radius:999px;background:#f1f8f5;color:#267267;font:9px ui-monospace,SFMono-Regular,Menlo,monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;cursor:pointer}.action-loop-ref:hover{border-color:#9ccabc;background:#e7f5f0}.action-loop-ref:focus-visible{outline:2px solid rgba(8,122,103,.28);outline-offset:1px}
      .action-loop-footer{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:11px;padding-top:9px;border-top:1px solid #edf1ef}.action-loop-safety{display:flex;align-items:center;gap:5px;color:#677671;font-size:9px}.action-loop-safety strong{color:#087a67}.action-loop-controls{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:6px}.action-loop-controls .btn{height:29px;padding:4px 9px;font-size:10px}.action-loop-controls .btn.danger{border-color:#efc2c5;color:#ad3d46;background:#fff8f8}.action-loop-controls .btn.danger:hover{border-color:#d98b91;background:#fff0f1;color:#9f2e38}.action-loop-playbook{height:29px;max-width:210px;padding:3px 7px;border:1px solid #d4e1dd;border-radius:7px;background:#fff;color:#405a53;font-size:10px}
      .action-loop-empty,.action-loop-state{display:grid;place-items:center;gap:6px;min-height:112px;padding:20px;border:1px dashed #cfdfda;border-radius:9px;background:#fbfdfc;color:#65746f;text-align:center;font-size:10px}.action-loop-empty strong,.action-loop-state strong{color:#2d4a43;font-size:12px}.action-loop-empty span,.action-loop-state span{max-width:600px;line-height:1.5}.action-loop-state.error{border-color:#ecc5c8;background:#fff8f8;color:#a3434b}.action-loop-skeleton{display:grid;gap:8px}.action-loop-skeleton i{display:block;height:13px;border-radius:5px;background:linear-gradient(90deg,#eef3f1 20%,#f8fbfa 50%,#eef3f1 80%);background-size:200% 100%;animation:action-loop-shimmer 1.2s ease-in-out infinite}.action-loop-skeleton i:nth-child(2){width:72%}.action-loop-skeleton i:nth-child(3){width:45%}@keyframes action-loop-shimmer{to{background-position:-200% 0}}
      .action-loop-note{margin-top:11px;padding:8px 10px;border:1px solid #e8dcc9;border-radius:7px;background:#fffaf1;color:#7b5b2e;font-size:9px;line-height:1.5}.action-loop-note strong{margin-right:5px;color:#8e5a16}
      .copilot-action-controls{grid-column:2/-1;display:flex;align-items:center;flex-wrap:wrap;gap:6px;margin-top:7px}.copilot-action-controls .btn{height:27px;padding:3px 8px;font-size:9px}.copilot-action-controls select{height:27px;max-width:220px;border:1px solid #d4e1dd;border-radius:6px;background:#fff;color:#405a53;font-size:9px}.copilot-action-controls .action-created{color:#087a67;font-size:9px;font-weight:650}.copilot-action-controls .action-unavailable{color:#9b5b12;font-size:9px}
      @media(max-width:720px){.action-loop-head{align-items:flex-start;flex-direction:column}.action-loop-head-actions{width:100%;justify-content:space-between}.action-loop-flow{grid-template-columns:repeat(5,minmax(90px,1fr));overflow-x:auto}.action-loop-flow-step{white-space:nowrap}.action-loop-card-head{flex-direction:column}.action-loop-status{align-self:flex-start}.action-loop-footer{align-items:flex-start;flex-direction:column}.action-loop-controls{justify-content:flex-start}.action-loop-playbook{max-width:100%;width:100%}}
      @media(prefers-reduced-motion:reduce){.action-loop-card,.action-loop-skeleton i{transition:none;animation:none}}
    }
`;
