export const OPS_OBSERVABILITY_SCRIPT_STRATEGIES = `      // ---- 自定义策略（P2 策略引擎）：列表 + 三区块编辑抽屉 ----
      // 与理想蓝图同构：基础信息 → 规则行（表格行布局，行内校验）→ 通知渠道。
      let strategyListData=null;let strategyDraft=null;let strategyEditingId=null;let strategyDrawerShell=null;
      (function bindStrategyCreate(){const btn=$('strategyCreateBtn');if(btn)btn.addEventListener('click',()=>openStrategyEditor(null))})();
      const STRATEGY_DURATION_OPTIONS=[[0,'立即'],[60,'连续 1 分钟'],[120,'连续 2 分钟'],[180,'连续 3 分钟'],[300,'连续 5 分钟'],[600,'连续 10 分钟'],[900,'连续 15 分钟'],[1800,'连续 30 分钟'],[3600,'连续 1 小时']];
      const STRATEGY_COMPARATOR_OPTIONS=[['gt','大于 >'],['gte','大于等于 ≥'],['lt','小于 <'],['lte','小于等于 ≤'],['eq','等于 ='],['ne','不等于 ≠']];
      function strategyChannelOptions(){const options=[['default','继承默认渠道']];const channels=state.config&&state.config.notification&&Array.isArray(state.config.notification.channels)?state.config.notification.channels:[];channels.forEach(item=>options.push([item.channel,channelLabel(item.channel)]));if(options.length<2){options.push(['feishu','飞书机器人'],['webhook','通用 Webhook'])}options.push(['none','不发送，仅记录']);return options}
      function emptyStrategyDraft(){return {name:'',description:'',enabled:true,notificationChannel:'default',rules:[{query:'',durationSeconds:300,comparator:'gt',threshold:'',severity:'warning',sendIntervalMinutes:0,noDataAlert:false}]}}
      function ensureStrategyDrawer(){let shell=document.getElementById('strategyDrawer');if(shell)return shell;shell=make('aside','drawer-backdrop');shell.id='strategyDrawer';shell.setAttribute('role','dialog');shell.setAttribute('aria-modal','true');shell.setAttribute('aria-label','编辑自定义策略');const drawer=make('div','drawer');shell.appendChild(drawer);shell.addEventListener('click',event=>{if(event.target===shell)closeStrategyEditor()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&shell.classList.contains('open')){event.preventDefault();closeStrategyEditor()}});document.body.appendChild(shell);return shell}
      function closeStrategyEditor(){const shell=document.getElementById('strategyDrawer');if(shell)shell.classList.remove('open');document.body.style.overflow='';strategyDraft=null;strategyEditingId=null}
      async function loadStrategyList(){const root=$('strategyList');if(!root)return;try{const data=await request('/api/ops/observability/strategies'+(adminTenantQuery()?'?'+adminTenantQuery().slice(1):''));strategyListData=data&&data.ok?data:{strategies:[],canWrite:false}}catch(error){strategyListData=null}renderStrategyList()}
      function renderStrategyList(){const root=$('strategyList');if(!root)return;root.replaceChildren();const list=strategyListData&&Array.isArray(strategyListData.strategies)?strategyListData.strategies:[];const canWrite=Boolean(strategyListData&&strategyListData.canWrite);const createBtn=$('strategyCreateBtn');if(createBtn)createBtn.hidden=!canWrite;if(!list.length){root.replaceChildren(make('div','empty','当前视角没有自定义策略；点击「新建策略」创建第一条 PromQL 阈值策略。'));return}
        const head=make('div','rules-head');['策略名称 / 描述','归属','规则行','级别','告警启停','最近更新','操作'].forEach(value=>add(head,'div','',value));root.appendChild(head);
        list.forEach(strategy=>{const row=make('article','rule-row');const main=make('div','rule-main');const titleBox=make('div');add(titleBox,'div','rule-title',strategy.name);add(titleBox,'div','rule-meta',strategy.description||strategy.id);main.appendChild(titleBox);row.appendChild(main);
          const scope=make('div','');add(scope,'span','category-chip '+(strategy.tenantId==='platform'?'type-metric':'type-log'),strategy.tenantId==='platform'?'公共':strategy.tenantId);row.appendChild(scope);
          add(row,'div','rule-eval',String(strategy.rules.length)+' 条规则');
          const sev=make('div','');strategy.rules.forEach(rule=>add(sev,'span','category-chip '+(rule.severity==='critical'?'type-log':'type-metric'),rule.severity==='critical'?'严重':'告警'));row.appendChild(sev);
          const toggle=make('button','strategy-toggle '+(strategy.enabled?'on':''),strategy.enabled?'开启':'关闭');toggle.type='button';toggle.disabled=!canWrite;toggle.setAttribute('aria-pressed',String(strategy.enabled));toggle.addEventListener('click',()=>toggleStrategyEnabled(strategy,toggle));row.appendChild(toggle);
          add(row,'div','rule-audit',strategy.updatedAt?when(strategy.updatedAt):'—');
          const action=make('div','row-action');const edit=add(action,'button','icon-btn','✎');edit.type='button';edit.title=canWrite?'编辑策略':'仅可查看（公共策略由平台管理员维护）';if(!canWrite&&strategy.tenantId!=='platform'){edit.title='仅租户 owner 可编辑'}edit.addEventListener('click',()=>openStrategyEditor(strategy));const del=add(action,'button','icon-btn','🗑');del.type='button';del.title='删除策略';if(canWrite){del.addEventListener('click',()=>deleteStrategyAction(strategy))}else{del.disabled=true}row.appendChild(action);root.appendChild(row)})}
      async function toggleStrategyEnabled(strategy,toggle){toggle.disabled=true;try{const data=await request('/api/ops/observability/strategies/'+encodeURIComponent(strategy.id),{method:'PUT',body:JSON.stringify({name:strategy.name,description:strategy.description,enabled:!strategy.enabled,notificationChannel:strategy.notificationChannel,rules:strategy.rules.map(rule=>({query:rule.query,durationSeconds:rule.durationSeconds,comparator:rule.comparator,threshold:rule.threshold,severity:rule.severity,sendIntervalMinutes:rule.sendIntervalMinutes,noDataAlert:rule.noDataAlert}))})});toast((!strategy.enabled?'已启用':'已停用')+'策略「'+strategy.name+'」');if(data&&data.strategy){Object.assign(strategy,data.strategy)}}catch(error){toast('修改失败：'+friendlyError(error.message),false)}finally{toggle.disabled=false;renderStrategyList()}}
      async function deleteStrategyAction(strategy){if(!window.confirm('确认删除策略「'+strategy.name+'」？删除后不再评估，历史事故保留。'))return;try{await request('/api/ops/observability/strategies/'+encodeURIComponent(strategy.id),{method:'DELETE'});toast('策略已删除');loadStrategyList()}catch(error){toast('删除失败：'+friendlyError(error.message),false)}}
      function strategyDraftFrom(strategy){return {name:strategy.name,description:strategy.description,enabled:strategy.enabled,notificationChannel:strategy.notificationChannel,rules:strategy.rules.map(rule=>({query:rule.query,durationSeconds:rule.durationSeconds,comparator:rule.comparator,threshold:String(rule.threshold),severity:rule.severity,sendIntervalMinutes:rule.sendIntervalMinutes,noDataAlert:rule.noDataAlert}))}}
      function openStrategyEditor(strategy){const canWrite=Boolean(strategyListData&&strategyListData.canWrite);if(strategy&&!canWrite){toast('该策略由平台管理员维护，当前身份只读',false);return}strategyDraft=strategy?strategyDraftFrom(strategy):emptyStrategyDraft();strategyEditingId=strategy?strategy.id:null;const shell=ensureStrategyDrawer();const drawer=shell.firstElementChild;drawer.replaceChildren();
        const head=make('div','drawer-head');const headCopy=make('div');add(headCopy,'div','page-kicker','自定义策略');add(headCopy,'h2','',strategy?'编辑：'+strategy.name:'新建自定义策略');head.appendChild(headCopy);const closeBtn=add(head,'button','icon-btn','✕');closeBtn.type='button';closeBtn.title='关闭';closeBtn.addEventListener('click',closeStrategyEditor);drawer.appendChild(head);
        const body=make('div','drawer-body');drawer.appendChild(body);
        const base=make('section','editor-section');add(base,'h3','','1. 基础信息');const baseFields=make('div','fields');const nameInput=field(baseFields,'strategyName','策略名称',strategyDraft.name);nameInput.placeholder='如：订单服务错误率告警';const descInput=field(baseFields,'strategyDescription','描述（可选）',strategyDraft.description);const enabledBox=make('div','field');switchField(enabledBox,'strategyEnabled','启用这条策略',strategyDraft.enabled);baseFields.appendChild(enabledBox);base.appendChild(baseFields);body.appendChild(base);
        const ruleSection=make('section','editor-section');add(ruleSection,'h3','','2. 规则设置');add(ruleSection,'p','','每行一个阈值条件：PromQL 即时查询持续命中达到时长即触发；任一规则行触发即产生事故，级别取最高命中的规则行。');
        const ruleHead=make('div','strategy-rules-head');['PromQL 查询','持续时长','比较符','阈值','级别','重复通知','无数据',''].forEach(value=>add(ruleHead,'div','',value));ruleSection.appendChild(ruleHead);const ruleRows=make('div','',);ruleRows.id='strategyRuleRows';ruleSection.appendChild(ruleRows);
        const addRowBar=make('div','form-actions');const addRow=add(addRowBar,'button','btn','＋ 新增规则行');addRow.type='button';addRow.addEventListener('click',()=>{const invalid=validateStrategyDraft();if(invalid){setFeedback('strategyEditorFeedback',invalid.message,false);return}strategyDraft.rules.push({query:'',durationSeconds:300,comparator:'gt',threshold:'',severity:'warning',sendIntervalMinutes:0,noDataAlert:false});renderStrategyRuleRows()});addRowBar.appendChild(addRow);ruleSection.appendChild(addRowBar);body.appendChild(ruleSection);
        const notify=make('section','editor-section');add(notify,'h3','','3. 通知渠道');const notifyFields=make('div','fields');selectField(notifyFields,'strategyChannel','通知渠道',strategyDraft.notificationChannel,strategyChannelOptions(),true);notify.appendChild(notifyFields);add(notify,'div','hint','留「继承默认渠道」时按平台通知路由发送；「不发送」仅记录事故，不发通知。');body.appendChild(notify);
        add(body,'div','feedback','').id='strategyEditorFeedback';
        const foot=make('div','form-actions');const cancel=add(foot,'button','btn','取消');cancel.type='button';cancel.addEventListener('click',closeStrategyEditor);const save=add(foot,'button','btn primary',strategy?'保存修改':'创建策略');save.type='button';save.addEventListener('click',saveStrategy);body.appendChild(foot);
        renderStrategyRuleRows();shell.classList.add('open');document.body.style.overflow='hidden'}
      function strategyRuleInput(index,key){return $('strategy-rule-'+index+'-'+key)}
      function readStrategyRuleRow(index){return {query:String(strategyRuleInput(index,'query').value||'').trim(),durationSeconds:Number(strategyRuleInput(index,'duration').value),comparator:String(strategyRuleInput(index,'comparator').value),threshold:Number(strategyRuleInput(index,'threshold').value),severity:String(strategyRuleInput(index,'severity').value),sendIntervalMinutes:Number(strategyRuleInput(index,'interval').value),noDataAlert:strategyRuleInput(index,'nodata').checked}}
      function validateStrategyDraft(){const draft=strategyDraft;const rows=[...document.querySelectorAll('#strategyRuleRows .strategy-rule-row')];rows.forEach(row=>row.querySelectorAll('.invalid').forEach(node=>node.classList.remove('invalid')));const seen={};for(let index=0;index<rows.length;index+=1){const values=readStrategyRuleRow(index);if(!values.query){markInvalid(index,'query');return{message:'请填写完第 '+(index+1)+' 行的 PromQL 查询后再新增规则行'}}if(!Number.isFinite(values.threshold)){markInvalid(index,'threshold');return{message:'第 '+(index+1)+' 行的阈值必须是有效数字'}}const key=values.query.trim();seen[key]=seen[key]||[];if(seen[key].length>=3){return{message:'相同查询最多添加 3 条规则行'}}if(seen[key].some(severity=>severity===values.severity)){return{message:'相同查询的告警级别不能重复（第 '+(index+1)+' 行）'}}seen[key].push(values.severity)}if(!draft.name.trim()){return{message:'请填写策略名称'}}return null}
      function markInvalid(index,key){const node=strategyRuleInput(index,key);if(node){node.classList.add('invalid');node.focus()}}
      function renderStrategyRuleRows(){const root=$('strategyRuleRows');if(!root||!strategyDraft)return;root.replaceChildren();strategyDraft.rules.forEach((rule,index)=>{const row=make('div','strategy-rule-row');const query=make('input');query.id='strategy-rule-'+index+'-query';query.type='text';query.placeholder='max(rate(errors[5m]) / rate(requests[5m])) * 100';query.value=rule.query;query.addEventListener('input',()=>{strategyDraft.rules[index].query=query.value});row.appendChild(query);
          const duration=make('select');duration.id='strategy-rule-'+index+'-duration';STRATEGY_DURATION_OPTIONS.forEach(optionData=>{const option=make('option','',optionData[1]);option.value=String(optionData[0]);option.selected=optionData[0]===rule.durationSeconds;duration.appendChild(option)});duration.addEventListener('change',()=>{strategyDraft.rules[index].durationSeconds=Number(duration.value)});row.appendChild(duration);
          const comparator=make('select');comparator.id='strategy-rule-'+index+'-comparator';STRATEGY_COMPARATOR_OPTIONS.forEach(optionData=>{const option=make('option','',optionData[1]);option.value=optionData[0];option.selected=optionData[0]===rule.comparator;comparator.appendChild(option)});comparator.addEventListener('change',()=>{strategyDraft.rules[index].comparator=comparator.value});row.appendChild(comparator);
          const threshold=make('input');threshold.id='strategy-rule-'+index+'-threshold';threshold.type='number';threshold.step='any';threshold.placeholder='1';threshold.value=rule.threshold;threshold.addEventListener('input',()=>{strategyDraft.rules[index].threshold=threshold.value});row.appendChild(threshold);
          const severity=make('select');severity.id='strategy-rule-'+index+'-severity';[['warning','告警'],['critical','严重']].forEach(optionData=>{const option=make('option','',optionData[1]);option.value=optionData[0];option.selected=optionData[0]===rule.severity;severity.appendChild(option)});severity.addEventListener('change',()=>{strategyDraft.rules[index].severity=severity.value});row.appendChild(severity);
          const interval=make('select');interval.id='strategy-rule-'+index+'-interval';[[0,'不重复'],[10,'每 10 分钟'],[30,'每 30 分钟'],[60,'每 1 小时'],[240,'每 4 小时']].forEach(optionData=>{const option=make('option','',optionData[1]);option.value=String(optionData[0]);option.selected=optionData[0]===Number(rule.sendIntervalMinutes||0);interval.appendChild(option)});interval.addEventListener('change',()=>{strategyDraft.rules[index].sendIntervalMinutes=Number(interval.value)});row.appendChild(interval);
          const noData=make('input');noData.id='strategy-rule-'+index+'-nodata';noData.type='checkbox';noData.checked=Boolean(rule.noDataAlert);noData.addEventListener('change',()=>{strategyDraft.rules[index].noDataAlert=noData.checked});row.appendChild(noData);
          const del=add(row,'button','icon-btn','🗑');del.type='button';del.title='删除此规则行';del.addEventListener('click',()=>{if(strategyDraft.rules.length<=1){setFeedback('strategyEditorFeedback','至少保留一条规则行',false);return}strategyDraft.rules.splice(index,1);renderStrategyRuleRows()});row.appendChild(del);root.appendChild(row)})}
      async function saveStrategy(){const nameInput=$('strategyName');const descInput=$('strategyDescription');strategyDraft.name=String(nameInput?nameInput.value:'');strategyDraft.description=String(descInput?descInput.value:'');const enabledBox=$('strategyEnabled');if(enabledBox)strategyDraft.enabled=enabledBox.checked;const channel=$('strategyChannel');if(channel)strategyDraft.notificationChannel=channel.value;const rows=[...document.querySelectorAll('#strategyRuleRows .strategy-rule-row')];strategyDraft.rules=rows.map((row,index)=>readStrategyRuleRow(index));const invalid=validateStrategyDraft();if(invalid){setFeedback('strategyEditorFeedback',invalid.message,false);return}const payload={name:strategyDraft.name.trim(),description:strategyDraft.description.trim(),enabled:strategyDraft.enabled,notificationChannel:strategyDraft.notificationChannel,rules:strategyDraft.rules.map(rule=>({query:rule.query,durationSeconds:rule.durationSeconds,comparator:rule.comparator,threshold:Number(rule.threshold),severity:rule.severity,sendIntervalMinutes:rule.sendIntervalMinutes,noDataAlert:rule.noDataAlert}))};const saveBtn=$('strategyDrawer').querySelector('.btn.primary');if(saveBtn)saveBtn.disabled=true;try{if(strategyEditingId){await request('/api/ops/observability/strategies/'+encodeURIComponent(strategyEditingId),{method:'PUT',body:JSON.stringify(payload)});toast('策略已保存，下一轮评估生效')}else{await request('/api/ops/observability/strategies'+(adminTenantQuery()?'?'+adminTenantQuery().slice(1):''),{method:'POST',body:JSON.stringify(payload)});toast('策略已创建，下一轮评估开始')}}catch(error){setFeedback('strategyEditorFeedback',friendlyError(error.message),false);if(saveBtn)saveBtn.disabled=false;return}closeStrategyEditor();loadStrategyList()}
      // ---- 告警屏蔽页（维护窗口管理）：剩余时间列 + 创建/删除 ----
      function silenceRemainingText(endsAt){const end=Date.parse(endsAt);if(!Number.isFinite(end))return '—';const diff=end-Date.now();if(diff<=0)return '已结束';const mins=Math.round(diff/60000);if(mins<60)return mins+' 分钟';if(mins<1440)return (mins/60).toFixed(1)+' 小时';return (mins/1440).toFixed(1)+' 天'}
      function renderSilencePage(){const root=$('silenceList');if(!root)return;root.replaceChildren();const windows=state.overview&&Array.isArray(state.overview.maintenanceWindows)?state.overview.maintenanceWindows:[];const createBtn=$('silenceCreateBtn');if(createBtn&&!createBtn.dataset.bound){createBtn.dataset.bound='1';createBtn.addEventListener('click',()=>silenceCreateAction())}
        const head=make('div','rules-head');['屏蔽范围','原因','时间窗','剩余时间','创建人','操作'].forEach(value=>add(head,'div','',value));root.appendChild(head);if(!windows.length){root.appendChild(make('div','empty','当前没有屏蔽窗口；计划内维护前先在这里创建，避免变更期间告警打扰。'));return}
        windows.slice().sort((a,b)=>String(b.startsAt).localeCompare(String(a.startsAt))).forEach(item=>{const row=make('article','rule-row');add(row,'div','rule-title',item.scope==='global'?'全部规则':('单条规则 · '+(item.alertKey||'—')));
          add(row,'div','rule-meta',item.reason||'—');
          const range=make('div','rule-condition');add(range,'div','',when(item.startsAt)+' → '+when(item.endsAt));row.appendChild(range);
          const remain=make('div','rule-eval');add(remain,'span','category-chip '+(item.active?'type-metric':'type-log'),item.active?('生效中 · 剩余 '+silenceRemainingText(item.endsAt)):'未生效/已结束');row.appendChild(remain);
          add(row,'div','rule-audit',item.createdBy||'—');
          const action=make('div','row-action');const del=add(action,'button','icon-btn','🗑');del.type='button';del.title='删除屏蔽窗口';del.addEventListener('click',async()=>{if(!window.confirm('确认删除该屏蔽窗口？删除后通知立即恢复投递。'))return;del.disabled=true;try{await request('/api/ops/observability/maintenance-windows/'+encodeURIComponent(String(item.id)),{method:'DELETE'});toast('屏蔽窗口已删除');await loadAll(true);renderSilencePage()}catch(error){toast('删除失败：'+friendlyError(error.message),false);del.disabled=false}});row.appendChild(action);root.appendChild(row)})}
      async function silenceCreateAction(){const keyInput=$('silenceAlertKey');const minutes=$('silenceMinutes');const reason=$('silenceReason');const value=reason?reason.value.trim():'';if(value.length<3){setFeedback('silenceFeedback','屏蔽原因至少 3 个字符，便于审计追踪',false);return}const btn=$('silenceCreateBtn');if(btn)btn.disabled=true;try{await request('/api/ops/observability/maintenance-windows',{method:'POST',body:JSON.stringify({alertKey:keyInput?keyInput.value.trim():'',minutes:Number(minutes?minutes.value:60),reason:value})});toast('屏蔽窗口已创建');if(keyInput)keyInput.value='';if(reason)reason.value='';await loadAll(true);renderSilencePage()}catch(error){setFeedback('silenceFeedback',friendlyError(error.message),false)}finally{if(btn)btn.disabled=false}}

      // ---- 账号行为视角（#platform/accounts，只读审计） ----
      let accountActivityData=null;
      function renderAccountActivity(){const btn=$('accountSearchBtn');if(btn&&!btn.dataset.bound){btn.dataset.bound='1';btn.addEventListener('click',()=>loadAccountActivity())}const input=$('accountIdentifier');if(input&&!input.dataset.bound){input.dataset.bound='1';input.addEventListener('keydown',event=>{if(event.key==='Enter')loadAccountActivity()})}const root=$('accountActivityResult');if(!root)return;if(!accountActivityData){root.replaceChildren();return}const r=accountActivityData;root.replaceChildren();const RUN_OUTCOME_LABELS={completed:'完成',completed_partial:'部分完成',error:'失败',cancelled:'已取消'};
        const humanDuration=ms=>{const v=Number(ms)||0;if(v>=3600000)return (v/3600000).toFixed(1)+' 小时';if(v>=90000)return (v/60000).toFixed(1)+' 分钟';if(v>=1000)return (v/1000).toFixed(1)+' s';return v+' ms'};
        const humanTokens=n=>{const v=Number(n)||0;if(v>=100000000)return (v/100000000).toFixed(2)+' 亿';if(v>=10000)return (v/10000).toFixed(1)+' 万';return String(v)};
        
        const ids=make('div','hint');ids.style.margin='4px 0 10px';ids.textContent='聚合账号：'+(r.resolvedIds||[]).join('、')+(r.registeredAt?(' · 注册于 '+when(r.registeredAt)+(r.registeredSource?('（'+r.registeredSource+'）'):'')):'');root.appendChild(ids);
        const summary=make('div','rule-summary');[['Agent Run',r.runs.total,'',r.runs.errors+' 次失败 · '+humanTokens(r.runs.totalTokens)+' token'],['最近活动',r.runs.lastStartedAt?when(r.runs.lastStartedAt):'—','',r.turns.lastRecordedAt?('会话 '+when(r.turns.lastRecordedAt)):'无会话记录'],['会话轮次',r.turns.total,'',r.turns.errors+' 轮异常'],['活跃天数',r.usage.activeDays,'',r.usage.lastDay?('最近 '+r.usage.lastDay):'—']].forEach(item=>{const card=make('div','panel summary-card');add(card,'div','summary-label',item[0]);add(card,'div','summary-value '+item[2],String(item[1]));add(card,'div','summary-note',item[3]);summary.appendChild(card)});root.appendChild(summary);
        const jumpBar=make('div','form-actions');jumpBar.style.margin='8px 0 2px';const metricBtn=add(jumpBar,'button','btn','按此账号查指标');metricBtn.type='button';metricBtn.title='跳转观测查询并预填 sso_user_id 过滤（指标序列需应用上报账号标签后才出数）';metricBtn.addEventListener('click',()=>{const sso=(r.resolvedIds&&r.resolvedIds.length?String(r.resolvedIds[0]):'')||String(($('accountIdentifier')||{}).value||'').trim();const input=$('signalSsoUser');if(input)input.value=sso;setView('signals')});root.appendChild(jumpBar);
        if(r.runs.recent.length){const panel=make('section','panel table-panel');const head=make('div','table-title');add(head,'h2','','最近 Agent Run');add(head,'span','summary-note','「查链路」携带 run_id 直达链路追踪');panel.appendChild(head);const scroll=make('div','scroll');const table=make('table');const thead=make('thead');const hr=make('tr');['开始','结果','模型','token','耗时','客户端','操作'].forEach(h=>add(hr,'th','',h));thead.appendChild(hr);table.appendChild(thead);const tbody=make('tbody');
          r.runs.recent.forEach(row=>{const tr=make('tr');add(tr,'td','',when(row.started_at));add(tr,'td','',RUN_OUTCOME_LABELS[String(row.outcome||'')]||String(row.outcome||'—'));add(tr,'td','',String(row.model||'—'));add(tr,'td','',humanTokens((Number(row.prompt_tokens)||0)+(Number(row.completion_tokens)||0)));add(tr,'td','',humanDuration(row.elapsed_ms));add(tr,'td','',String(row.client_type||'—'));const op=make('td');const q=add(op,'button','btn','查链路');q.type='button';q.title='携带 run_id 跳转链路追踪';q.addEventListener('click',()=>{state.traceQuery=String(row.run_id||'');state.traceOutcome='all';setView('traces')});op.appendChild(q);tr.appendChild(op);tbody.appendChild(tr)});
          table.appendChild(tbody);scroll.appendChild(table);panel.appendChild(scroll);root.appendChild(panel)}
        if(r.turns.recent.length)root.appendChild(buildTable('最近会话轮次',['时间','渠道','结果','工具数','版本'],r.turns.recent.map(row=>[when(row.recorded_at),String(row.channel||'—'),String(row.outcome||'—'),String(row.tools_count??0),String(row.app_version||'—')]),'暂无会话记录'));
        if(r.loginAudit.length)root.appendChild(buildTable('登录记录',['时间','动作'],r.loginAudit.map(row=>[when(row.occurred_at),row.action==='sso_login'?'登录':'退出']),'暂无登录记录'));
        if(r.configAudit.length)root.appendChild(buildTable('配置变更',['时间','动作','摘要'],r.configAudit.map(row=>[when(row.occurred_at),String(row.action||''),String(row.summary||'')]),'暂无配置变更'));
        if(r.incidentActivity.length)root.appendChild(buildTable('事故处置',['时间','事故','动作','摘要'],r.incidentActivity.map(row=>[when(row.occurred_at),String(row.alert_key||''),String(row.action||''),String(row.summary||'')]),'暂无处置记录'));
        if(r.opsEvents.length)root.appendChild(buildTable('事件流水',['时间','组件','事件','结果','摘要'],r.opsEvents.map(row=>[when(row.occurred_at),String(row.component||''),String(row.event_code||''),String(row.outcome||''),String(row.safe_summary||'')]),'暂无事件'));
        {const detailBar=make('div','form-actions');detailBar.style.margin='10px 0 4px';const codeSel=make('select');codeSel.id='accountEventCode';codeSel.style.maxWidth='220px';codeSel.appendChild(new Option('全部事件类型',''));detailBar.appendChild(codeSel);
          const loadBtn=add(detailBar,'button','btn','加载事件明细（≤200 条）');loadBtn.type='button';
          const detailRoot=make('div');detailRoot.id='accountEventDetail';detailBar.appendChild(detailRoot);
          root.appendChild(detailBar);
          loadBtn.addEventListener('click',async()=>{loadBtn.disabled=true;detailRoot.replaceChildren();detailRoot.appendChild(make('div','signals-empty','正在加载事件明细…'));try{const identifier=String(($('accountIdentifier')||{}).value||'').trim();const hours=Number(($('accountHours')||{}).value||168);const code=String((($('accountEventCode')||{}).value)||'');const query='/api/ops/observability/account-activity/events?identifier='+encodeURIComponent(identifier)+'&hours='+hours+'&limit=200'+(code?'&eventCode='+encodeURIComponent(code):'');const data=await request(query);const logData=data&&data.log?data.log:null;detailRoot.replaceChildren();if(!logData){detailRoot.appendChild(make('div','empty','明细加载失败'));return}
            const codeSel2=$('accountEventCode');if(codeSel2&&codeSel2.options.length<=1){(logData.codes||[]).forEach(item=>codeSel2.appendChild(new Option(item.eventCode+' ('+item.total+')',item.eventCode)))}
            if(!(logData.events||[]).length){detailRoot.appendChild(make('div','empty','所选条件下没有事件记录'));return}
            detailRoot.appendChild(buildTable('事件明细（最近 '+(logData.events.length)+' 条）',['时间','组件','事件','结果','摘要'],logData.events.map(row=>[when(row.occurred_at),String(row.component||''),String(row.event_code||''),String(row.outcome||''),String(row.safe_summary||'')]),'暂无事件'))}catch(error){detailRoot.replaceChildren();detailRoot.appendChild(make('div','empty','明细加载失败：'+friendlyError(error.message)))}finally{loadBtn.disabled=false}})}
        if(!r.runs.total&&!r.turns.total&&!r.configAudit.length&&!r.incidentActivity.length&&!r.opsEvents.length){root.appendChild(make('div','empty','时间窗内没有该账号的任何行为记录'))}}
      async function loadAccountActivity(){const input=$('accountIdentifier');const identifier=input?input.value.trim():'';if(!identifier){toast('请输入账号 ID 或用户名',false);return}const hours=$('accountHours')?Number($('accountHours').value):168;const btn=$('accountSearchBtn');if(btn)btn.disabled=true;const root=$('accountActivityResult');if(root){root.replaceChildren();root.appendChild(make('div','signals-empty','正在检索账号行为…'))}try{const data=await request('/api/ops/observability/account-activity?identifier='+encodeURIComponent(identifier)+'&hours='+hours);accountActivityData=data&&data.ok?data.report:null}catch(error){accountActivityData=null;toast('检索失败：'+friendlyError(error.message),false)}finally{if(btn)btn.disabled=false}renderAccountActivity()}
`;