/**
 * 观测查询（指标/日志/自定义面板）与边缘设备视图的客户端逻辑。
 * 依赖外层脚本提供的共享工具：state、base、$、make、add、apiHeaders、toast、when。
 */

export const OPS_OBSERVABILITY_SCRIPT_SIGNALS =
  `
      // ============ 零依赖折线图渲染器（观测查询 / 设备 / 自定义面板共用） ============
      const SIGNALS_CHART_COLORS = ['#3b82f6','#10b981','#f59e0b','#ef4444','#8b5cf6','#06b6d4','#ec4899','#84cc16'];
      function signalsFormatValue(value){const n=Number(value)||0;const abs=Math.abs(n);if(abs>=1e9)return (n/1e9).toFixed(1)+'G';if(abs>=1e6)return (n/1e6).toFixed(1)+'M';if(abs>=1e3)return (n/1e3).toFixed(1)+'k';if(abs>=10)return n.toFixed(0);if(abs>=1)return n.toFixed(2);if(abs===0)return '0';return n.toFixed(3)}
      function signalsFormatTs(ts,windowMinutes){const date=new Date(Number(ts));if(!Number.isFinite(date.getTime()))return '';const pad=v=>String(v).padStart(2,'0');if(windowMinutes<=1440)return pad(date.getHours())+':'+pad(date.getMinutes());return (date.getMonth()+1)+'/'+date.getDate()+' '+pad(date.getHours())+':00'}
      // series: [{name, points:[{ts,value}]}]; 渲染 SVG 折线 + 网格 + 图例。
      function renderSignalsChart(container,series,windowMinutes){container.replaceChildren();const usable=series.filter(item=>item.points&&item.points.length);if(!usable.length){container.appendChild(make('div','signals-empty','所选范围内没有数据点'));return}
        const width=Math.max(320,container.clientWidth||640);const height=200;const padL=52;const padR=12;const padT=10;const padB=24;
        let minV=Infinity,maxV=-Infinity,minT=Infinity,maxT=-Infinity;usable.forEach(item=>item.points.forEach(p=>{minV=Math.min(minV,p.value);maxV=Math.max(maxV,p.value);minT=Math.min(minT,p.ts);maxT=Math.max(maxT,p.ts)}));
        if(minT===maxT){maxT=minT+60000}if(minV===maxV){maxV=minV+1}const padV=(maxV-minV)*0.08;minV-=padV;maxV+=padV;
        const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 '+width+' '+height);svg.setAttribute('role','img');svg.setAttribute('aria-label','时序折线图');
        const x=ts=>padL+((ts-minT)/(maxT-minT))*(width-padL-padR);const y=v=>padT+(1-(v-minV)/(maxV-minV))*(height-padT-padB);
        for(let i=0;i<=3;i++){const value=minV+(maxV-minV)*(i/3);const gy=y(value);const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',padL);line.setAttribute('x2',width-padR);line.setAttribute('y1',gy);line.setAttribute('y2',gy);line.setAttribute('stroke','rgba(148,163,184,.18)');line.setAttribute('stroke-width','1');svg.appendChild(line);
          const label=document.createElementNS('http://www.w3.org/2000/svg','text');label.setAttribute('x',padL-6);label.setAttribute('y',gy+4);label.setAttribute('text-anchor','end');label.setAttribute('font-size','10');label.setAttribute('fill','var(--muted)');label.textContent=signalsFormatValue(value);svg.appendChild(label)}
        const tickCount=Math.min(5,usable[0].points.length);for(let i=0;i<tickCount;i++){const ts=minT+(maxT-minT)*(tickCount===1?0:i/(tickCount-1));const tx=x(ts);const tlabel=document.createElementNS('http://www.w3.org/2000/svg','text');tlabel.setAttribute('x',Math.min(Math.max(tx,padL),width-padR));tlabel.setAttribute('y',height-6);tlabel.setAttribute('text-anchor','middle');tlabel.setAttribute('font-size','10');tlabel.setAttribute('fill','var(--muted)');tlabel.textContent=signalsFormatTs(ts,windowMinutes||240);svg.appendChild(tlabel)}
        usable.forEach((item,index)=>{const color=SIGNALS_CHART_COLORS[index%SIGNALS_CHART_COLORS.length];const d=item.points.map((p,i2)=>(i2?'L':'M')+x(p.ts).toFixed(1)+' '+y(p.value).toFixed(1)).join(' ');const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',d);path.setAttribute('fill','none');path.setAttribute('stroke',color);path.setAttribute('stroke-width','1.6');path.setAttribute('stroke-linejoin','round');svg.appendChild(path)});
        container.appendChild(svg);
        const legend=make('div','signals-legend');usable.forEach((item,index)=>{const entry=make('span');const swatch=make('span','swatch');swatch.style.background=SIGNALS_CHART_COLORS[index%SIGNALS_CHART_COLORS.length];entry.appendChild(swatch);entry.appendChild(document.createTextNode(item.name+(item.points.length?(' ('+item.points.length+')'):'')));legend.appendChild(entry)});container.appendChild(legend)}

      // ============ 指标查询 ============
      state.signalMetricNames=state.signalMetricNames||[];
      async function loadSignalMetricNames(){try{const response=await fetch(base+'/api/ops/observability/metrics/series?limit=500',{headers:apiHeaders(false),credentials:'same-origin'});const data=await response.json().catch(()=>null);if(response.ok&&data&&data.ok){state.signalMetricNames=[...new Set((data.series||[]).map(item=>item.metric))].sort();const list=$('signalMetricList');if(list){list.replaceChildren();state.signalMetricNames.forEach(name=>{const option=make('option');option.value=name;list.appendChild(option)})}const input=$('signalMetricInput');if(input&&!input.value&&state.signalMetricNames.length)input.value=state.signalMetricNames[0]}}catch{}}
      async function runSignalsMetricQuery(){const metric=String(($('signalMetricInput')||{}).value||'').trim();const minutes=Number(($('signalMinutes')||{}).value||240);const target=$('signalsMetricChart');if(!target)return;if(!metric){toast('请先输入指标名',false);return}target.replaceChildren();const loading=make('div','signals-empty','正在查询 '+metric+' …');target.appendChild(loading);
        try{const response=await fetch(base+'/api/ops/observability/metrics/query?metric='+encodeURIComponent(metric)+'&minutes='+encodeURIComponent(String(minutes))+'&points=240',{headers:apiHeaders(false),credentials:'same-origin'});const data=await response.json().catch(()=>null);if(!response.ok||!data||!data.ok){loading.textContent=data&&data.error==='central_store_disabled'?'指标存储未启用（未配置中心库）':'查询失败，请稍后重试';return}
          const series=(data.series||[]).map(item=>({name:item.metric+' '+JSON.stringify(item.labels||{}),points:item.points||[]}));renderSignalsChart(target,series,minutes)}catch{loading.textContent='查询失败，请检查网络后重试'}}
      async function runSignalsLogQuery(){const service=String(($('signalLogService')||{}).value||'').trim();const severityMin=Number(($('signalLogSeverity')||{}).value||9);const minutes=Number(($('signalLogMinutes')||{}).value||240);const target=$('signalsLogTable');if(!target)return;target.replaceChildren();target.appendChild(make('div','signals-empty','正在查询日志…'));
        try{const params='/api/ops/observability/logs?minutes='+encodeURIComponent(String(minutes))+'&severityMin='+encodeURIComponent(String(severityMin))+(service?'&service='+encodeURIComponent(service):'')+'&limit=200';const response=await fetch(base+params,{headers:apiHeaders(false),credentials:'same-origin'});const data=await response.json().catch(()=>null);target.replaceChildren();if(!response.ok||!data||!data.ok){target.appendChild(make('div','signals-empty','日志查询失败'));return}
          const logs=data.logs||[];if(!logs.length){target.appendChild(make('div','signals-empty','所选范围内没有日志记录'));return}
          const table=make('table','signals-log-table');const thead=make('thead');const headRow=make('tr');['时间','服务','级别','内容'].forEach(h=>add(headRow,'th','',h));thead.appendChild(headRow);table.appendChild(thead);const tbody=make('tbody');logs.forEach(row=>{const tr=make('tr');add(tr,'td','',when(row.timestampMs));add(tr,'td','',row.service||'—');const sev=add(tr,'td');add(sev,'span','signals-log-sev '+String(row.severityText||'INFO'),String(row.severityText||'INFO'));add(tr,'td','',row.body||'');tbody.appendChild(tr)});table.appendChild(tbody);target.appendChild(table)}catch{target.replaceChildren();target.appendChild(make('div','signals-empty','日志查询失败，请检查网络'))}}

      // ============ 自定义面板 ============
      state.signalPanels=state.signalPanels||null;
      async function loadSignalPanels(){const target=$('signalsPanelGrid');if(!target)return;try{const response=await fetch(base+'/api/ops/observability/panels',{headers:apiHeaders(false),credentials:'same-origin'});const data=await response.json().catch(()=>null);target.replaceChildren();if(!response.ok||!data||!data.ok){target.appendChild(make('div','signals-empty','面板读取失败'));return}
          const panels=data.panels||[];if(!panels.length){target.appendChild(make('div','signals-empty','还没有保存的面板；在上方查询指标后点「保存为面板」'));return}
          panels.forEach(panel=>{const card=make('div','signals-panel-card');const head=make('h4');add(head,'span','',panel.title+' · '+panel.spec.metric+' · '+(panel.spec.windowMinutes>=1440?(panel.spec.windowMinutes/1440)+'天':panel.spec.windowMinutes+'分钟'));const del=add(head,'button','btn','删除');del.type='button';del.addEventListener('click',async()=>{try{await fetch(base+'/api/ops/observability/panels/'+encodeURIComponent(panel.id),{method:'DELETE',headers:apiHeaders(true),credentials:'same-origin'});toast('面板已删除');loadSignalPanels()}catch{toast('删除失败',false)}});card.appendChild(head);const chartWrap=make('div','signals-chart-wrap');card.appendChild(chartWrap);target.appendChild(card);
            fetch(base+'/api/ops/observability/metrics/query?metric='+encodeURIComponent(panel.spec.metric)+'&minutes='+encodeURIComponent(String(panel.spec.windowMinutes))+'&points=120',{headers:apiHeaders(false),credentials:'same-origin'}).then(r=>r.json()).then(data2=>{const series=(data2&&data2.ok?data2.series:[]).map(item=>({name:item.metric,points:item.points||[]}));renderSignalsChart(chartWrap,series,panel.spec.windowMinutes)}).catch(()=>{chartWrap.appendChild(make('div','signals-empty','加载失败'))})})}catch{target.replaceChildren();target.appendChild(make('div','signals-empty','面板读取失败'))}}
      async function saveSignalsPanel(){const metric=String(($('signalMetricInput')||{}).value||'').trim();const minutes=Number(($('signalMinutes')||{}).value||240);if(!metric){toast('先查询一个指标再保存',false);return}const title=window.prompt('面板标题',metric);if(!title)return;
        try{const response=await fetch(base+'/api/ops/observability/panels',{method:'POST',headers:apiHeaders(true),credentials:'same-origin',body:JSON.stringify({title:title.slice(0,120),spec:{metric:metric,windowMinutes:minutes}})});const data=await response.json().catch(()=>null);if(response.ok&&data&&data.ok){toast('面板已保存');loadSignalPanels()}else toast(data&&data.error==='invalid_panel_spec'?'指标名不合法':'保存失败',false)}catch{toast('保存失败',false)}}

      // ============ 边缘设备 ============
      state.deviceRevealToken=state.deviceRevealToken||'';
      async function loadDevicesView(){const target=$('devicesContent');if(!target)return;target.replaceChildren();const loading=make('div','shell-status');loading.setAttribute('role','status');add(loading,'span','shell-spinner','');add(loading,'strong','','正在读取设备清单');add(loading,'small','','查询注册设备、心跳与在线状态…');target.appendChild(loading);
        try{const response=await fetch(base+'/api/ops/observability/devices',{headers:apiHeaders(false),credentials:'same-origin'});const data=await response.json().catch(()=>null);target.replaceChildren();if(!response.ok||!data||!data.ok){const failed=make('div','signals-empty','设备清单读取失败（需要运营权限与中心库）');target.appendChild(failed);return}
          const devices=data.devices||[];state.deviceRevealToken='';
          const table=make('table','devices-table');const thead=make('thead');const headRow=make('tr');[['设备','device'],['归属','tenant'],['型号 / 固件','model'],['状态','status'],['最近心跳','seen'],['操作','ops']].forEach(h=>add(headRow,'th','',h[0]));thead.appendChild(headRow);table.appendChild(thead);const tbody=make('tbody');
          if(!devices.length){const emptyRow=make('tr');const emptyCell=add(emptyRow,'td','',"还没有注册设备：在上方注册并部署 edge-agent 后，心跳会自动出现在这里");emptyCell.colSpan=6;tbody.appendChild(emptyRow)}
          devices.forEach(device=>{const tr=make('tr');const idCell=add(tr,'td');add(idCell,'strong','',device.deviceId);if(device.displayName&&device.displayName!==device.deviceId)add(idCell,'div','',device.displayName);
            add(tr,'td','',device.tenantId);const modelCell=add(tr,'td','');add(modelCell,'div','',device.model||'—');if(device.firmware)add(modelCell,'small','','固件 '+device.firmware);
            const statusCell=add(tr,'td');if(device.status==='disabled')add(statusCell,'span','device-pill offline','已停用');else add(statusCell,'span','device-pill '+(device.online?'online':'offline'),device.online?'在线':'离线');
            add(tr,'td','',device.lastSeenAt?when(device.lastSeenAt):'从未上报');
            const opsCell=add(tr,'td');const detailBtn=add(opsCell,'button','btn','指标');detailBtn.type='button';detailBtn.addEventListener('click',()=>toggleDeviceDetail(device.deviceId,detailBtn));const rotateBtn=add(opsCell,'button','btn','轮换 token');rotateBtn.type='button';rotateBtn.addEventListener('click',()=>rotateDeviceTokenFlow(device.deviceId));const toggleBtn=add(opsCell,'button','btn',device.status==='disabled'?'启用':'停用');toggleBtn.type='button';toggleBtn.addEventListener('click',async()=>{try{const next=device.status==='disabled'?'active':'disabled';const r=await fetch(base+'/api/ops/observability/devices/'+encodeURIComponent(device.deviceId)+'/status',{method:'POST',headers:apiHeaders(true),credentials:'same-origin',body:JSON.stringify({status:next})});if(r.ok){toast(next==='active'?'设备已启用':'设备已停用');loadDevicesView()}else toast('操作失败',false)}catch{toast('操作失败',false)}});
            tbody.appendChild(tr)});table.appendChild(tbody);target.appendChild(table)}catch{target.replaceChildren();target.appendChild(make('div','signals-empty','设备清单读取失败，请检查网络'))}}
      function toggleDeviceDetail(deviceId,button){const existing=$('device-detail-'+deviceId);if(existing){existing.remove();button.textContent='指标';return}button.textContent='收起';const table=button.closest('table');if(!table)return;const row=button.closest('tr');const holder=make('tr');const cell=add(holder,'td');cell.colSpan=6;const detail=make('div','device-detail');detail.id='device-detail-'+deviceId;add(detail,'strong','','设备指标（最近 24 小时）');const chartWrap=make('div','signals-chart-wrap');detail.appendChild(chartWrap);cell.appendChild(detail);if(row&&row.parentNode)row.parentNode.insertBefore(holder,row.nextSibling);
        fetch(base+'/api/ops/observability/devices/'+encodeURIComponent(deviceId)+'/samples?minutes=1440&points=240',{headers:apiHeaders(false),credentials:'same-origin'}).then(r=>r.json()).then(data=>{if(!data||!data.ok){chartWrap.appendChild(make('div','signals-empty','样本读取失败'));return}
          const samples=data.samples||[];const keys={};samples.forEach(s=>Object.keys(s.metrics||{}).forEach(k=>{keys[k]=true}));const preferred=['cpu_percent','mem_percent','temp_c','disk_percent','load1','bpu0_util'].filter(k=>keys[k]);const chosen=preferred.length?preferred.slice(0,4):Object.keys(keys).slice(0,4);
          const series=chosen.map(k=>({name:k,points:samples.map(s=>({ts:s.ts,value:Number(s.metrics[k])||0}))}));renderSignalsChart(chartWrap,series,1440)}).catch(()=>{chartWrap.appendChild(make('div','signals-empty','样本读取失败'))})}
      async function registerDeviceFlow(){const deviceId=String(($('newDeviceId')||{}).value||'').trim();const displayName=String(($('newDeviceName')||{}).value||'').trim();const model=String(($('newDeviceModel')||{}).value||'').trim();if(!deviceId){toast('请填写设备 ID（小写字母/数字/点/连字符）',false);return}
        try{const response=await fetch(base+'/api/ops/observability/devices',{method:'POST',headers:apiHeaders(true),credentials:'same-origin',body:JSON.stringify({deviceId:deviceId,displayName:displayName,model:model})});const data=await response.json().catch(()=>null);if(response.ok&&data&&data.ok){state.deviceRevealToken=data.token;toast('设备已注册');loadDevicesView();const hint=$('newDeviceTokenHint');if(hint){hint.classList.remove('hidden');hint.textContent='设备 '+data.device.deviceId+' 的 token（只显示一次，立即保存）：'+data.token+'  |  部署：RDK_OBS_REPORT_URL 指向本服务，RDK_DEVICE_TOKEN_FILE 存入该 token，运行 tools/edge-agent.mjs'}}else toast(data&&data.error==='invalid_device_id'?'设备 ID 不合法（小写字母/数字开头，2-64 位）':'注册失败',false)}catch{toast('注册失败，请检查网络',false)}}
      async function rotateDeviceTokenFlow(deviceId){if(!window.confirm('轮换设备 '+deviceId+' 的 token？旧 token 立即失效。'))return;
        try{const response=await fetch(base+'/api/ops/observability/devices/'+encodeURIComponent(deviceId)+'/token',{method:'POST',headers:apiHeaders(true),credentials:'same-origin'});const data=await response.json().catch(()=>null);if(response.ok&&data&&data.ok){const hint=$('newDeviceTokenHint');if(hint){hint.classList.remove('hidden');hint.textContent='设备 '+deviceId+' 的新 token（只显示一次，立即保存）：'+data.token}toast('token 已轮换')}else toast('轮换失败',false)}catch{toast('轮换失败',false)}}
      // ============ 质量与反馈趋势 ============
      async function loadQualitySummary(){const target=$('signalsQualityContent');if(!target)return;try{const response=await fetch(base+'/api/ops/observability/quality/summary?days=30',{headers:apiHeaders(false),credentials:'same-origin'});const data=await response.json().catch(()=>null);target.replaceChildren();if(!response.ok||!data||!data.ok){target.appendChild(make('div','signals-empty','质量趋势读取失败（需要中心库）'));return}
          const trend=data.trend||{};const totals=trend.totals||{};
          const kpis=make('div','signals-legend');[['反馈条数',String(totals.feedbackCount??0)],['好评率',totals.positiveRate==null?'—':Math.round(totals.positiveRate*100)+'%'],['评分样本',String(totals.scoreCount??0)],['平均评分',totals.avgScore==null?'—':String(totals.avgScore)]].forEach(item=>{const node=make('span');add(node,'strong','',item[1]);add(node,'span','', ' '+item[0]);node.style.gap='4px';kpis.appendChild(node)});target.appendChild(kpis);
          const active=(trend.series||[]).filter(p=>p.feedbackCount>0||p.scoreCount>0);if(!active.length){target.appendChild(make('div','signals-empty','近 30 天还没有评分或反馈数据；在链路追踪里对 run 打分/点 👍👎 后这里会出现趋势'));return}
          const table=make('table','signals-log-table');const thead=make('thead');const headRow=make('tr');['日期','反馈','好评率','评分样本','平均评分'].forEach(h=>add(headRow,'th','',h));thead.appendChild(headRow);table.appendChild(thead);const tbody=make('tbody');active.slice(-14).forEach(p=>{const tr=make('tr');add(tr,'td','',p.day);add(tr,'td','',String(p.feedbackCount));add(tr,'td','',p.positiveRate==null?'—':Math.round(p.positiveRate*100)+'%');add(tr,'td','',String(p.scoreCount));add(tr,'td','',p.avgScore==null?'—':String(p.avgScore));tbody.appendChild(tr)});table.appendChild(tbody);target.appendChild(table)}catch{target.replaceChildren();target.appendChild(make('div','signals-empty','质量趋势读取失败，请检查网络'))}}

      // ============ 生态接入凭据（人/服务/租户三级） ============
      const ingestSubjectNames={user:'用户',service:'服务',tenant:'租户'};
      function showIngestTokenSecret(token,prefix){const hint=$('ingestTokenSecretHint');if(hint){hint.classList.remove('hidden');hint.textContent=prefix+token+'  |  上报示例：OTEL_EXPORTER_OTLP_HEADERS=\\'Authorization=Bearer '+token.slice(0,8)+'…\\'（完整值见上方，只显示一次）'}}
      async function loadIngestTokens(){const target=$('ingestTokensContent');if(!target)return;try{const response=await fetch(base+'/api/ops/observability/ingest-tokens',{headers:apiHeaders(false),credentials:'same-origin'});const data=await response.json().catch(()=>null);target.replaceChildren();if(!response.ok||!data||!data.ok){target.appendChild(make('div','signals-empty','凭据清单读取失败（需要中心库）'));return}
          const tokens=data.tokens||[];if(!tokens.length){target.appendChild(make('div','signals-empty','还没有签发凭据；上方选择对象类型与 ID 后点「签发」'));return}
          const table=make('table','signals-log-table');const thead=make('thead');const headRow=make('tr');['对象','类型','显示名','owner 前缀','状态','最近上报','操作'].forEach(h=>add(headRow,'th','',h));thead.appendChild(headRow);table.appendChild(thead);const tbody=make('tbody');
          tokens.forEach(row=>{const tr=make('tr');add(tr,'td','',row.subjectId||'—');add(tr,'td','',ingestSubjectNames[row.subjectType]||row.subjectType);add(tr,'td','',row.displayName||'—');add(tr,'td','',String(row.owner||'').slice(0,22)+'…');const st=add(tr,'td');add(st,'span','signals-log-sev '+(row.status==='active'?'INFO':'ERROR'),row.status==='active'?'active':'revoked');add(tr,'td','',when(row.lastSeenAt));const op=add(tr,'td');const rotate=add(op,'button','btn','轮换');rotate.type='button';rotate.addEventListener('click',()=>ingestTokenAction(row.tokenId,'rotate'));const revoke=add(op,'button','btn','吊销');revoke.type='button';revoke.addEventListener('click',()=>ingestTokenAction(row.tokenId,'revoke'));tbody.appendChild(tr)});
          table.appendChild(tbody);target.appendChild(table)}catch{target.replaceChildren();target.appendChild(make('div','signals-empty','凭据清单读取失败，请检查网络'))}}
      async function ingestTokenAction(tokenId,action){if(action==='rotate'&&!window.confirm('轮换该凭据？旧 token 立即失效。'))return;
        try{const response=await fetch(base+'/api/ops/observability/ingest-tokens/'+encodeURIComponent(tokenId)+'/'+action,{method:'POST',headers:apiHeaders(true),credentials:'same-origin'});const data=await response.json().catch(()=>null);if(!response.ok||!data||!data.ok){toast(action==='rotate'?'轮换失败':'吊销失败',false);return}
          if(action==='rotate')showIngestTokenSecret(data.token,'轮换成功，新 token（只显示一次）：');else toast('已吊销');loadIngestTokens()}catch{toast('操作失败，请检查网络',false)}}
      async function issueIngestTokenFlow(){const subjectType=String(($('ingestTokenSubjectType')||{}).value||'');const subjectId=String(($('ingestTokenSubjectId')||{}).value||'').trim();const displayName=String(($('ingestTokenDisplayName')||{}).value||'').trim();if(!subjectId){toast('请填写对象 ID（如 sso 用户 ID / 服务名 / 租户 ID）',false);return}
        try{const response=await fetch(base+'/api/ops/observability/ingest-tokens',{method:'POST',headers:apiHeaders(true),credentials:'same-origin',body:JSON.stringify({subjectType:subjectType,subjectId:subjectId,displayName:displayName})});const data=await response.json().catch(()=>null);if(response.ok&&data&&data.ok){toast('凭据已签发');showIngestTokenSecret(data.token,'对象 '+data.record.subjectId+' 的 token（只显示一次，立即保存）：');loadIngestTokens()}else toast(data&&data.error==='invalid_subject_id'?'对象 ID 格式不合法（2-128 位字母数字与.@_:-）':'签发失败',false)}catch{toast('签发失败，请检查网络',false)}}

      // ============ 自然语言查询与指标字典 ============
      async function renderNlChart(series, minutes){const target=$('nlQueryResult');if(!target)return;const chartWrap=make('div','signals-chart-wrap');target.appendChild(chartWrap);renderSignalsChart(chartWrap,series,minutes)}
      async function executePromql(promql,minutes){const target=$('nlQueryResult');if(!target)return;const status=make('div','signals-empty','正在执行 PromQL…');target.appendChild(status);
        try{const response=await fetch(base+'/api/ops/observability/prom/query?query='+encodeURIComponent(promql)+'&minutes='+encodeURIComponent(String(minutes)),{headers:apiHeaders(false),credentials:'same-origin'});const data=await response.json().catch(()=>null);status.remove();if(!response.ok||!data||!data.ok){const note=make('div','signals-empty',data&&data.error==='prometheus_not_configured'?'未配置 RDK_PROMETHEUS_QUERY_URL，无法直接执行；语句已生成，可在 Prometheus 里查询':'Prometheus 查询失败');target.appendChild(note);return}
          renderNlChart(data.series||[],minutes)}catch{status.remove();target.appendChild(make('div','signals-empty','Prometheus 查询失败，请检查网络'))}}
      async function runNlQuery(){const input=$('nlQueryInput');const target=$('nlQueryResult');if(!input||!target)return;const question=String(input.value||'').trim();if(!question){toast('先用一句中文描述你想查什么',false);return}
        target.replaceChildren();target.appendChild(make('div','signals-empty','正在理解问题…'));
        try{const response=await fetch(base+'/api/ops/observability/nl-query',{method:'POST',headers:apiHeaders(false),credentials:'same-origin',body:JSON.stringify({question:question})});const data=await response.json().catch(()=>null);target.replaceChildren();if(!response.ok||!data||!data.ok){target.appendChild(make('div','signals-empty',data&&data.error==='nl_query_no_match'?'没能识别目标指标；换个问法，或在指标字典里直接选。':'智能查询暂时不可用'));return}
          const spec=data.spec||{};const head=make('div','signals-legend');const badge=make('span','signals-log-sev '+(data.source==='model'?'INFO':'WARN'));badge.textContent=data.source==='model'?'AI':'规则';head.appendChild(badge);
          const explain=add(head,'span','',spec.explanation||'');head.style.gap='6px';target.appendChild(head);
          if(spec.metric&&(spec.plane==='prometheus'||spec.plane==='otlp')&&data.promql){const code=add(target,'code','',data.promql);code.style.display='block';code.style.margin='6px 0';const run=add(target,'button','btn primary','执行查询');run.type='button';run.addEventListener('click',()=>executePromql(data.promql,spec.windowMinutes||240))}
          if(spec.metric&&spec.plane==='otlp'){
            const loading=make('div','signals-empty','正在查询平台内指标 '+spec.metric+' …');target.appendChild(loading);
            const params='/api/ops/observability/metrics/query?metric='+encodeURIComponent(spec.metric)+'&minutes='+encodeURIComponent(String(spec.windowMinutes||240))+'&points=240';
            fetch(base+params,{headers:apiHeaders(false),credentials:'same-origin'}).then(r=>r.json()).then(data2=>{loading.remove();const series=(data2&&data2.ok?data2.series:[]).map(item=>({name:item.metric+' '+JSON.stringify(item.labels||{}),points:item.points||[]}));if(!series.length){target.appendChild(make('div','signals-empty','所选范围内没有数据点'));return}renderNlChart(series,spec.windowMinutes||240)}).catch(()=>{loading.textContent='平台内指标查询失败'})}
          if(!spec.metric){target.appendChild(make('div','signals-empty','未能定位到具体指标；试试「指标字典」页签，或在下方直接输入指标名。'))}
        }catch{target.replaceChildren();target.appendChild(make('div','signals-empty','智能查询失败，请检查网络'))}}
      async function loadMetricCatalog(){const target=$('metricCatalogContent');if(!target)return;try{const response=await fetch(base+'/api/ops/observability/metrics/catalog',{headers:apiHeaders(false),credentials:'same-origin'});const data=await response.json().catch(()=>null);target.replaceChildren();if(!response.ok||!data||!data.ok){target.appendChild(make('div','signals-empty','指标字典读取失败'));return}
          const groups=new Map();for(const entry of (data.catalog||[])){if(!groups.has(entry.category))groups.set(entry.category,[]);groups.get(entry.category).push(entry)}
          for(const [category,entries] of groups){const details=make('details','detail-sections');const summary=add(details,'summary','detail-summary');add(summary,'strong','',category+'（'+entries.length+'）');details.appendChild(summary);
            const table=make('table','signals-log-table');const thead=make('thead');const headRow=make('tr');['指标','说明','标签'].forEach(h=>add(headRow,'th','',h));thead.appendChild(headRow);table.appendChild(thead);const tbody=make('tbody');
            entries.forEach(entry=>{const tr=make('tr');const nameTd=add(tr,'td');if(entry.metric.startsWith('otlp://')){add(nameTd,'em','',entry.zhName)}else{const btn=add(nameTd,'button','btn','');btn.type='button';btn.textContent=entry.zhName+' · '+entry.metric;btn.addEventListener('click',()=>{const input=$('signalMetricInput');if(input&&entry.metric&&!entry.metric.includes('*')){input.value=entry.metric;toast('已填入指标查询');}})}add(tr,'td','',entry.description);add(tr,'td','',entry.labels.join(', ')||'—');tbody.appendChild(tr)});
            table.appendChild(tbody);details.appendChild(table);target.appendChild(details)}}catch{target.replaceChildren();target.appendChild(make('div','signals-empty','指标字典读取失败，请检查网络'))}}

      function renderSignalsView(){loadSignalMetricNames();loadSignalPanels();runSignalsMetricQuery();runSignalsLogQuery();loadQualitySummary();loadIngestTokens();loadMetricCatalog()}
      (function bindSignalsControls(){const bind=(id,event,handler)=>{const node=$(id);if(node)node.addEventListener(event,handler)};
        bind('signalQueryBtn','click',runSignalsMetricQuery);
        bind('signalMetricInput','keydown',event=>{if(event.key==='Enter')runSignalsMetricQuery()});
        bind('signalSavePanelBtn','click',saveSignalsPanel);
        bind('signalLogQueryBtn','click',runSignalsLogQuery);
        bind('registerDeviceBtn','click',registerDeviceFlow);
        bind('nlQueryBtn','click',runNlQuery);
        bind('nlQueryInput','keydown',event=>{if(event.key==='Enter')runNlQuery()});
        bind('ingestTokenIssueBtn','click',issueIngestTokenFlow)})();
`
