/** Evidence-bound incident copilot. It can analyze and navigate, but never mutate.
 *  诚实性约定：本部署不调用模型，全部研判由确定性证据引擎产出；渲染层保留
 *  source==='model' 分支给接入了模型的部署，但来源标签必须如实展示当前引擎。 */
export const OPS_OBSERVABILITY_SCRIPT_COPILOT = `
      state.copilotAnalysis=null;
      state.copilotQuality=null;
      state.copilotQuestion='';
      state.copilotLoading=false;
      state.copilotExpanded=false;
      state.copilotError='';

      function copilotPct(value){const parsed=Number(value);return Number.isFinite(parsed)?Math.round(parsed*100)+'%':'—'}
      function copilotEvidenceMap(analysis){return new Map((analysis&&analysis.evidenceIndex||[]).map(item=>[item.ref,item]))}
      function navigateCopilotEvidence(ref,o){
        ref=String(ref||'');if(!ref)return;
        const eventPrefix='event:';if(ref.startsWith(eventPrefix)){const id=ref.slice(eventPrefix.length);const event=investigationEvents(o).find(item=>item.id===id);if(event){openOpsEventDetail(event);return}}
        if(ref.startsWith('incident:')){setView('overview');setTimeout(()=>{const node=$('incidentWorkbench');if(node)node.scrollIntoView({behavior:'smooth',block:'start'})},0);return}
        if(ref.startsWith('check:')){goToOverviewTarget('rules',{category:'all',status:'all'});return}
        if(ref.startsWith('slo:')){setView('service-levels');return}
        if(ref.startsWith('trace:')){setView('agent-traces');return}
      }
      function goToOverviewTarget(target,options){
        if(target==='rules'&&options){state.category=options.category||'all';state.statusFilter=options.status||'all';document.querySelectorAll('[data-category]').forEach(item=>item.classList.toggle('active',item.dataset.category===state.category));document.querySelectorAll('[data-status]').forEach(item=>item.classList.toggle('active',item.dataset.status===state.statusFilter));setView('rules');if(typeof renderRules==='function')renderRules();window.scrollTo({top:0,behavior:'smooth'});return}
        if(target==='investigate'){setView('investigate');return}
        setView(target||'overview');window.scrollTo({top:0,behavior:'smooth'});
      }
      function renderCopilotRefs(parent,refs,analysis,o){
        const index=copilotEvidenceMap(analysis);const box=make('div','copilot-refs');
        (refs||[]).forEach(value=>{const ref=String(value||'');if(!ref)return;const meta=index.get(ref);const node=add(box,'button','copilot-ref',meta?meta.label:ref);node.type='button';node.title='打开证据：'+ref;node.setAttribute('aria-label','打开证据 '+(meta?meta.label:ref));node.addEventListener('click',()=>navigateCopilotEvidence(ref,o))});
        if(box.childElementCount)parent.appendChild(box);
      }
      function renderCopilotAnalysis(root,analysis,o){
        const result=make('div','copilot-result');result.setAttribute('aria-live','polite');const head=make('div','copilot-result-head');const copy=make('div');add(copy,'div','copilot-kicker',analysis.source==='model'?'模型研判 · 证据约束':'证据引擎 · 确定性');add(copy,'strong','',analysis.headline||'研判已生成');add(copy,'p','',analysis.executiveSummary||'暂无执行摘要。');head.appendChild(copy);const confidence=make('div','copilot-confidence');if(analysis.source==='model'){add(confidence,'span','','模型置信度');add(confidence,'strong','',Math.round(Number(analysis.confidence||0)*100)+'%')}else{const quality=state.copilotQuality;add(confidence,'span','','证据质量');add(confidence,'strong','',quality&&Number.isFinite(quality.score)?quality.score:'—')}head.appendChild(confidence);result.appendChild(head);
        const hypotheses=make('div','copilot-hypotheses');const hypothesisItems=Array.isArray(analysis.hypotheses)?analysis.hypotheses:[];hypothesisItems.forEach((item,index)=>{const card=make('article','copilot-hypothesis');const title=make('div','copilot-hypothesis-title');add(title,'span','','H'+(index+1));add(title,'strong','',item.title||'待验证假设');add(title,'b','',analysis.source==='model'?Math.round(Number(item.confidence||0)*100)+'%':((item.evidenceRefs||[]).length)+' 条证据');card.appendChild(title);renderCopilotRefs(card,item.evidenceRefs,analysis,o);const facts=make('div','copilot-falsification');add(facts,'span','','证伪方法');add(facts,'p','',item.falsificationTest||'—');card.appendChild(facts);if(item.missingEvidence){const missing=make('div','copilot-missing');add(missing,'span','','缺失证据');add(missing,'p','',item.missingEvidence);card.appendChild(missing)}const goal=add(card,'button','copilot-goal','以此为调查目标');goal.type='button';goal.title='把该假设填入调查目标并重新研判';goal.addEventListener('click',()=>{state.copilotQuestion=String(item.title||'');runCopilotAnalysis(o)});hypotheses.appendChild(card)});if(hypothesisItems.length)result.appendChild(hypotheses);
        const actions=make('section','copilot-actions');add(actions,'h4','','建议动作');const nextActions=Array.isArray(analysis.nextActions)?analysis.nextActions:[];if(!nextActions.length)add(actions,'div','copilot-no-actions','当前证据不足以产生建议动作，请先补充证据。');nextActions.forEach(item=>{const priority=String(item.priority||'P2');const row=make('div','copilot-action');add(row,'span','copilot-priority '+priority.toLowerCase(),priority);const body=make('div');add(body,'strong','',item.title||'待核对动作');add(body,'p','',item.rationale||'暂无理由说明。');renderCopilotRefs(body,item.evidenceRefs,analysis,o);row.appendChild(body);add(row,'span','copilot-approval',item.requiresApproval?'需人工审批':'只读建议');actions.appendChild(row)});result.appendChild(actions);
        if(analysis.doNotDo&&analysis.doNotDo.length){const guard=make('div','copilot-guard');add(guard,'strong','','安全边界');add(guard,'span','',analysis.doNotDo.join('；'));result.appendChild(guard)}
        add(result,'div','copilot-foot','生成于 '+when(analysis.generatedAt)+' · 副驾只提供证据约束的研判，不会自动执行处置');root.appendChild(result);
      }
      function renderCopilotQuality(parent,o){
        const quality=state.copilotQuality;const events=investigationEvents(o);const contextRate=quality?quality.eventContextCoverage:(events.length?events.filter(item=>item.context&&item.context.detailsAvailable).length/events.length:null);const versionRate=quality?quality.clientVersionCoverage:(o.clientVersions&&o.clientVersions.coverageRate);const score=quality?quality.score:Math.round(((Number(contextRate)||0)*45)+((Number(versionRate)||0)*35)+20);const row=make('div','copilot-quality');add(row,'span','copilot-quality-score','证据质量 '+score);[['上下文',copilotPct(contextRate)],['版本',copilotPct(versionRate)],['Run Trace',o.runTraces&&o.runTraces.length?'已接入':'待接入']].forEach(item=>{const node=make('div');add(node,'span','',item[0]);add(node,'strong','',item[1]);row.appendChild(node)});parent.appendChild(row);
      }
      function renderAiCopilotPanel(o){
        const panel=make('details','panel ai-copilot');panel.open=Boolean(state.copilotExpanded||state.copilotLoading);panel.setAttribute('aria-busy',String(Boolean(state.copilotLoading)));const summary=make('summary','ai-copilot-summary');const identity=make('div','ai-copilot-identity');const orb=add(identity,'span','ai-orb','EE');orb.title='Evidence Engine · 确定性证据引擎（本部署未接入模型）';const copy=make('div');add(copy,'div','copilot-kicker','证据约束研判');add(copy,'h2','','事故副驾');add(copy,'p','',state.copilotAnalysis?(state.copilotAnalysis.headline||'研判结果已就绪'):'按需展开：生成可证伪假设、证据引用和下一步。');identity.appendChild(copy);summary.appendChild(identity);const summaryMeta=make('div','copilot-summary-meta');add(summaryMeta,'span','copilot-mode','只读');add(summaryMeta,'span','copilot-toggle',panel.open?'收起':'展开');summary.appendChild(summaryMeta);panel.appendChild(summary);
        const body=make('div','ai-copilot-body');const boundary=make('p','copilot-boundary');boundary.textContent='不读取原始密钥，不自动执行处置；本部署未接入模型，全部研判由确定性证据引擎生成。';body.appendChild(boundary);renderCopilotQuality(body,o);
        const label=make('label','copilot-question-label');label.setAttribute('for','copilotQuestion');label.textContent='调查目标（可选）';body.appendChild(label);const ask=make('div','copilot-ask');const input=make('textarea');input.id='copilotQuestion';input.rows=2;input.maxLength=600;input.placeholder='例如：这次异常是否集中在某个版本？';input.value=state.copilotQuestion;input.disabled=state.copilotLoading;input.addEventListener('input',event=>{state.copilotQuestion=event.target.value});input.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key==='Enter'){event.preventDefault();runCopilotAnalysis(o)}});ask.appendChild(input);const button=add(ask,'button','btn primary',state.copilotLoading?'正在研判…':(state.copilotAnalysis?'重新研判':'研判当前证据'));button.type='button';button.disabled=state.copilotLoading;button.title='可使用 Ctrl/Command + Enter';button.addEventListener('click',()=>runCopilotAnalysis(o));ask.appendChild(button);body.appendChild(ask);
        const examples=['最近异常集中在哪个组件？','拨测失败影响哪些入口？','失败事件与哪个客户端版本相关？'];const chips=make('div','copilot-examples');chips.setAttribute('role','group');chips.setAttribute('aria-label','示例调查目标');examples.forEach(question=>{const chip=add(chips,'button','copilot-example',question);chip.type='button';chip.title='填入调查目标并研判';chip.addEventListener('click',()=>{state.copilotQuestion=question;runCopilotAnalysis(o)})});body.appendChild(chips);
        if(state.copilotLoading){const loading=make('div','copilot-loading');loading.setAttribute('role','status');loading.setAttribute('aria-live','polite');loading.appendChild(make('span','copilot-spinner'));add(loading,'div','','证据引擎正在对齐事故、检查、事件、SLO 与 Run Trace…');body.appendChild(loading)}else if(state.copilotError){const failed=make('div','copilot-error');failed.setAttribute('role','alert');add(failed,'strong','','研判未完成');add(failed,'span','',state.copilotError);add(failed,'span','', '已有调查证据仍可继续手动查看，也可点击上方按钮重试。');body.appendChild(failed)}else if(state.copilotAnalysis)renderCopilotAnalysis(body,state.copilotAnalysis,o);else{const empty=make('div','copilot-empty');add(empty,'strong','','用当前证据开始，不需要先写问题');add(empty,'span','','输出必须引用页面中的 evidence ref，并明确缺失证据与证伪方法。');body.appendChild(empty)}panel.appendChild(body);panel.addEventListener('toggle',()=>{state.copilotExpanded=panel.open;const toggle=panel.querySelector('.copilot-toggle');if(toggle)toggle.textContent=panel.open?'收起':'展开'});
        return panel;
      }
      const DSH_COPILOT_EVENT_REF=/^event:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
      function dshCopilotRef(kind,value){const safe=String(value||'').trim().replace(/[^A-Za-z0-9._:-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,160);return safe?kind+':'+safe:null}
      function dshCopilotPacket(o){
        const events=investigationEvents(o).filter(isInvestigationProblem);const evidenceIndex=[{ref:'summary:posture',kind:'summary',label:'生产稳定性态势'}];const eventRefs=[];
        events.slice(0,24).forEach(event=>{const ref=eventEvidenceId(event);if(!DSH_COPILOT_EVENT_REF.test(ref))return;eventRefs.push(ref);evidenceIndex.push({ref,kind:'event',label:String(event.component||'事件')+' · '+String(event.eventCode||'异常')})});
        (Array.isArray(o&&o.checks)?o.checks:[]).filter(check=>check.status&&check.status!=='healthy').slice(0,12).forEach(check=>{const ref=dshCopilotRef('check',check.key);if(ref)evidenceIndex.push({ref,kind:'check',label:String(check.title||check.key||'检查')})});
        const posture=o&&o.summary||{};const warning=[];const contextEvents=events.filter(event=>event.context&&event.context.detailsAvailable).length;if(events.length&&contextEvents/events.length<0.7)warning.push('事件上下文覆盖率不足 70%');if(!events.length)warning.push('当前窗口没有可引用的失败事件');
        return {events,eventRefs,evidenceIndex,warning,posture:{openIncidents:Number(posture.openIncidents)||0,criticalIncidents:Number(posture.criticalIncidents)||0,aiErrors:Number(o&&o.ai&&o.ai.errors)||0}};
      }
      function dshCopilotFallback(o,packet){
        const leadRef=packet.eventRefs[0]||null;const lead=packet.events.find(event=>eventEvidenceId(event)===leadRef)||null;const hasProblems=Boolean(packet.events.length||packet.posture.openIncidents||packet.posture.aiErrors);const actions=[];
        if(leadRef)actions.push({priority:'P1',title:'打开代表事件并核对上下文',rationale:'先验证事实、影响范围和关联 Run，再决定是否处置。',actionType:'investigate',requiresApproval:false,evidenceRefs:[leadRef]});
        if(leadRef&&state.remediation&&Array.isArray(state.remediation.playbooks)&&state.remediation.playbooks.length)actions.push({priority:'P0',title:'评估白名单处置剧本',rationale:'仅在证据确认后提交审批；执行仍由服务端 CAS 与后置验证保护。',actionType:'remediate',requiresApproval:true,evidenceRefs:[leadRef]});
        else if(leadRef)actions.push({priority:'P2',title:'继续观察并补齐证据覆盖',rationale:'当前只生成只读建议，不执行任何生产变更。',actionType:'observe',requiresApproval:false,evidenceRefs:[leadRef]});
        return {source:'evidence-engine',modelStatus:'unavailable',headline:hasProblems?'确定性证据引擎已整理当前异常':'当前窗口未发现明确异常证据',executiveSummary:hasProblems?'先核对代表事件和低敏上下文，再决定是否提交行动提案。':'当前检查与事件窗口未呈现明确故障，建议保持观察。',confidence:null,hypotheses:lead&&leadRef?[{title:'优先验证：'+String(lead.component||'代表事件'),evidenceRefs:[leadRef],missingEvidence:packet.warning.join('；')||'需要更多时间序列与变更证据',falsificationTest:'对比同时间窗口的版本、组件、Run 与恢复后样本；若异常不随该维度变化，则否定该假设。'}]:[],nextActions:actions,doNotDo:['不要在缺少真实事件证据和后置验证时直接扩大自愈范围'],generatedAt:new Date().toISOString(),evidenceIndex:packet.evidenceIndex};
      }
      async function runCopilotAnalysis(o){
        if(state.copilotLoading)return;state.copilotLoading=true;state.copilotExpanded=true;state.copilotError='';renderInvestigation(o);
        try{const packet=dshCopilotPacket(o||state.overview||{});const analysis=dshCopilotFallback(o||state.overview||{},packet);state.copilotQuality={score:Math.max(0,Math.min(100,Math.round((packet.events.length?45:20)+(packet.eventRefs.length?35:0)+Math.round((Number(packet.events.length?packet.events.filter(event=>event.context&&event.context.detailsAvailable).length/packet.events.length:0)||0)*20)))),eventContextCoverage:packet.events.length?packet.events.filter(event=>event.context&&event.context.detailsAvailable).length/packet.events.length:null,clientVersionCoverage:o&&o.clientVersions&&o.clientVersions.coverageRate};if(packet.eventRefs.length){const response=await fetch(base+'/api/ops/observability/actions/evidence-proof',{method:'POST',credentials:'same-origin',headers:apiHeaders(true),body:JSON.stringify({evidenceRefs:packet.eventRefs,runId:null})});if(response.status===401){renderAccess();throw new Error('not_authorized')}const data=await response.json().catch(()=>({}));if(response.status===403){if(typeof handleForbidden==='function')handleForbidden(data.error||'not_authorized');throw new Error(data.error||'not_authorized')}if(!response.ok||!data.ok||!data.evidenceProof)throw new Error(data.error||('HTTP '+response.status));analysis.evidenceProof=data.evidenceProof}state.copilotAnalysis=analysis;toast(packet.eventRefs.length?'证据引擎研判已生成，已绑定短期 evidence proof':'当前没有可用于行动提案的 event 证据，先继续观察')}catch(error){state.copilotError=friendlyError(error.message);toast('证据研判失败：'+state.copilotError,false)}finally{state.copilotLoading=false;renderInvestigation(state.investigationOverview||state.overview)}
      }
`;
