export const OPS_OBSERVABILITY_SCRIPT_A = `    (() => {
      const $ = id => document.getElementById(id);
      const base = location.pathname.replace(/\\/ops-observability\\/?$/, '');
      // Canonical views are listed first; legacy names remain parseable so old
      // bookmarks (#rules/#database/#session-traces) open the corresponding
      // accordion in the unified workbench instead of falling back to a blank tab.
      const viewNames = ['overview','service-levels','operator-metrics','data-health','database','skill-loop','evolution','investigate','alerts','traces','platform','tenants','metrics','rules','channels','agent-traces','session-traces','model-pool','settings'];
      const overviewScopedViews = ['overview','traces'];
      // Keep old deep links usable while the workbench exposes one canonical
      // set of top-level views.  Object/table/learning names were used by the
      // earlier observability console and should open the matching accordion
      // instead of silently falling back to the overview.
      const viewAliases = {metrics:'alerts',rules:'alerts',channels:'alerts',objects:'alerts',object:'alerts','alert-objects':'alerts','agent-traces':'traces','session-traces':'traces','model-pool':'platform',settings:'platform','platform-settings':'platform','skill-flywheel':'skill-loop','skill-governance':'skill-loop',learning:'skill-loop',skills:'skill-loop',postgres:'database','postgresql':'database'};
      const state = { overview:null, overviewHours:24, config:null, remediation:null, actions:null, learning:null, operatorMetrics:null, modelPool:null, objects:null, objectSelection:null, objectDetail:null, objectDetailLoading:false, objectSearch:'', objectTeam:'all', objectOwnerTeam:'all', objectLabel:'all', objectType:'all', objectArchived:'all', database:null, databaseHours:24, databaseLoading:false, databaseLoadedAt:0, databaseTableSelection:null, databaseTableDetail:null, databaseTablePage:1, databaseTableLoading:false, databaseTableSortColumn:'', databaseTableSortDirection:'asc', traceEnvironment:null, traceOutcome:null, investigationOverview:null, investigationOutcome:null, investigationQuery:'', pendingRemediate:null, view:'overview', viewSource:'overview', category:'all', statusFilter:'all', search:'', editingKey:null, editorDirty:false, editorReturnFocus:null, templateEditing:false, accessRendered:false };
      const viewMeta = {overview:['可观测中心 / 总览','生产可观测与告警','先判断生产影响，再处理事故、维护告警，最后下钻到链路证据。'],investigate:['可观测中心 / 事故调查','事故调查','关联异常趋势、代表证据与影响范围，形成可复核的根因假设。'],alerts:['可观测中心 / 告警策略','告警策略','管理指标、日志与拨测规则，验证阈值并安全配置通知。'],traces:['可观测中心 / 链路追踪','链路追踪','从原生 Trace 与会话链路定位慢请求、失败步骤和模型路由。'],'operator-metrics':['可观测中心 / 运营指标','运营指标','按天查看 token、新增用户、DAU、对话次数和 Agent Run。'],'data-health':['可观测中心 / 数据健康','数据健康','检查关键业务数据是否持续入库，并核对数量、趋势与最近写入。'],database:['可观测中心 / 数据库','数据库','从表目录和关系图下钻，并通过脱敏只读查询获取证据。'],'skill-loop':['可观测中心 / 学习与进化','Skill 数据闭环','把埋点采集、运行反馈、候选审核和发布回流放在同一条可追溯链路。'],evolution:['可观测中心 / 学习与进化','每日自我进化','查看证据聚合、质量闸门和可审核候选；候选不会自动上线。'],platform:['可观测中心 / 系统设置','系统设置','管理评估器、Canary 真实业务拨测与安全进化边界。'],metrics:['可观测中心 / 告警策略','指标与数据源','核对系统指标的数据源、状态和阈值。'],rules:['可观测中心 / 告警策略','告警策略','按指标、日志和拨测筛选，完成数据源到通知的策略闭环。'],channels:['可观测中心 / 通知模板','通知模板','先确认投递状态，再按需编辑降噪策略与渠道凭据。'],'agent-traces':['可观测中心 / 链路追踪','Agent 原生 Trace','从真实 Agent 执行记录定位模型、工具和持久化问题。'],'session-traces':['可观测中心 / 链路追踪','会话 Trace','按会话重放用户到 Agent 的完整链路。'],'model-pool':['可观测中心 / 模型池','模型路由池','查看模型健康与路由配置。'],settings:['可观测中心 / 系统设置','系统配置','配置评估器、Canary 真实业务拨测和日志签名。'],'service-levels':['可观测中心 / SLO','SLO 与错误预算','用 SLO 和错误预算衡量用户可感知的可靠性。']};
      const categoryNames = {metric:'指标',log:'日志',probe:'拨测'};
      const statusNames = {healthy:'正常',observing:'Pending',warning:'告警',critical:'严重',stale:'数据过期',disabled:'已停用',open:'进行中',acknowledged:'已确认',silenced:'已静默',resolved:'已恢复',running:'运行中',no_candidate:'暂无候选',candidate_ready:'待审核',rejected:'已拒绝',blocked:'已阻塞',error:'失败',never:'未运行'};
      const severityNames = {critical:'严重',warning:'警告'};
      const fieldNames = {windowMinutes:'查询窗口（分钟）',minSamples:'最少样本数',threshold:'告警阈值',criticalThreshold:'严重阈值',ratePercent:'失败率阈值（%）',openAfter:'Pending 连续评估次数',resolveAfter:'连续恢复次数'};
      const make = (tag, cls, value) => { const node=document.createElement(tag); if(cls)node.className=cls; if(value!==undefined&&value!==null)node.textContent=String(value); return node; };
      const add = (parent, tag, cls, value) => { const node=make(tag,cls,value); parent.appendChild(node); return node; };
      const fmt = value => Number(value||0).toLocaleString();
      const pct = value => value==null?'—':(Number(value)*100).toFixed(1)+'%';
      const when = value => {if(!value)return '—';const date=new Date(value);return Number.isFinite(date.getTime())?date.toLocaleString('zh-CN',{hour12:false}):'—'};
      // 主站会话镜像（localStorage）：桌面 / 非 https / 跨源场景下 Cookie 带不到，
      // 镜像头是唯一凭证通道；同源 https 浏览器走 HttpOnly Cookie，由服务端直接读。
      // 键名必须与 apiHeaders 的小写会话头一致——大小写不同的两个键会被 fetch 合并
      // 成一个逗号值，服务端按 64-hex 校验会把整条会话判为无效。
      function studioSessionHeaders(){try{const headers={};if(!sessionStorage.getItem('d_obs_sso_session')){const session=localStorage.getItem('rdk_sso_session_mirror');if(session)headers['x-rdk-sso-session']=session;const cloud=localStorage.getItem('rdk_sso_session_mirror_cloud');if(cloud)headers['x-rdk-sso-session-cloud']=cloud}return headers}catch{return {}}}
      // 主站 SSO 账号登录（组员/管理员）：/api/ops/auth/login 成功后把主站
      // 会话存 sessionStorage（键名与 Studio 镜像不同，避免互相踩踏）。
      function obsSsoSessionId(){try{return sessionStorage.getItem('d_obs_sso_session')||''}catch{return ''}}
      function obsActiveTenant(){try{return sessionStorage.getItem('d_obs_active_tenant')||''}catch{return ''}}
      const opsSsoSession = obsSsoSessionId();
      const opsSsoActiveTenant = obsActiveTenant();
      // /auth/me 的启动结果：{user, tenants, admin, relayConfigured}。
      const obsAuthState = {me:null};
      // 独立部署没有 Studio SSO 会话；用 URL ?ops-token= 一次性注入管理
      // token 存 sessionStorage（不落 localStorage、不留在地址栏），后续请求
      // 原样带上 x-admin-token 头。Studio 部署下该值为空，行为不变。
      function standaloneAdminToken(){try{const url=new URL(location.href);const fromUrl=url.searchParams.get('ops-token');if(fromUrl){sessionStorage.setItem('d_obs_admin_token',fromUrl);url.searchParams.delete('ops-token');history.replaceState(null,'',url)}return sessionStorage.getItem('d_obs_admin_token')||''}catch{return ''}}
      const opsAdminToken = standaloneAdminToken();
      // 租户视图入口：?tenant-token= 一次性注入租户 token（同样只存
      // sessionStorage）。租户模式下请求带 x-tenant-token 头，只展示本租户
      // 的拨测检查/事故/通知只读视图；不与 admin token 同时使用。
      function standaloneTenantToken(){try{const url=new URL(location.href);const fromUrl=url.searchParams.get('tenant-token');if(fromUrl){sessionStorage.setItem('d_obs_tenant_token',fromUrl);url.searchParams.delete('tenant-token');history.replaceState(null,'',url)}return sessionStorage.getItem('d_obs_tenant_token')||''}catch{return ''}}
      const opsTenantToken = standaloneTenantToken();
      const opsTenantMode = Boolean(opsTenantToken && !opsAdminToken);
      // 组员视图模式：由 /auth/me 的结果决定（会话可能来自同源 HttpOnly Cookie 的
      // 免登通道，此时 sessionStorage 里没有会话 id，不能拿它当判据）。启动时用
      // token 存在性给一个保守初值，me 解析后由 applyAuthMode 重算——apiHeaders 是
      // 闭包，按调用时刻读取该变量。声明必须排在两个 token 常量之后（const 暂时性死区）。
      let opsMemberMode = Boolean(opsSsoSession && opsSsoActiveTenant && !opsAdminToken && !opsTenantToken);
      function applyAuthMode(me){const user=me&&me.user;const tenants=(me&&me.tenants)||[];opsMemberMode=Boolean(user&&!me.admin&&tenants.length&&!opsAdminToken&&!opsTenantToken&&opsSsoActiveTenant);return opsMemberMode}
      const apiHeaders = mutation => Object.assign({'content-type':'application/json'},studioSessionHeaders(),opsAdminToken?{'x-admin-token':opsAdminToken}:{},opsTenantMode?{'x-tenant-token':opsTenantToken}:{},opsSsoSession?{'x-rdk-sso-session':opsSsoSession}:{},opsMemberMode?{'x-rdk-obs-tenant':opsSsoActiveTenant}:{},mutation?{'X-RDK-Ops-Action':'observability'}:{});
      // 退出：把四条本地凭证全部清掉。只清 SSO 会话会让同一标签页里的 token 直连
      // 身份继续生效（刷新后仍是管理员，且会盖掉后续的账号登录）。
      async function obsLogout(){try{await fetch(base+'/api/ops/auth/logout',{method:'POST',headers:Object.assign({'content-type':'application/json'},apiHeaders(false))})}catch{}try{['d_obs_sso_session','d_obs_active_tenant','d_obs_admin_token','d_obs_tenant_token'].forEach(key=>sessionStorage.removeItem(key))}catch{}location.reload()}
      // 登录屏判定用公开只读端点（永远 200）：业务端点的 403 既可能是「未登录」，
      // 也可能是某个模块域的权限降级，不能拿它当判据。
      async function obsAccessEnabled(){try{const response=await fetch(base+'/api/ops/observability/access',{headers:apiHeaders(false),credentials:'same-origin'});const data=await response.json().catch(()=>null);return response.ok&&data&&data.ok?Boolean(data.enabled):null}catch{return null}}
      async function obsLoadMe(){try{const response=await fetch(base+'/api/ops/auth/me',{headers:apiHeaders(false),credentials:'same-origin'});if(!response.ok)return null;const data=await response.json().catch(()=>null);if(!data||!data.ok)return null;obsAuthState.me=data;return data}catch{return null}};
      function toast(message, ok=true){const node=$('toast');node.textContent=message;node.className='toast show '+(ok?'ok':'bad');clearTimeout(toast.timer);toast.timer=setTimeout(()=>{node.className='toast'},3600)}
      function setFeedback(id,message,ok=true){const node=$(id);if(!node)return;node.textContent=message;node.className='feedback '+(ok?'ok':'bad')}
      function projectTelemetryState(kind,label){const next=['live','stale','error','unauthorized'].includes(kind)?kind:'unknown';const header=$('headerTelemetryStatus');if(header){header.className='header-live '+next;header.textContent=label||({live:'Telemetry 已接入',stale:'Telemetry 可能过期',error:'Telemetry 加载失败',unauthorized:'Telemetry 未授权',unknown:'Telemetry 未确认'})[next]}const scope=$('scopeStatus');if(scope){scope.className='scope-status '+next;scope.textContent=next==='live'?'数据持续接入':next==='stale'?'数据可能过期':next==='unauthorized'?'当前账号无权限':next==='error'?'数据加载失败':'等待真实数据'}}
      // 最近一次成功加载的时刻（轮询节流用：所有加载分支都经过这里）。
      let obsLastOkAt=0;
      function applyOverviewSnapshot(overview){obsLastOkAt=Date.now();state.overview=overview||null;const alerting=state.overview&&state.overview.alerting;if(!alerting||!alerting.lastCheckedAt)projectTelemetryState('unknown');else if(alerting.status==='stale')projectTelemetryState('stale');else projectTelemetryState('live');if(state.overview&&typeof renderOverview==='function')renderOverview();if(typeof updateGlobalContext==='function')updateGlobalContext(state.overview);if(typeof setNavGroupAlerts==='function')setNavGroupAlerts(state.overview)}
      function syncScopeVisibility(name){const scope=$('overviewScopeBar');if(scope)scope.classList.toggle('hidden',!overviewScopedViews.includes(name))}
      function friendlyError(message){const labels={feishu_contact_point_not_configured:'请先填写飞书 Webhook URL',webhook_contact_point_not_configured:'请先填写通用 Webhook URL',notification_delivery_disabled:'请先启用真实通知并关闭影子模式',not_authorized:'当前账号没有运营配置权限',remediation_cooldown:'该剧本近期已执行，处于冷却期，请稍后重试',remediation_already_running:'已有自愈正在执行，请等待其完成',remediation_store_unavailable:'审计数据库不可用，暂无法执行自愈',remediation_start_failed:'自愈执行单元启动失败',unknown_remediation_playbook:'未知的自愈剧本',action_store_unavailable:'行动审计数据库暂不可用，请稍后重试',action_evidence_proof_invalid:'证据包已过期或已变化，请重新研判',action_evidence_proof_required:'请从 AI 事故副驾生成带证据的行动',action_approval_expired:'审批已过期，请重新审批',action_state_conflict:'行动状态已被其他人更新，请刷新后继续',action_execution_failed:'白名单剧本执行失败，请查看后置验证',action_verification_failed:'后置验证未通过，请查看失败证据并加入回归集',action_completion_requires_approval:'该行动尚未完成审批',ai_sql_provider_unavailable:'当前账号没有可用的 AI 模型配置',ai_sql_schema_unavailable:'AI 脱敏查询层尚未就绪，请稍后重试',ai_sql_generation_failed:'AI 生成 SQL 失败，请重试',ai_sql_invalid_response:'AI 返回的 SQL 格式无效，请换一种问法',ai_sql_execution_failed:'生成的 SQL 执行失败，请换一种问法',ai_sql_query_in_progress:'已有数据库查询正在执行',ai_sql_rate_limited:'操作太频繁，请稍后再试',ai_sql_question_invalid:'请描述要查询的问题',ai_sql_export_format_invalid:'导出格式只支持 JSON 或 CSV',ai_sql_not_read_only:'只允许执行只读 SQL',ai_sql_unsafe_syntax:'生成的 SQL 未通过安全检查',ai_sql_schema_blocked:'只能查询脱敏视图',ai_sql_schema_required:'查询必须使用 ops_ai 脱敏视图',ai_sql_relation_blocked:'查询访问了未授权数据表',ai_sql_function_blocked:'查询使用了不安全函数',tenant_list_unavailable:'租户数据服务暂不可用，请稍后重试',tenant_create_failed:'创建租户失败，请核对参数后重试',tenant_already_exists:'该租户 ID 已存在',tenant_id_invalid:'租户 ID 不符合规范：需小写字母开头，2–40 字符',tenant_token_rotate_failed:'token 轮换失败，请稍后重试',tenant_status_failed:'租户状态更新失败，请稍后重试',tenant_not_found:'租户不存在或已被删除',tenant_scope_only:'该模块属于平台运营视图，租户凭证不可访问',tenant_members_unavailable:'组员数据服务暂不可用，请稍后重试',tenant_member_add_failed:'添加组员失败，请稍后重试',tenant_member_role_failed:'修改组员角色失败，请稍后重试',tenant_member_remove_failed:'移除组员失败，请稍后重试',member_not_found:'该账号不是本租户组员',member_already_exists:'该账号已是本租户组员',invalid_sso_user_id:'账号 ID 格式不正确（4–128 位字母数字）',invalid_member_role:'角色只支持 owner 或 member',last_owner_role_required:'本租户只剩这一个 owner，不能降级',last_owner_required:'本租户只剩这一个 owner，不能移除',not_a_member:'你不是该租户的组员',sso_relay_disabled:'账号登录未启用（未配置主站中继），请联系管理员',login_rate_limited:'登录尝试过于频繁，请 15 分钟后再试',sso_login_failed:'登录服务暂不可用，请稍后重试',missing_user_name_or_password:'请输入账号和密码',sso_relay_unavailable:'账号登录中继暂不可用，请稍后重试或联系管理员',tenant_disabled:'该租户已被停用，请联系平台管理员',central_store_disabled:'中心库未启用，租户与组员功能暂不可用',invalid_tenant_token:'租户 token 无效或已轮换，请重新获取',invalid_tenant_status:'租户状态只支持 active 或 disabled',observability_query_failed:'可观测数据查询失败，请稍后重试',postgres_table_detail_query_failed:'数据表详情查询失败，请稍后重试',telemetry_governance_unavailable:'遥测治理服务暂不可用，请稍后重试'};return labels[message]||'操作失败，请稍后重试'}
      function section(title,hint){const node=make('section','panel section');const head=make('div','section-head');const box=make('div');add(box,'h2','',title);if(hint)add(box,'div','hint',hint);head.appendChild(box);node.appendChild(head);return node}
      function field(parent,id,labelText,value,type='text',full=false){const box=make('div','field'+(full?' full':''));const label=add(box,'label','',labelText);label.htmlFor=id;const input=make(type==='textarea'?'textarea':'input');input.id=id;if(type!=='textarea')input.type=type;if(type==='password'){input.autocomplete='new-password';input.name='ops-secret-'+id;input.dataset.lpignore='true';input.dataset['1pIgnore']='true'}input.value=value==null?'':String(value);box.appendChild(input);parent.appendChild(box);return input}
      function selectField(parent,id,labelText,value,options,full=false){const box=make('div','field'+(full?' full':''));const label=add(box,'label','',labelText);label.htmlFor=id;const select=make('select');select.id=id;options.forEach(optionData=>{const option=make('option','',optionData[1]);option.value=optionData[0];option.selected=optionData[0]===value;select.appendChild(option)});box.appendChild(select);parent.appendChild(box);return select}
      function switchField(parent,id,labelText,checked){const label=make('label','switch');const input=make('input');input.type='checkbox';input.id=id;input.checked=Boolean(checked);label.appendChild(input);label.appendChild(document.createTextNode(labelText));parent.appendChild(label);return input}
      // 401 与 403 语义不同：401 是未登录（登录屏可恢复），403 是已登录但权限变化
      // （被移出租户 / 租户停用 / 模块域降级）。403 不能清屏，只提示并刷新身份快照。
      let obsForbiddenNotifiedAt=0;let obsForbiddenCode='';
      // 只有这些 403 说明「你的身份/租户权限变了」——需要提示并重查身份。
      // 其余 403 是模块级能力差异（admin token 直连下行动域的预期降级、租户 token
      // 的只读限制等），按原有方式静默降级：否则每轮轮询都会弹一次误报。
      // 只列「身份/租户权限被改动」的码：invalid_tenant_token 是 gate 的 401
      // （真凭证失效），tenant_scope_only 是「租户凭证打了平台面」的正常收敛，
      // 两者都不该当作权限变化来提示。
      const OBS_IDENTITY_FORBIDDEN_CODES=['not_a_member','tenant_disabled'];
      function handleForbidden(code){
        if(!OBS_IDENTITY_FORBIDDEN_CODES.includes(code))return false;
        const now=Date.now();
        projectTelemetryState('unauthorized');
        if(code!==obsForbiddenCode||now-obsForbiddenNotifiedAt>15000){obsForbiddenNotifiedAt=now;obsForbiddenCode=code;toast('权限已变化：'+friendlyError(code),false)}
        obsLoadMe().then(me=>{if(me)applyAuthMode(me)});
        return true;
      }
      async function request(path, options){const response=await fetch(base+path,Object.assign({credentials:'same-origin',headers:apiHeaders(Boolean(options&&options.method&&options.method!=='GET'))},options||{}));if(response.status===401){renderAccess();throw new Error('not_authorized')}if(response.status===403){const denied=await response.json().catch(()=>({}));const code=String((denied&&(denied.error||denied.message))||'not_authorized');const deniedError=new Error(code);deniedError.forbidden=handleForbidden(code);throw deniedError}const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.message||data.error||(data.result&&data.result.error)||('HTTP '+response.status));return data}
      function renderAccess(){ // admin-token 直连模式下 action/证据域仍要求 SSO 账号身份；
      // 租户 token 模式是只读降级，两种情况都不该把已渲染的看板整体盖住。
      if(opsAdminToken||opsTenantMode){projectTelemetryState('unauthorized');return}
      projectTelemetryState('unauthorized');if(state.accessRendered)return;state.accessRendered=true;const box=make('section','panel access');box.dataset.accessScreen='true';add(box,'h2','','需要运营账号登录');add(box,'p','','本页数据受运营账号权限保护。使用主站账号登录（加入租户的组员与平台管理员均可），或使用运营令牌入口。');
      // 主站账号登录：中继可用时为主表单（组员/管理员共用）；成功后把主站
      // 会话存 sessionStorage 并整页重载，让初始化流程带会话重跑。
      const relayReady=Boolean(obsAuthState.me&&obsAuthState.me.relayConfigured);
      if(relayReady){
        const accountForm=make('form');accountForm.className='access-form';accountForm.noValidate=true;
        const userField=field(accountForm,'obsLoginUser','主站账号','','text',false);
        userField.placeholder='账号名（与主站登录一致）';userField.autocomplete='username';
        const passField=field(accountForm,'obsLoginPassword','密码','','password',false);
        passField.placeholder='主站账号密码';
        const submit=add(accountForm,'button','btn primary','登录');submit.type='submit';
        const note=add(accountForm,'div','feedback',' ');
        accountForm.addEventListener('submit',async event=>{event.preventDefault();const userName=String(userField.value||'').trim();const password=String(passField.value||'');if(!userName||!password){note.textContent='请输入账号和密码';note.className='feedback bad';return}submit.disabled=true;submit.textContent='登录中…';
          try{const response=await fetch(base+'/api/ops/auth/login',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({userName,password})});
            const data=await response.json().catch(()=>({}));
            if(response.ok&&data.ok&&data.sessionId){sessionStorage.setItem('d_obs_sso_session',data.sessionId);location.reload();return}
            // friendlyError 现在有兜底文案，不能再靠 || 区分「未知错误码」；
            // 中继自身故障码之外的一切失败都按凭据不正确提示（避免泄露原始错误码）。
            const relayCodes=['missing_user_name_or_password','login_rate_limited','sso_relay_disabled','sso_relay_unavailable','sso_login_failed','cross_origin_login_denied','invalid_origin'];
            note.textContent=relayCodes.includes(String(data.error||''))?friendlyError(data.error):'账号或密码不正确，请重试';note.className='feedback bad';
          }catch{note.textContent='网络异常，请稍后重试';note.className='feedback bad'}
          submit.disabled=false;submit.textContent='登录'});
        box.appendChild(accountForm);
        const divider=make('div','hint');divider.style.margin='14px 0 6px';divider.textContent='也可以使用运营令牌（管理员直连）：';box.appendChild(divider);
      }
      const form=make('form');form.className='access-form';form.noValidate=true;
      const input=field(form,'opsTokenInput','运营令牌','','password',true);input.placeholder='运营令牌（ops-token）';
      const submit=add(form,'button','btn primary','登录');submit.type='submit';
      const note=add(form,'div','feedback',' ');
      form.addEventListener('submit',async event=>{event.preventDefault();const value=String(input.value||'').trim();if(!value){note.textContent='请输入运营令牌';note.className='feedback bad';return}submit.disabled=true;submit.textContent='验证中…';
        try{const response=await fetch(base+'/api/ops/observability/access',{headers:{'content-type':'application/json','x-admin-token':value}});
          if(response.ok){sessionStorage.setItem('d_obs_admin_token',value);location.reload();return}
          note.textContent='令牌无效或权限不足，请核对后重试';note.className='feedback bad';
        }catch{note.textContent='网络异常，请稍后重试';note.className='feedback bad'}
        submit.disabled=false;submit.textContent='登录'});
      box.appendChild(form);
      document.querySelectorAll('.view').forEach(node=>node.classList.add('hidden'));const main=document.querySelector('main');if(main)main.appendChild(box);const fresh=$('fresh');if(fresh)fresh.textContent='真实数据和配置受运营账号权限保护';setTimeout(()=>{try{(relayReady?userField:input).focus()}catch{}},50)}
      // 管理员选中租户时用 ?tenant= 把概览切到该租户视角：服务端只对管理员生效
      // 且会校验租户存在（组员模式走 x-rdk-obs-tenant 头，不经过这里）。
      function adminTenantQuery(){try{const me=obsAuthState.me;const tenant=obsActiveTenant();return me&&me.admin&&tenant?'&tenant='+encodeURIComponent(tenant):''}catch{return ''}}
      function updateViewHeader(source,name){const meta=viewMeta[source]||viewMeta[name]||viewMeta.overview;[['pageKicker',meta[0]],['pageTitle',meta[1]],['pageIntro',meta[2]]].forEach(item=>{const node=$(item[0]);if(node)node.textContent=item[1]});document.title='d-obs · '+meta[1]}
      const navGroupByView={investigate:'core',alerts:'core',traces:'core','operator-metrics':'data','data-health':'data',database:'data','skill-loop':'learning',evolution:'learning',platform:'advanced','service-levels':'core'};
      // 多级收起菜单的统一徽章层：分组收起时把组内关键计数提升到分组头，
      // 展开后组内 tab 上的计数继续可见；两个位置由同一份状态驱动，避免漂移。
      function navBadgeValue(id){const node=$(id);if(!node||node.hidden)return 0;const value=Number(node.textContent);return Number.isFinite(value)?value:0}
      function activeIncidentCount(o){const incidents=Array.isArray(o&&o.incidents)?o.incidents:[];return incidents.filter(item=>['open','acknowledged','silenced'].includes(item.status)).length}
      function setNavGroupAlerts(o){const count=o!=null?activeIncidentCount(o):navBadgeValue('incidentCount');const incidentBadge=$('incidentCount');if(incidentBadge&&count>0){incidentBadge.textContent=String(count);incidentBadge.hidden=false;incidentBadge.title=count+' 个进行中事故'}const coreAlert=$('navCoreAlert');if(coreAlert){coreAlert.textContent=count?String(count):'';coreAlert.hidden=!count;coreAlert.title=count?count+' 个进行中事故':'';const group=coreAlert.closest('.nav-group');if(group)group.classList.toggle('has-alert',count>0)}const overviewCount=$('overviewCount');if(overviewCount){overviewCount.textContent=count?String(count):'';overviewCount.hidden=!count;overviewCount.title=count?count+' 个进行中事故':''}}
      function openNavGroupForView(name){const groupName=navGroupByView[name]||'';document.querySelectorAll('.nav-group').forEach(group=>{group.open=Boolean(groupName&&group.dataset.navGroup===groupName)})}
      function initNavGroups(){document.querySelectorAll('.nav-group').forEach(group=>group.addEventListener('toggle',()=>{if(group.open)document.querySelectorAll('.nav-group').forEach(other=>{if(other!==group)other.open=false})}))}
      function setView(requested, updateHash=true){const source=requested;const name=viewAliases[requested]||requested;if(!viewNames.includes(name))return setView('overview',updateHash);// 租户只读模式收敛到总览视图：其余视图属于平台运营域。
      if(opsTenantMode&&name!=='overview')return setView('overview',updateHash);
      // SSO 组员模式：只放开总览（本租户只读）与租户（owner 管组员 /
      // member 看本租户名单）；其余视图属于平台运营域。
      if(opsMemberMode&&name!=='overview'&&name!=='tenants')return setView('overview',updateHash);state.view=name;state.viewSource=source;updateViewHeader(source,name);syncScopeVisibility(name);openNavGroupForView(name);const activeView=document.querySelector('[data-view="'+source+'"]')?source:name;document.querySelectorAll('[data-view]').forEach(button=>{const active=button.dataset.view===activeView;button.classList.toggle('active',active);if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current')});viewNames.forEach(view=>{const node=$('view-'+view);if(node)node.classList.toggle('hidden',view!==name)});if(updateHash)history.replaceState(null,'','#'+source);if(name==='investigate'&&typeof renderInvestigation==='function')renderInvestigation(state.investigationOverview||state.overview);if(name==='service-levels')renderServiceLevels();if(name==='operator-metrics'&&typeof loadOperatorMetrics==='function')loadOperatorMetrics(false);if((name==='data-health'||name==='database')&&typeof loadPostgresDashboard==='function')loadPostgresDashboard();if((name==='skill-loop'||name==='evolution')&&typeof renderLearningModules==='function')renderLearningModules();if(name==='alerts'){if(typeof renderMetrics==='function')renderMetrics();if(typeof renderObjects==='function')renderObjects();renderRules();renderChannels();const section=source==='metrics'?$('alerts-metrics'):['objects','object','alert-objects'].includes(source)?$('alerts-objects'):source==='channels'?$('alerts-channels'):$('alerts-rules');if(section)section.open=true}if(name==='traces'){if(typeof renderNativeTraces==='function')renderNativeTraces();if(source==='session-traces'&&$('traces-session'))$('traces-session').open=true}if(name==='tenants'){if(opsMemberMode&&typeof renderObsMemberTenantsView==='function')renderObsMemberTenantsView();else{bindTenantPanel();loadTenants()}}if(name==='platform'){renderSettings();renderEvolution();if(source==='model-pool'&&typeof renderModelPool==='function')renderModelPool();const section=source==='model-pool'?$('platform-model'):$('platform-settings');if(section)section.open=true}}
      function renderLoadPanel(root,label,error){if(!root)return;root.replaceChildren();const panel=make('section','panel load-state '+(error?'error':'loading'));panel.setAttribute('role',error?'alert':'status');panel.setAttribute('aria-live','polite');add(panel,'div','load-state-icon',error?'!':'');const copy=make('div');add(copy,'strong','',error?label:'正在加载'+label+'…');add(copy,'span','',error?'请检查网络或运营权限后重试。':'已发起真实数据请求，请稍候。');panel.appendChild(copy);if(error){const retry=add(panel,'button','btn','重试');retry.type='button';retry.addEventListener('click',()=>loadAll(true))}root.appendChild(panel)}
      function renderInitialLoading(){if(state.config)return;renderLoadPanel($('metricsContent'),'指标与数据源',false);renderLoadPanel($('rulesList'),'告警策略',false);renderLoadPanel($('templateSummary'),'通知模板',false);renderLoadPanel($('settingsContent'),'系统设置',false)}
      function renderInitialError(message){if(state.config)return;const label='加载失败：'+friendlyError(message);renderLoadPanel($('metricsContent'),label,true);renderLoadPanel($('rulesList'),label,true);renderLoadPanel($('templateSummary'),label,true);renderLoadPanel($('settingsContent'),label,true)}
      function overviewNumber(value){const parsed=Number(value);return Number.isFinite(parsed)?parsed:0}
      function overviewChecks(o){return Array.isArray(o&&o.checks)?o.checks:[]}
      function overviewIncidents(o){return Array.isArray(o&&o.incidents)?o.incidents:[]}
      function checkStatus(key){return overviewChecks(state.overview).find(check=>check.key===key)}
      function conditionText(def,rule){if(def.key==='ai-run-degraded-rate')return '样本 ≥ '+rule.minSamples+'，失败/部分完成率 ≥ '+rule.ratePercent+'%，且异常数 ≥ '+rule.threshold;if(def.key==='llm-token-budget')return rule.windowMinutes+' 分钟内 token 总量 ≥ '+Number(rule.threshold).toLocaleString();if(def.key==='api-5xx-spike')return rule.windowMinutes+' 分钟内计数 ≥ '+rule.threshold+'，客户端错误需独立样本 ≥ '+rule.minSamples;if(def.key==='disk-space')return '磁盘使用率 ≥ '+rule.threshold+'%';if(def.key==='slo-error-budget-burn')return '1h / 6h 错误预算燃烧率 ≥ '+rule.threshold+'x';if(def.key==='external-tls')return '证书剩余天数 < '+rule.threshold+' 天';if(def.category==='probe')return '不可用，或耗时 ≥ '+rule.threshold+' ms';return rule.windowMinutes+' 分钟窗口内计数 ≥ '+rule.threshold}
      function criticalText(def,rule){if(def.key==='external-tls')return '证书校验失败立即视为严重';if(def.key==='disk-space')return '严重：≥ '+rule.criticalThreshold+'%';if(def.key==='slo-error-budget-burn')return '严重燃烧：≥ '+rule.criticalThreshold+'x';if(def.category==='probe')return '严重延迟：≥ '+rule.criticalThreshold+' ms';return '严重阈值：'+rule.criticalThreshold}
      function resolvedChannel(rule){return rule.notificationChannel==='default'?state.config.notification.channel:rule.notificationChannel}
      function channelConfigured(rule){const channel=resolvedChannel(rule);if(channel==='none')return false;if(channel==='feishu')return state.config.notification.feishuWebhookConfigured;return state.config.notification.genericWebhookConfigured}
      function channelText(rule){if(rule.notificationChannel==='none')return '不发送';const channel=resolvedChannel(rule);const label=channel==='feishu'?'飞书机器人':'通用 Webhook';return (rule.notificationChannel==='default'?'默认 · ':'')+label+(channelConfigured(rule)?'':'（未配置）')}
      function dataSourceName(def){if(def.key.startsWith('external-'))return '异地拨测';if(def.key.startsWith('synthetic-'))return '真实业务链路拨测';if(def.key==='slo-error-budget-burn')return 'SLO 错误预算引擎';if(def.key==='agent-model-target-degraded')return '3100/3101 gateway target-health';if(def.key==='nginx-5xx-log')return 'Nginx access.log';if(def.key==='postgres-error-log'||def.key==='central-database')return 'PostgreSQL';if(def.key==='service-crash-signature'||def.key==='process-unhandled-error'||def.key==='internal-health')return 'systemd / 本机';if(def.category==='metric')return 'RDK 运营遥测';return '独立巡检 Worker'}
      function targetName(def){return def.key.startsWith('external-')?'异地探针':'主站'}
      function renderRuleSummary(definitions){const root=$('ruleSummary');root.replaceChildren();const enabled=definitions.filter(def=>state.config.rules[def.key].enabled).length;const firing=definitions.filter(def=>['warning','critical'].includes(checkStatus(def.key)?.status)).length;const pending=definitions.filter(def=>checkStatus(def.key)?.status==='observing').length;const routed=definitions.filter(def=>state.config.rules[def.key].enabled&&channelConfigured(state.config.rules[def.key])).length;[['全部策略',definitions.length,'','指标 / 日志 / 拨测'],['生效策略',enabled,'good',(definitions.length-enabled)+' 条停用'],['触发中',firing+pending,(firing+pending)?'bad':'good',firing+' 告警 · '+pending+' Pending'],['可投递',routed,routed?'good':'warn','已绑定有效发送模板']].forEach(item=>{const card=make('div','panel summary-card');add(card,'div','summary-label',item[0]);add(card,'div','summary-value '+item[2],item[1]);add(card,'div','summary-note',item[3]);root.appendChild(card)})}
      function renderMetrics(){if(!state.config)return;const definitions=state.config.definitions.filter(def=>def.category==='metric');$('metricCount').textContent=String(definitions.length);const panel=make('section','panel metric-catalog');const head=make('div','metric-head');['指标名称','数据源','当前状态','告警阈值','严重阈值','查询窗口','操作'].forEach(value=>add(head,'div','',value));panel.appendChild(head);definitions.forEach(def=>{const rule=state.config.rules[def.key];const check=checkStatus(def.key);const status=rule.enabled?(check?.status||'healthy'):'disabled';const row=make('article','metric-row');const name=make('div');add(name,'div','rule-title',def.title);add(name,'div','metric-source',def.key);row.appendChild(name);const source=make('div');add(source,'div','',dataSourceName(def));add(source,'div','metric-source',def.description);row.appendChild(source);const stateCell=make('div','metric-status');stateCell.appendChild(make('span','state-dot '+status));add(stateCell,'span','',statusNames[status]||status);row.appendChild(stateCell);add(row,'div','',conditionText(def,rule));add(row,'div','',criticalText(def,rule));add(row,'div','',rule.windowMinutes?rule.windowMinutes+' 分钟':'每 60 秒');const edit=add(row,'button','icon-btn','✎');edit.type='button';edit.title='编辑指标阈值';edit.setAttribute('aria-label','编辑 '+def.title);edit.addEventListener('click',()=>openEditor(def.key));row.appendChild(edit);panel.appendChild(row)});const root=$('metricsContent');root.replaceChildren(panel)}
      function updateFilterSummary(){const count=(state.category==='all'?0:1)+(state.statusFilter==='all'?0:1);$('filterText').textContent=count?'筛选('+count+')':'筛选';$('filterTrigger').classList.toggle('active',count>0)}
      function renderRules(){if(!state.config)return;const definitions=state.config.definitions;$('ruleCount').textContent=String(definitions.length);renderRuleSummary(definitions);updateFilterSummary();if(typeof setNavGroupAlerts==='function')setNavGroupAlerts(state.overview);const search=state.search.toLowerCase();const shown=definitions.filter(def=>{const rule=state.config.rules[def.key];const categoryMatch=state.category==='all'||def.category===state.category;const statusMatch=state.statusFilter==='all'||(state.statusFilter==='enabled'?rule.enabled:!rule.enabled);const searchMatch=!search||(def.title+' '+def.description+' '+def.key+' '+dataSourceName(def)).toLowerCase().includes(search);return categoryMatch&&statusMatch&&searchMatch});const root=$('rulesList');root.replaceChildren();if(!shown.length){root.appendChild(make('div','empty','没有匹配的告警策略'));return}shown.forEach(def=>{const rule=state.config.rules[def.key];const check=checkStatus(def.key);const status=rule.enabled?(check?.status||'healthy'):'disabled';const row=make('article','rule-row');const main=make('div','rule-main');main.appendChild(make('span','state-dot '+status));const titleBox=make('div');add(titleBox,'div','rule-title',def.title);add(titleBox,'div','rule-meta',dataSourceName(def)+' · '+def.key);main.appendChild(titleBox);row.appendChild(main);row.appendChild(make('span','category-chip type-'+def.category,categoryNames[def.category]));const condition=make('div','rule-condition',conditionText(def,rule));add(condition,'small','',criticalText(def,rule));row.appendChild(condition);const evaluation=make('div','rule-eval','每 60 秒');add(evaluation,'small','','持续 '+rule.openAfter+' 次 · 恢复 '+rule.resolveAfter+' 次');row.appendChild(evaluation);row.appendChild(make('div','channel-chip '+(!channelConfigured(rule)?'silent':''),channelText(rule)));const toggle=make('button','strategy-toggle '+(rule.enabled?'on':''),rule.enabled?'开启':'关闭');toggle.type='button';toggle.title=(rule.enabled?'停用':'启用')+'此告警策略';toggle.setAttribute('aria-label',(rule.enabled?'停用 ':'启用 ')+def.title);toggle.setAttribute('aria-pressed',String(rule.enabled));toggle.addEventListener('click',()=>toggleRule(def.key,!rule.enabled,toggle));row.appendChild(toggle);const action=make('div','row-action');const edit=add(action,'button','icon-btn','✎');edit.type='button';edit.title='编辑策略';edit.setAttribute('aria-label','编辑 '+def.title);edit.addEventListener('click',()=>openEditor(def.key));row.appendChild(action);root.appendChild(row)})}
`;
