export const OPS_OBSERVABILITY_VERSION_DISTRIBUTION_STYLE = `
    .overview-supporting-detail{margin-top:0}.client-version-panel{padding:16px}.client-version-panel .section-head{margin-bottom:14px}.client-version-layout{display:grid;grid-template-columns:180px minmax(0,1fr);gap:22px;align-items:start}.client-version-summary{display:flex;flex-direction:column;min-height:132px;padding:16px;border-radius:8px;background:linear-gradient(145deg,#edf7f4,#f8fbfa);color:var(--muted);font-size:12px}.client-version-summary>strong{margin:5px 0 2px;color:#26302e;font-size:28px;line-height:1}.client-version-summary small{font-size:11px}.client-version-coverage{margin-top:auto;padding-top:14px;border-top:1px solid rgba(0,102,95,.12)}.client-version-coverage span,.client-version-coverage small{display:block}.client-version-coverage strong{display:block;margin:3px 0;color:var(--green);font-size:18px}.client-version-list{display:grid;gap:9px}.client-version-row{display:grid;grid-template-columns:minmax(128px,.75fr) minmax(120px,1.5fr) 88px;align-items:center;gap:12px}.client-version-meta{display:flex;align-items:center;justify-content:space-between;gap:8px;min-width:0;font-size:12px}.client-version-meta strong{overflow:hidden;color:#2d3533;text-overflow:ellipsis;white-space:nowrap}.client-version-meta span{flex:none;color:var(--muted);font-variant-numeric:tabular-nums}.client-version-bar{height:8px;overflow:hidden;border-radius:999px;background:#edf1f0}.client-version-bar-fill{display:block;height:100%;min-width:2px;border-radius:inherit;background:linear-gradient(90deg,#00665f,#00a67e)}.client-version-last{color:var(--muted);font-size:11px;text-align:right;white-space:nowrap}.client-version-empty{padding:24px;border:1px dashed var(--line);border-radius:8px;color:var(--muted);text-align:center}.client-version-more{padding-top:3px;color:var(--muted);font-size:11px;text-align:right}
    @media(max-width:1100px){.client-version-row{grid-template-columns:minmax(128px,.75fr) minmax(140px,1.5fr)}.client-version-last{display:none}}
    @media(max-width:700px){.client-version-layout{grid-template-columns:1fr}.client-version-summary{min-height:0}.client-version-coverage{margin-top:14px}.client-version-row{grid-template-columns:minmax(130px,.8fr) minmax(130px,1.2fr)}}
    @media(max-width:520px){.client-version-panel{padding:13px}.client-version-row{grid-template-columns:1fr}.client-version-meta{margin-bottom:-3px}}
`;

export const OPS_OBSERVABILITY_VERSION_DISTRIBUTION_SCRIPT = `
      function clientVersionLabel(value){const version=String(value||'').trim();if(!version||version==='(unreported)')return '未上报';return version.startsWith('v')?version:('v'+version)}
      function renderClientVersionDistribution(o){const data=o&&o.clientVersions?o.clientVersions:{};const items=Array.isArray(data.items)?data.items:[];const total=Number(data.activeClients)||0;const panel=make('section','panel client-version-panel');const head=make('div','section-head');const title=make('div');add(title,'h2','','最近 7 天客户端版本');add(title,'div','hint','按账号 / 匿名标识最近一次打开去重；反映活跃使用，不等于安装量。');head.appendChild(title);add(head,'div','right',total?fmt(total)+' 个活跃标识':'暂无活跃样本');panel.appendChild(head);if(!items.length){panel.appendChild(make('div','client-version-empty','最近 7 天没有可用的客户端版本上报。'));return panel}const body=make('div','client-version-layout');const summary=make('div','client-version-summary');add(summary,'span','','活跃标识');add(summary,'strong','',fmt(total));add(summary,'small','',items.length+' 个版本档位');const coverage=make('div','client-version-coverage');add(coverage,'span','','版本上报覆盖率');add(coverage,'strong','',pct(data.coverageRate));add(coverage,'small','',fmt(data.reportedClients)+' 已上报 · '+fmt(data.unknownClients)+' 未上报');summary.appendChild(coverage);body.appendChild(summary);const list=make('div','client-version-list');items.slice(0,12).forEach(item=>{const share=Math.max(0,Math.min(1,Number(item.share)||0));const row=make('div','client-version-row');const meta=make('div','client-version-meta');add(meta,'strong','',clientVersionLabel(item.version));add(meta,'span','',fmt(item.clients)+' · '+pct(share));row.appendChild(meta);const track=make('div','client-version-bar');const fill=make('span','client-version-bar-fill');fill.style.width=(share*100).toFixed(1)+'%';track.appendChild(fill);row.appendChild(track);add(row,'small','client-version-last','最近 '+when(item.lastSeenAt));list.appendChild(row)});if(items.length>12)add(list,'div','client-version-more','其余 '+(items.length-12)+' 个版本档位已折叠');body.appendChild(list);panel.appendChild(body);return panel}
      const renderOverviewWithoutVersionDistribution=renderOverview;
      renderOverview=function(){renderOverviewWithoutVersionDistribution();const root=$('overviewContent');const data=state.overview&&state.overview.clientVersions?state.overview.clientVersions:{};const details=make('details','detail-sections overview-supporting-detail');const summary=make('summary','detail-summary');add(summary,'strong','','发布与客户端版本');add(summary,'span','',Number(data.activeClients||0)?(fmt(data.activeClients)+' 个活跃标识 · 上报覆盖 '+pct(data.coverageRate)):'最近 7 天暂无活跃样本');details.appendChild(summary);details.appendChild(renderClientVersionDistribution(state.overview));const diagnostic=root.querySelector('.detail-sections');if(diagnostic)root.insertBefore(details,diagnostic);else root.appendChild(details)};
`;
