/** Visual layer for the evidence-first AI SRE action queue. */
export const OPS_OBSERVABILITY_ACTION_LOOP_STYLE = `
    @scope (body.ops-observability){
      .action-loop-panel{padding:18px 20px;border:1px solid var(--c154);border-radius:13px;background:linear-gradient(135deg,var(--c525) 0%,var(--c2) 58%,var(--c526) 100%);box-shadow:0 8px 24px var(--c527)}
      .action-loop-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.action-loop-identity{display:flex;gap:11px;min-width:0}.action-loop-orb{display:grid;place-items:center;flex:0 0 38px;width:38px;height:38px;border:1px solid var(--c528);border-radius:11px;background:linear-gradient(145deg,var(--c529),var(--c530));color:var(--c383);font-size:10px;font-weight:800;letter-spacing:.05em}.action-loop-kicker{color:var(--c383);font-size:9px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.action-loop-head h2{margin:2px 0 0;color:var(--c531);font-size:16px;letter-spacing:-.015em}.action-loop-head p{max-width:760px;margin:4px 0 0;color:var(--c532);font-size:11px;line-height:1.5}.action-loop-head-actions{display:flex;align-items:center;gap:8px;flex:0 0 auto}.action-loop-count{padding:5px 8px;border:1px solid var(--c533);border-radius:999px;background:var(--c2);color:var(--c532);font-size:10px;white-space:nowrap}.action-loop-count.warn{border-color:var(--c534);background:var(--c535);color:var(--c536)}.action-loop-refresh{height:32px;padding:4px 10px;font-size:10px}
      .action-loop-stats{display:flex;flex-wrap:wrap;align-items:center;gap:6px;margin:0 0 12px}.action-loop-stats-label{color:var(--c537);font-size:9px;font-weight:650;white-space:nowrap}.action-loop-stats-chip{padding:3px 8px;border-radius:999px;background:var(--c538);color:var(--c539);font:9px ui-monospace,SFMono-Regular,Menlo,monospace;white-space:nowrap;cursor:help}.action-loop-stats-chip.ai{background:var(--c212);color:var(--c198)}
      .action-loop-flow{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px;margin:15px 0 14px;padding:7px;border:1px solid var(--c368);border-radius:9px;background:var(--c540)}.action-loop-flow-step{display:flex;align-items:center;justify-content:center;gap:6px;min-height:27px;border-radius:6px;color:var(--c541);font-size:9px;font-weight:650}.action-loop-flow-step:after{content:'→';margin-left:auto;color:var(--c542)}.action-loop-flow-step:last-child:after{display:none}.action-loop-flow-step.is-active{background:var(--c543);color:var(--c383)}.action-loop-flow-step.is-safe{background:var(--c544);color:var(--c545)}
      .action-loop-list{display:grid;gap:9px}.action-loop-card{padding:13px 14px;border:1px solid var(--c546);border-radius:10px;background:var(--c2);transition:border-color .16s ease,box-shadow .16s ease}.action-loop-card:hover{border-color:var(--c547);box-shadow:0 5px 16px var(--c482)}.action-loop-card[data-status='pending_approval']{border-left:3px solid var(--c386)}.action-loop-card[data-status='executing']{border-left:3px solid var(--c388)}.action-loop-card[data-status='succeeded']{border-left:3px solid var(--c383)}.action-loop-card[data-status='failed'],.action-loop-card[data-status='verification_failed']{border-left:3px solid var(--c387)}.action-loop-card[data-status='denied']{border-left:3px solid var(--c548);background:var(--c113)}
      .action-loop-card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.action-loop-card-title{display:flex;align-items:flex-start;gap:8px;min-width:0}.action-loop-card-title h3{margin:0;color:var(--c549);font-size:12px;line-height:1.4}.action-loop-card-title p{margin:3px 0 0;color:var(--c541);font-size:10px;line-height:1.45}.action-loop-type{padding:3px 6px;border-radius:5px;background:var(--c215);color:var(--c550);font-size:8px;font-weight:750;white-space:nowrap}.action-loop-status{padding:4px 8px;border-radius:999px;background:var(--c551);color:var(--c552);font-size:9px;font-weight:700;white-space:nowrap}.action-loop-status.pending_approval{background:var(--c227);color:var(--c536)}.action-loop-status.approved{background:var(--c553);color:var(--c554)}.action-loop-status.executing{background:var(--c555);color:var(--c388)}.action-loop-status.succeeded{background:var(--c543);color:var(--c383)}.action-loop-status.failed,.action-loop-status.verification_failed{background:var(--c556);color:var(--c557)}.action-loop-status.denied{background:var(--c223);color:var(--c558)}
      .action-loop-meta{display:flex;flex-wrap:wrap;gap:6px 12px;margin-top:9px;color:var(--c559);font:9px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace}.action-loop-origin{padding:3px 8px;border-radius:999px;background:var(--c212);color:var(--c198);font-size:9px;font-weight:650;white-space:nowrap;cursor:help}.action-loop-meta span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.action-loop-rationale{margin:9px 0 0;padding:8px 10px;border-radius:7px;background:var(--c29);color:var(--c560);font-size:10px;line-height:1.5}.action-loop-evidence{display:flex;align-items:center;flex-wrap:wrap;gap:5px;margin-top:9px}.action-loop-evidence-label{color:var(--c537);font-size:9px;font-weight:650}.action-loop-ref{max-width:230px;padding:3px 7px;border:1px solid var(--c561);border-radius:999px;background:var(--c562);color:var(--c563);font:9px ui-monospace,SFMono-Regular,Menlo,monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;cursor:pointer}.action-loop-ref:hover{border-color:var(--c564);background:var(--c565)}.action-loop-ref:focus-visible{outline:2px solid var(--c566);outline-offset:1px}
      .action-loop-history{display:flex;flex-wrap:wrap;align-items:center;gap:5px;margin-top:9px;padding:7px 9px;border:1px solid var(--c178);border-radius:7px;background:var(--c567)}.action-loop-history-label{color:var(--c537);font-size:9px;font-weight:650;white-space:nowrap}.action-loop-history-run{padding:3px 7px;border-radius:999px;background:var(--c538);color:var(--c541);font:9px ui-monospace,SFMono-Regular,Menlo,monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;cursor:help}.action-loop-history-run.good{background:var(--c543);color:var(--c383)}.action-loop-history-run.bad{background:var(--c556);color:var(--c557)}.action-loop-history-run.warn{background:var(--c227);color:var(--c536)}
      .action-loop-recovery{margin-top:9px;padding:8px 11px;border:1px solid var(--c568);border-left:3px solid var(--c387);border-radius:7px;background:var(--c144);color:var(--c569);font-size:10px;line-height:1.55}
      .action-loop-footer{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:11px;padding-top:9px;border-top:1px solid var(--c570)}.action-loop-safety{display:flex;align-items:center;gap:5px;color:var(--c571);font-size:9px}.action-loop-safety strong{color:var(--c383)}.action-loop-controls{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:6px}.action-loop-controls .btn{height:29px;padding:4px 9px;font-size:10px}.action-loop-controls .btn.danger{border-color:var(--c572);color:var(--c573);background:var(--c574)}.action-loop-controls .btn.danger:hover{border-color:var(--c575);background:var(--c17);color:var(--c576)}.action-loop-playbook{height:29px;max-width:210px;padding:3px 7px;border:1px solid var(--c577);border-radius:7px;background:var(--c2);color:var(--c578);font-size:10px}
      .action-loop-empty,.action-loop-state{display:grid;place-items:center;gap:6px;min-height:112px;padding:20px;border:1px dashed var(--c579);border-radius:9px;background:var(--c159);color:var(--c580);text-align:center;font-size:10px}.action-loop-empty strong,.action-loop-state strong{color:var(--c581);font-size:12px}.action-loop-empty span,.action-loop-state span{max-width:600px;line-height:1.5}.action-loop-state.error{border-color:var(--c582);background:var(--c574);color:var(--c583)}.action-loop-skeleton{display:grid;gap:8px}.action-loop-skeleton i{display:block;height:13px;border-radius:5px;background:linear-gradient(90deg,var(--c584) 20%,var(--c194) 50%,var(--c584) 80%);background-size:200% 100%;animation:action-loop-shimmer 1.2s ease-in-out infinite}.action-loop-skeleton i:nth-child(2){width:72%}.action-loop-skeleton i:nth-child(3){width:45%}@keyframes action-loop-shimmer{to{background-position:-200% 0}}
      .action-loop-note{margin-top:11px;padding:8px 10px;border:1px solid var(--c585);border-radius:7px;background:var(--c65);color:var(--c586);font-size:9px;line-height:1.5}.action-loop-note strong{margin-right:5px;color:var(--c587)}
      .copilot-action-controls{grid-column:2/-1;display:flex;align-items:center;flex-wrap:wrap;gap:6px;margin-top:7px}.copilot-action-controls .btn{height:27px;padding:3px 8px;font-size:9px}.copilot-action-controls select{height:27px;max-width:220px;border:1px solid var(--c577);border-radius:6px;background:var(--c2);color:var(--c578);font-size:9px}.copilot-action-controls .action-created{color:var(--c383);font-size:9px;font-weight:650}.copilot-action-controls .action-unavailable{color:var(--c536);font-size:9px}
      @media(max-width:720px){.action-loop-head{align-items:flex-start;flex-direction:column}.action-loop-head-actions{width:100%;justify-content:space-between}.action-loop-flow{grid-template-columns:repeat(5,minmax(90px,1fr));overflow-x:auto}.action-loop-flow-step{white-space:nowrap}.action-loop-card-head{flex-direction:column}.action-loop-status{align-self:flex-start}.action-loop-footer{align-items:flex-start;flex-direction:column}.action-loop-controls{justify-content:flex-start}.action-loop-playbook{max-width:100%;width:100%}}
      @media(prefers-reduced-motion:reduce){.action-loop-card,.action-loop-skeleton i{transition:none;animation:none}}
    }
`;
