export const OPS_OBSERVABILITY_SCRIPT_C = `      async function runChecks(){const button=$('runChecks');button.disabled=true;button.textContent='评估中…';try{await request('/api/ops/observability/run-checks',{method:'POST',body:'{}'});toast('评估任务已触发，正在刷新结果');await new Promise(resolve=>setTimeout(resolve,1200));await loadAll(true);toast('即时评估已完成，结果已刷新')}catch(error){toast('运行评估失败：'+friendlyError(error.message),false)}finally{button.disabled=false;button.textContent='立即评估'}}
      function runEvolution(){setView('overview');setTimeout(()=>{const node=$('actionLoopMount');if(node)node.scrollIntoView({behavior:'smooth',block:'start'});toast('候选进化直达触发已关闭；请在证据化行动队列中查看或提交动作。',false)},0)}
      function runRemediation(playbookId,button){const rem=state.remediation;const pb=rem&&rem.playbooks.find(item=>item.id===playbookId);const title=pb?pb.title:playbookId;if(button){button.disabled=true;button.setAttribute('aria-disabled','true')}toast('自愈「'+title+'」必须先绑定事件证据并提交行动提案，由另一位管理员审批后才能执行；本页不会直接修改生产。',false);if(button){button.disabled=false;button.removeAttribute('aria-disabled')}}
      if(typeof initNavGroups==='function')initNavGroups();
      document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.view)));
      document.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{state.category=button.dataset.category;document.querySelectorAll('[data-category]').forEach(item=>item.classList.toggle('active',item===button));renderRules()}));
      document.querySelectorAll('[data-status]').forEach(button=>button.addEventListener('click',()=>{state.statusFilter=button.dataset.status;document.querySelectorAll('[data-status]').forEach(item=>item.classList.toggle('active',item===button));renderRules()}));
      $('ruleSearch').value='';$('ruleSearch').addEventListener('focus',()=>$('ruleSearch').removeAttribute('readonly'),{once:true});$('ruleSearch').addEventListener('input',event=>{state.search=event.target.value.trim();renderRules()});
      $('filterTrigger').addEventListener('click',event=>{event.stopPropagation();$('ruleFilters').classList.toggle('hidden')});$('ruleFilters').addEventListener('click',event=>event.stopPropagation());$('closeFilters').addEventListener('click',()=>$('ruleFilters').classList.add('hidden'));$('clearFilters').addEventListener('click',()=>{state.category='all';state.statusFilter='all';document.querySelectorAll('[data-category]').forEach(item=>item.classList.toggle('active',item.dataset.category==='all'));document.querySelectorAll('[data-status]').forEach(item=>item.classList.toggle('active',item.dataset.status==='all'));renderRules()});document.addEventListener('click',()=>$('ruleFilters').classList.add('hidden'));
      $('refresh').addEventListener('click',()=>loadAll(true));$('runChecks').addEventListener('click',runChecks);$('runEvolution').addEventListener('click',runEvolution);$('closeEditor').addEventListener('click',closeEditor);$('cancelEditor').addEventListener('click',closeEditor);$('testRule').addEventListener('click',testRule);$('saveRule').addEventListener('click',saveRule);$('closeTemplateEditor').addEventListener('click',()=>{state.templateEditing=false;$('templateEditorZone').classList.add('hidden');$('templateSummary').scrollIntoView({behavior:'smooth',block:'start'})});$('ruleDrawer').addEventListener('click',event=>{if(event.target===$('ruleDrawer'))closeEditor()});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeEditor()});window.addEventListener('hashchange',()=>{const raw=location.hash.replace(/^#/,'');if(raw.startsWith('remediate=')){try{state.pendingRemediate=decodeURIComponent(raw.slice(10))}catch{state.pendingRemediate=raw.slice(10)}setView('overview',false);return}const alias=viewAliases[raw]||raw;if(viewNames.includes(raw)||viewNames.includes(alias))setView(raw,false)});
      const hashRaw=location.hash.replace(/^#/,'');if(hashRaw.startsWith('remediate=')){try{state.pendingRemediate=decodeURIComponent(hashRaw.slice(10))}catch{state.pendingRemediate=hashRaw.slice(10)}state.view='overview'}else{const alias=viewAliases[hashRaw]||hashRaw;/* Keep the raw alias for this first call so setView can open its legacy accordion. It canonicalizes state.view before loadAll runs. */state.view=(viewNames.includes(hashRaw)||viewNames.includes(alias))?(hashRaw||'overview'):'overview'}setView(state.view,false);loadAll();setInterval(()=>loadAll(false),30000);
    })();`;
