/** Read-only PostgreSQL dashboard. Rendered exclusively with safe DOM APIs. */
export const OPS_OBSERVABILITY_SCRIPT_DATABASE = `
      function databaseFriendlyError(message){const text=String(message||'').trim();if(text==='HTTP 404')return '数据库看板服务端路由尚未发布，请先刷新页面或联系管理员完成路由部署';const mapped=friendlyError(text);if(mapped!==text)return mapped;return '数据库服务暂不可用，请稍后重试或联系管理员'}
      function databaseBytes(value){
        const bytes=Math.max(0,Number(value)||0);if(bytes<1024)return bytes+' B';
        const units=['KB','MB','GB','TB'];let scaled=bytes;let unit=-1;
        do{scaled/=1024;unit+=1}while(scaled>=1024&&unit<units.length-1);
        return scaled.toFixed(scaled>=100?0:scaled>=10?1:2)+' '+units[unit];
      }
      function databaseDuration(seconds){
        const value=Math.max(0,Number(seconds)||0);const days=Math.floor(value/86400);const hours=Math.floor((value%86400)/3600);
        if(days)return days+' 天 '+hours+' 小时';const minutes=Math.floor((value%3600)/60);return hours?hours+' 小时 '+minutes+' 分钟':minutes+' 分钟';
      }
      function databasePercent(value,digits=1){return value==null?'—':(Number(value)*100).toFixed(digits)+'%'}
      function databaseWindowLabel(hours){return hours===24?'24 小时':hours===168?'近 7 天':'近 30 天'}
      function databaseMetric(label,value,detail,tone){const card=make('article','panel database-metric '+(tone||''));add(card,'div','database-metric-label',label);add(card,'div','database-metric-value',value);add(card,'div','database-metric-detail',detail);return card}
      function databasePanelHead(title,hint,right){const head=make('div','database-panel-head');const copy=make('div');add(copy,'h3','',title);add(copy,'p','',hint);head.appendChild(copy);if(right)add(head,'div','right',right);return head}
      function databaseLoading(label){const box=make('section','panel database-loading');box.setAttribute('role','status');box.setAttribute('aria-live','polite');const pulse=make('span','database-loading-pulse');pulse.setAttribute('aria-hidden','true');box.appendChild(pulse);add(box,'span','',label);return box}
      function databaseExportStamp(value){const date=new Date(value||Date.now());return Number.isFinite(date.getTime())?date.toISOString().replace(/[-:]/g,'').replace(/\\.\\d{3}Z$/,'Z'):'export'}
      function databaseCsvCell(value){let text=value===null||value===undefined?'':String(value);if(typeof value==='string'&&/^[\\t\\r\\n ]*[=+\\-@]/.test(text))text="'"+text;return '"'+text.replace(/"/g,'""')+'"'}
      function databaseDownload(name,content,type,bom=false){const blob=new Blob([bom?'\uFEFF':'',content],{type:type+';charset=utf-8'});const url=URL.createObjectURL(blob);const link=make('a');link.href=url;link.download=name;link.style.display='none';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
      function exportDatabaseTableCatalog(data){const columns=['schema_name','table_name','description','ai_access','estimated_rows','total_bytes','table_bytes','index_bytes','dead_rows','dead_row_ratio','index_scan_ratio','last_autovacuum_at','last_autoanalyze_at'];const lines=[columns.map(databaseCsvCell).join(','),...(data.tables||[]).map(item=>[item.schemaName||'public',item.name,item.description||'',item.aiQueryable?'masked_view':'blocked',item.estimatedRows,item.totalBytes,item.tableBytes,item.indexBytes,item.deadRows,item.deadRowRatio,item.indexScanRatio,item.lastAutovacuumAt,item.lastAutoanalyzeAt].map(databaseCsvCell).join(','))];databaseDownload('rdkstudio-pg-table-catalog-'+databaseExportStamp(data.generatedAt)+'.csv',lines.join('\\r\\n')+'\\r\\n','text/csv',true);toast('全部表清单已导出')}
      function databaseTableRequestPath(selection,format,page){const params=new URLSearchParams({schema:selection.schemaName||'public',format:format||'json',sort:state.databaseTableSortColumn||'',direction:state.databaseTableSortDirection||'asc'});if(format!=='csv'){params.set('page',String(Math.max(1,Number(page)||1)));params.set('pageSize','25')}return '/api/ops/observability/database/tables/'+encodeURIComponent(selection.name)+'?'+params.toString()}
      // 整表 CSV 导出必须走带鉴权的 fetch：<a href download> 是一次普通导航，带不上
      // ops 会话 / 运营令牌 / 租户令牌头，服务端只会返回 {ok:false} JSON，用户下载到的
      // 就是那份错误文档。这里改为 blob + object URL 触发下载，并复用 friendlyError。
      async function exportDatabaseTable(){
        const selection=state.databaseTableSelection;if(!selection)return;
        const tableLabel=(selection.schemaName||'public')+'.'+selection.name;
        toast('正在导出 '+tableLabel+' 整表 CSV…');
        try{
          const response=await fetch(base+databaseTableRequestPath(selection,'csv',1),{credentials:'same-origin',headers:apiHeaders(false)});
          if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error((data&&(data.error||data.message))||('HTTP '+response.status))}
          const blob=await response.blob();const url=URL.createObjectURL(blob);const link=make('a');link.href=url;link.download='rdkstudio-pg-'+tableLabel+'-'+databaseExportStamp()+'.csv';link.style.display='none';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
          toast('已导出 '+tableLabel+' 整表 CSV')
        }catch(error){toast('导出失败：'+databaseFriendlyError(error&&error.message),false)}
      }
      // 数据库 AI 查询面板已整体移除：该路由未在本服务挂载，表单与接口说明只会把
      // 用户引向 404；配套的渲染/执行函数与 state 字段一并删除，避免死代码引用。
      function renderDatabaseTrend(data){
        const panel=make('section','panel database-trend-panel');
        panel.appendChild(databasePanelHead('入库趋势','按库内时间戳聚合，只展示数量，不读取业务正文；悬停柱形查看时间桶与各来源明细。',databaseWindowLabel(data.windowHours)+' · '+(data.bucket==='hour'?'每小时':'每天')));
        const body=make('div','database-trend-body');const chart=make('div','database-chart');
        const totals=(data.trend||[]).map(item=>Object.values(item.values||{}).reduce((sum,value)=>sum+(Number(value)||0),0));
        const maxTotal=Math.max(1,...totals);const labelStep=Math.max(1,Math.ceil((data.trend||[]).length/6));
        const tooltip=make('div','database-trend-tooltip');tooltip.id='databaseTrendTooltip';tooltip.setAttribute('role','tooltip');tooltip.hidden=true;chart.appendChild(tooltip);
        const hideTooltip=column=>{if(document.activeElement!==column)tooltip.hidden=true};
        const showTooltip=(column,item,index,stack)=>{
          const total=totals[index]||0;tooltip.replaceChildren();add(tooltip,'strong','database-trend-tooltip-time',when(item.bucket));add(tooltip,'div','database-trend-tooltip-total','合计 '+fmt(total)+' 条');
          const rows=make('div','database-trend-tooltip-rows');(data.sources||[]).forEach(source=>{const count=Number(item.values&&item.values[source.key])||0;const row=make('div','database-trend-tooltip-row');const dot=make('i');dot.style.background=source.color;row.appendChild(dot);add(row,'span','',source.label);add(row,'strong','',fmt(count));rows.appendChild(row)});tooltip.appendChild(rows);
          tooltip.hidden=false;const chartRect=chart.getBoundingClientRect();const columnRect=column.getBoundingClientRect();const stackRect=stack.getBoundingClientRect();const center=columnRect.left+columnRect.width/2-chartRect.left;const halfWidth=tooltip.offsetWidth/2;const minLeft=halfWidth+8;const maxLeft=Math.max(minLeft,chart.clientWidth-halfWidth-8);tooltip.style.left=Math.min(maxLeft,Math.max(minLeft,center))+'px';tooltip.style.top=Math.max(8,stackRect.top-chartRect.top-tooltip.offsetHeight-8)+'px';
        };
        (data.trend||[]).forEach((item,index)=>{const column=make('div','database-trend-column');const total=totals[index]||0;const stack=make('div','database-trend-stack');stack.style.height=Math.max(total?2:0,(total/maxTotal)*100)+'%';
          (data.sources||[]).forEach(source=>{const count=Number(item.values&&item.values[source.key])||0;if(!count)return;const segment=make('span','database-trend-segment');segment.style.background=source.color;segment.style.height=(count/Math.max(1,total)*100)+'%';stack.appendChild(segment)});
          column.appendChild(stack);column.setAttribute('role','img');column.setAttribute('tabindex','0');column.setAttribute('aria-describedby','databaseTrendTooltip');column.setAttribute('aria-label',when(item.bucket)+'，合计 '+fmt(total)+' 条；'+(data.sources||[]).map(source=>source.label+' '+fmt(Number(item.values&&item.values[source.key])||0)).join('、'));column.addEventListener('pointerenter',()=>showTooltip(column,item,index,stack));column.addEventListener('pointerleave',()=>hideTooltip(column));column.addEventListener('focus',()=>showTooltip(column,item,index,stack));column.addEventListener('blur',()=>{tooltip.hidden=true});
          if(index%labelStep===0||index===(data.trend||[]).length-1){const date=new Date(item.bucket);const label=data.bucket==='hour'?String(date.getHours()).padStart(2,'0')+':00':(date.getMonth()+1)+'/'+date.getDate();add(column,'span','database-trend-label',label)}
          chart.appendChild(column)});
        if(!(data.trend||[]).length)chart.appendChild(make('div','database-loading','当前时间窗口没有入库记录'));
        body.appendChild(chart);const legend=make('div','database-legend');(data.sources||[]).forEach(source=>{const row=make('div','database-legend-row');const dot=make('i');dot.style.background=source.color;row.appendChild(dot);add(row,'span','',source.label);add(row,'strong','',fmt(source.windowRows));legend.appendChild(row)});body.appendChild(legend);panel.appendChild(body);return panel;
      }
      function renderDatabaseSources(data){
        const panel=make('section','panel database-source-panel');const total=(data.sources||[]).reduce((sum,source)=>sum+(Number(source.windowRows)||0),0);
        panel.appendChild(databasePanelHead('业务数据入库','关键数据表的估算总量、时间窗口新增和最近写入。',databaseWindowLabel(data.windowHours)+' 共 '+fmt(total)+' 条'));
        const grid=make('div','database-sources');(data.sources||[]).forEach(source=>{const card=make('article','database-source');const top=make('div','database-source-head');const dot=make('i','database-source-dot');dot.style.background=source.color;top.appendChild(dot);add(top,'div','database-source-title',source.label);card.appendChild(top);add(card,'div','database-source-time','最近入库 '+when(source.latestAt));const counts=make('div','database-source-counts');const totalBox=make('div');add(totalBox,'span','',source.key);add(totalBox,'strong','',fmt(source.estimatedRows));counts.appendChild(totalBox);const windowBox=make('div');add(windowBox,'span','',databaseWindowLabel(data.windowHours)+' 新增');add(windowBox,'strong','',fmt(source.windowRows));counts.appendChild(windowBox);card.appendChild(counts);add(card,'div','database-source-time','表占用 '+databaseBytes(source.totalBytes)+' · 总量为 PG 估算值');grid.appendChild(card)});
        if(!(data.sources||[]).length)grid.appendChild(make('div','database-loading','未找到已接入的业务数据表'));
        panel.appendChild(grid);return panel;
      }
      let databaseTableReturnFocus=null;let databaseBodyOverflow='';
      function closeDatabaseTableDetail(){
        const backdrop=$('databaseDetailDrawer');if(!backdrop||backdrop.classList.contains('hidden'))return;backdrop.classList.add('hidden');backdrop.setAttribute('aria-hidden','true');document.body.style.overflow=databaseBodyOverflow;const returnFocus=databaseTableReturnFocus;databaseTableReturnFocus=null;if(returnFocus&&returnFocus.isConnected&&typeof returnFocus.focus==='function')returnFocus.focus();
      }
      function ensureDatabaseTableDetailDrawer(){
        let backdrop=$('databaseDetailDrawer');if(backdrop)return backdrop;
        backdrop=make('div','database-detail-backdrop hidden');backdrop.id='databaseDetailDrawer';backdrop.setAttribute('role','dialog');backdrop.setAttribute('aria-modal','true');backdrop.setAttribute('aria-hidden','true');backdrop.setAttribute('aria-labelledby','databaseDetailTitle');backdrop.setAttribute('aria-describedby','databaseDetailSubtitle');
        const drawer=make('aside','database-detail-drawer');const head=make('div','database-detail-head');const copy=make('div','database-detail-head-copy');add(copy,'div','page-kicker','PG 数据库 / 表详情');const title=add(copy,'h2','','选择一张表');title.id='databaseDetailTitle';const subtitle=add(copy,'p','','字段结构、索引与脱敏数据预览');subtitle.id='databaseDetailSubtitle';head.appendChild(copy);const close=add(head,'button','btn database-detail-close','关闭');close.type='button';close.setAttribute('aria-label','关闭 PostgreSQL 表详情');close.addEventListener('click',closeDatabaseTableDetail);head.appendChild(close);drawer.appendChild(head);const body=make('div','database-detail-body');body.id='databaseDetailBody';drawer.appendChild(body);backdrop.appendChild(drawer);backdrop.addEventListener('click',event=>{if(event.target===backdrop)closeDatabaseTableDetail()});document.addEventListener('keydown',event=>{if(backdrop.classList.contains('hidden'))return;if(event.key==='Escape'){closeDatabaseTableDetail();return}if(event.key!=='Tab')return;const focusable=[...backdrop.querySelectorAll('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(node=>!node.hidden&&node.getClientRects().length);if(!focusable.length)return;const first=focusable[0];const last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});document.body.appendChild(backdrop);return backdrop;
      }
      function databaseDetailMetric(label,value,detail){
        const card=make('article','panel database-detail-card');add(card,'span','',label);add(card,'strong','',value);if(detail)add(card,'span','',detail);return card;
      }
      function databaseDetailCellValue(value){
        if(value===null||value===undefined)return 'NULL';if(typeof value==='object'){try{return JSON.stringify(value)}catch{return String(value)}}return String(value);
      }
      function renderDatabaseTableDetail(detail){
        const body=$('databaseDetailBody');if(!body)return;body.replaceChildren();const relation=detail.relation||{};$('databaseDetailTitle').textContent=(relation.schemaName||'public')+'.'+(relation.name||'—');$('databaseDetailSubtitle').textContent=relation.description||'PostgreSQL 业务表';
        const stack=make('div','database-detail-stack');const summary=make('div','database-detail-summary');summary.appendChild(databaseDetailMetric('估算行数',fmt(relation.estimatedRows),'来自 PostgreSQL 统计'));summary.appendChild(databaseDetailMetric('表总占用',databaseBytes(relation.totalBytes),'含表与索引'));summary.appendChild(databaseDetailMetric('字段',fmt((detail.columns||[]).length),'主键 '+fmt((detail.columns||[]).filter(column=>column.primaryKey).length)+' 列'));summary.appendChild(databaseDetailMetric('索引',fmt((detail.indexes||[]).length),relation.kind==='partitioned_table'?'分区表':'普通表'));stack.appendChild(summary);
        const columnSection=make('section','panel database-detail-section');columnSection.appendChild(databasePanelHead('字段结构','用户、账号、会话、正文与扩展数据均可查看；仅密码、Token、密钥等凭据字段不读取预览值。',(detail.columns||[]).length+' 列'));const columnScroll=make('div','database-detail-grid-scroll');columnScroll.tabIndex=0;columnScroll.setAttribute('aria-label','字段结构表');const columnTable=make('table','database-detail-grid');const columnHead=make('thead');const columnHeader=make('tr');['字段','类型','可空','默认值','备注','预览'].forEach(label=>{const th=add(columnHeader,'th','',label);th.scope='col'});columnHead.appendChild(columnHeader);columnTable.appendChild(columnHead);const columnBody=make('tbody');(detail.columns||[]).forEach(column=>{const row=make('tr');const name=make('td','database-detail-column-name',column.name);if(column.primaryKey)add(name,'span','database-detail-badge','PK');row.appendChild(name);add(row,'td','',column.dataType||'—');add(row,'td','',column.nullable?'是':'否');add(row,'td','',column.defaultValue||'—');add(row,'td','',column.description||'—');add(row,'td',column.previewable?'':'database-detail-mask',column.previewable?'可见':'凭据已隐藏');columnBody.appendChild(row)});columnTable.appendChild(columnBody);columnScroll.appendChild(columnTable);columnSection.appendChild(columnScroll);
        const previewSection=make('section','panel database-detail-section');const previewHead=databasePanelHead('分页数据预览','只读返回，每页最多 25 行；排序与整表 CSV 导出使用同一顺序，仅凭据字段隐藏。');const controls=make('div','database-detail-controls');const sortLabel=add(controls,'label','','排序字段');const sortSelect=make('select','database-detail-sort');(detail.columns||[]).filter(column=>column.sortable).forEach(column=>{const option=make('option');option.value=column.name;option.textContent=column.name+(column.primaryKey?' · PK':'');sortSelect.appendChild(option)});sortSelect.value=detail.preview.sortColumn||'';sortSelect.disabled=!sortSelect.options.length;sortSelect.addEventListener('change',()=>{state.databaseTableSortColumn=sortSelect.value;openDatabaseTableDetail(state.databaseTableSelection,1)});sortLabel.appendChild(sortSelect);[['asc','正序 ↑'],['desc','倒序 ↓']].forEach(option=>{const button=add(controls,'button','btn database-sort-direction '+(detail.preview.sortDirection===option[0]?'active':''),option[1]);button.type='button';button.addEventListener('click',()=>{state.databaseTableSortDirection=option[0];openDatabaseTableDetail(state.databaseTableSelection,1)});controls.appendChild(button)});const exportButton=add(controls,'button','btn primary database-table-export','导出整表 CSV');exportButton.type='button';exportButton.addEventListener('click',exportDatabaseTable);controls.appendChild(exportButton);const pagination=make('div','database-detail-pagination');const previous=add(pagination,'button','btn','上一页');previous.type='button';previous.disabled=Number(detail.preview.page)<=1;previous.addEventListener('click',()=>openDatabaseTableDetail(state.databaseTableSelection,Number(detail.preview.page)-1));add(pagination,'span','','第 '+fmt(detail.preview.page)+' 页');const next=add(pagination,'button','btn','下一页');next.type='button';next.disabled=!detail.preview.hasMore;next.addEventListener('click',()=>openDatabaseTableDetail(state.databaseTableSelection,Number(detail.preview.page)+1));pagination.appendChild(next);controls.appendChild(pagination);previewHead.appendChild(controls);previewSection.appendChild(previewHead);
        if((detail.preview.rows||[]).length){const previewScroll=make('div','database-detail-grid-scroll');previewScroll.tabIndex=0;previewScroll.setAttribute('aria-label','分页数据预览表');const previewTable=make('table','database-detail-grid');previewTable.style.minWidth=Math.max(760,(detail.columns||[]).length*145)+'px';const previewThead=make('thead');const previewHeader=make('tr');(detail.columns||[]).forEach(column=>{const th=add(previewHeader,'th','',column.name);th.scope='col'});previewThead.appendChild(previewHeader);previewTable.appendChild(previewThead);const previewBody=make('tbody');(detail.preview.rows||[]).forEach(item=>{const row=make('tr');(detail.columns||[]).forEach(column=>{const value=databaseDetailCellValue(item[column.name]);const cell=add(row,'td',column.previewable?'':'database-detail-mask',value);cell.title=value});previewBody.appendChild(row)});previewTable.appendChild(previewBody);previewScroll.appendChild(previewTable);previewSection.appendChild(previewScroll)}else{previewSection.appendChild(make('div','database-detail-empty',detail.preview.hiddenColumnCount===(detail.columns||[]).length?'该表全部字段都是凭据或二进制数据，已保留结构信息但不读取行数据':'当前页没有数据'))}
        if(detail.preview.hiddenColumnCount)add(previewSection,'div','database-detail-empty','已隐藏 '+fmt(detail.preview.hiddenColumnCount)+' 个凭据或二进制字段；用户、账号、会话、正文与扩展数据均按原值展示。');stack.appendChild(previewSection);stack.appendChild(columnSection);
        const indexSection=make('section','panel database-detail-section');indexSection.appendChild(databasePanelHead('索引','用于判断主键、唯一约束和查询路径。',(detail.indexes||[]).length+' 个'));const indexes=make('div','database-detail-indexes');(detail.indexes||[]).forEach(index=>{const item=make('div','database-detail-index');add(item,'strong','',index.name);add(item,'code','',index.definition);indexes.appendChild(item)});if(!(detail.indexes||[]).length)indexes.appendChild(make('div','database-detail-empty','此表没有索引'));indexSection.appendChild(indexes);stack.appendChild(indexSection);body.appendChild(stack);
      }
      async function openDatabaseTableDetail(item,page=1){
        if(!item||state.databaseTableLoading)return;const selection={schemaName:item.schemaName||'public',name:item.name};const changed=!state.databaseTableSelection||state.databaseTableSelection.schemaName!==selection.schemaName||state.databaseTableSelection.name!==selection.name;if(changed){state.databaseTableSortColumn='';state.databaseTableSortDirection='asc'}state.databaseTableSelection=selection;state.databaseTablePage=Math.max(1,Number(page)||1);const backdrop=ensureDatabaseTableDetailDrawer();const opening=backdrop.classList.contains('hidden');if(opening){databaseTableReturnFocus=document.activeElement;databaseBodyOverflow=document.body.style.overflow;document.body.style.overflow='hidden'}backdrop.classList.remove('hidden');backdrop.setAttribute('aria-hidden','false');if(opening){const close=backdrop.querySelector('.database-detail-close');if(close)close.focus()}$('databaseDetailTitle').textContent=selection.schemaName+'.'+selection.name;$('databaseDetailSubtitle').textContent='正在读取字段结构、索引与排序后的分页预览…';$('databaseDetailBody').replaceChildren(make('div','database-detail-loading','正在加载表详情…'));state.databaseTableLoading=true;
        try{const result=await request(databaseTableRequestPath(selection,'json',state.databaseTablePage));state.databaseTableDetail=result.detail;state.databaseTableSortColumn=result.detail.preview.sortColumn||'';state.databaseTableSortDirection=result.detail.preview.sortDirection||'asc';renderDatabaseTableDetail(result.detail)}catch(error){const body=$('databaseDetailBody');if(body){const box=make('section','panel database-error');add(box,'strong','','表详情加载失败');add(box,'span','',databaseFriendlyError(error.message));const retry=add(box,'button','btn','重试');retry.type='button';retry.addEventListener('click',()=>openDatabaseTableDetail(selection,state.databaseTablePage));box.appendChild(retry);body.replaceChildren(box)}}finally{state.databaseTableLoading=false}
      }
      function renderDatabaseTables(data){
        const tables=data.tables||[];const pageSize=12;let expanded=false;
        const panel=make('section','panel database-table-panel');const panelHead=databasePanelHead('全部表与维护状态','先搜索或按脱敏权限筛选；点击任意表即可查看字段结构、索引和分页数据预览，仅凭据字段自动隐藏。');const panelActions=make('div','database-panel-actions');add(panelActions,'span','',tables.length+' 张表');const exportButton=add(panelActions,'button','btn database-export-button','导出表清单 CSV');exportButton.type='button';exportButton.addEventListener('click',()=>exportDatabaseTableCatalog(data));panelHead.appendChild(panelActions);panel.appendChild(panelHead);
        const tools=make('div','database-table-tools');const searchLabel=make('label','database-table-search');add(searchLabel,'span','', '搜索表');const search=make('input');search.type='search';search.autocomplete='off';search.placeholder='表名、schema 或备注';search.setAttribute('aria-label','搜索数据库表');searchLabel.appendChild(search);tools.appendChild(searchLabel);const filterLabel=make('label','database-table-filter');add(filterLabel,'span','','查询权限');const filter=make('select');[['all','全部权限'],['queryable','可脱敏查询'],['restricted','不开放查询']].forEach(option=>{const item=make('option');item.value=option[0];item.textContent=option[1];filter.appendChild(item)});filterLabel.appendChild(filter);tools.appendChild(filterLabel);const resultStatus=add(tools,'div','database-table-result','');resultStatus.setAttribute('role','status');resultStatus.setAttribute('aria-live','polite');panel.appendChild(tools);
        const scroll=make('div','database-table-scroll');scroll.tabIndex=0;scroll.setAttribute('aria-label','PostgreSQL 表与维护状态');const table=make('table','database-table');const head=make('thead');const header=make('tr');['表名','备注与 AI 权限','估算行数','总占用','索引占用','死行 / 比例','索引扫描率','最近 Autovacuum','最近 Analyze'].forEach(label=>{const th=add(header,'th','',label);th.scope='col'});head.appendChild(header);table.appendChild(head);const body=make('tbody');table.appendChild(body);scroll.appendChild(table);panel.appendChild(scroll);
        const footer=make('div','database-table-footer');const footerCopy=add(footer,'span','','');const toggle=add(footer,'button','btn database-table-toggle','');toggle.type='button';footer.appendChild(toggle);panel.appendChild(footer);
        const createRow=item=>{const row=make('tr');const nameCell=make('td','database-table-name');add(nameCell,'span','database-table-schema',item.schemaName||'public');const tableButton=add(nameCell,'button','database-table-link',item.name);tableButton.type='button';tableButton.setAttribute('aria-label','查看表 '+(item.schemaName||'public')+'.'+item.name);row.appendChild(nameCell);row.addEventListener('click',()=>{tableButton.focus();openDatabaseTableDetail(item,1)});const note=make('td','database-table-description');add(note,'span','',item.description||'尚未设置备注');add(note,'small',item.aiQueryable?'queryable':'restricted',item.aiQueryable?'可脱敏查询':'不开放查询');row.appendChild(note);add(row,'td','',fmt(item.estimatedRows));add(row,'td','',databaseBytes(item.totalBytes));add(row,'td','',databaseBytes(item.indexBytes));const deadTone=(item.deadRowRatio||0)>=.2?'critical':(item.deadRowRatio||0)>=.1?'warning':'';add(row,'td','database-ratio '+deadTone,fmt(item.deadRows)+' / '+databasePercent(item.deadRowRatio));add(row,'td','',databasePercent(item.indexScanRatio));add(row,'td','',when(item.lastAutovacuumAt));add(row,'td','',when(item.lastAutoanalyzeAt));return row};
        const update=()=>{const query=search.value.trim().toLocaleLowerCase();const permission=filter.value;const matches=tables.filter(item=>{const searchable=[item.schemaName||'public',item.name,item.description||''].join(' ').toLocaleLowerCase();const permissionMatch=permission==='all'||(permission==='queryable'&&item.aiQueryable)||(permission==='restricted'&&!item.aiQueryable);return permissionMatch&&(!query||searchable.includes(query))});const visible=expanded?matches:matches.slice(0,pageSize);body.replaceChildren();visible.forEach(item=>body.appendChild(createRow(item)));if(!matches.length){const row=make('tr');const cell=add(row,'td','database-table-empty','没有匹配的表，请更换搜索词或筛选条件。');cell.colSpan=9;body.appendChild(row)}resultStatus.textContent='匹配 '+matches.length+' 张表';footerCopy.textContent=matches.length?'已显示 '+visible.length+' / '+matches.length+' 张表':'当前无可展示结果';toggle.hidden=matches.length<=pageSize;toggle.textContent=expanded?'收起到前 '+pageSize+' 张':'展开剩余 '+Math.max(0,matches.length-pageSize)+' 张';toggle.setAttribute('aria-expanded',String(expanded))};
        search.addEventListener('input',()=>{expanded=false;update()});filter.addEventListener('change',()=>{expanded=false;update()});toggle.addEventListener('click',()=>{expanded=!expanded;update();if(!expanded)panel.scrollIntoView({block:'start',behavior:'smooth'})});update();return panel;
      }
      function renderDataHealthDashboard(){
        const root=$('dataHealthContent');if(!root)return;const data=state.database;if(!data){root.setAttribute('aria-busy','true');root.replaceChildren(databaseLoading('正在读取业务数据入库状态…'));return}root.removeAttribute('aria-busy');root.replaceChildren();
        const toolbar=make('section','panel database-toolbar');const copy=make('div','database-toolbar-copy');add(copy,'strong','','业务入库只读视图');add(copy,'span','','只统计固定白名单表的数量和时间戳，不读取业务正文 · 更新 '+when(data.generatedAt));toolbar.appendChild(copy);const ranges=make('div','segmented');ranges.setAttribute('role','group');ranges.setAttribute('aria-label','入库数据时间范围');[[24,'24 小时'],[168,'7 天'],[720,'30 天']].forEach(option=>{const button=make('button',Number(data.windowHours)===option[0]?'active':'',option[1]);button.type='button';button.dataset.databaseHours=String(option[0]);button.setAttribute('aria-pressed',String(Number(data.windowHours)===option[0]));button.addEventListener('click',()=>{state.databaseHours=option[0];loadPostgresDashboard(true)});ranges.appendChild(button)});toolbar.appendChild(ranges);const refresh=add(toolbar,'button','btn database-refresh','刷新');refresh.type='button';refresh.setAttribute('aria-label','刷新业务入库数据');refresh.addEventListener('click',()=>loadPostgresDashboard(true));root.appendChild(toolbar);
        root.appendChild(renderDatabaseSources(data));const trendDisclosure=make('details','detail-sections database-disclosure');trendDisclosure.id='data-health-trend-disclosure';const trendSummary=make('summary','detail-summary');add(trendSummary,'strong','','入库趋势');add(trendSummary,'span','',databaseWindowLabel(data.windowHours)+' · 按需展开时间序列');trendDisclosure.appendChild(trendSummary);trendDisclosure.appendChild(renderDatabaseTrend(data));root.appendChild(trendDisclosure);
      }
      function renderPostgresDashboard(){
        const root=$('databaseContent');if(!root)return;const data=state.database;if(!data){root.setAttribute('aria-busy','true');root.replaceChildren(databaseLoading('正在读取 PostgreSQL 运行状态…'));return}root.removeAttribute('aria-busy');root.replaceChildren();
        const toolbar=make('section','panel database-toolbar');const copy=make('div','database-toolbar-copy');add(copy,'strong','','中心库只读视图');add(copy,'span','','指标来自 pg_stat_* 与固定白名单表，不开放任意 SQL · 更新 '+when(data.generatedAt));toolbar.appendChild(copy);const refresh=add(toolbar,'button','btn database-refresh','刷新');refresh.type='button';refresh.setAttribute('aria-label','刷新 PostgreSQL 运行状态');refresh.addEventListener('click',()=>loadPostgresDashboard(true));root.appendChild(toolbar);
        const health=data.health;const hero=make('section','panel database-health '+health.status);add(hero,'div','database-health-icon',health.status==='healthy'?'✓':health.status==='critical'?'!':'△');const healthCopy=make('div');add(healthCopy,'h3','',health.status==='healthy'?'PostgreSQL 运行正常':health.status==='critical'?'数据库需要立即处置':'数据库存在待观察信号');add(healthCopy,'p','',(health.reasons||[]).join(' · '));hero.appendChild(healthCopy);const meta=make('div','database-health-meta');add(meta,'strong','','PostgreSQL '+(health.version||'—'));add(meta,'span','','已运行 '+databaseDuration(health.uptimeSeconds)+' · 更新 '+when(data.generatedAt));hero.appendChild(meta);root.appendChild(hero);
        const metrics=make('div','database-metrics');const connectionTone=(health.connections.ratio||0)>=.9?'critical':(health.connections.ratio||0)>=.7?'warning':'';metrics.appendChild(databaseMetric('数据库容量',databaseBytes(health.databaseSizeBytes),'共享缓冲区 '+(health.sharedBuffers||'—')));metrics.appendChild(databaseMetric('连接使用',health.connections.used+' / '+health.connections.max,databasePercent(health.connections.ratio)+' · '+health.connections.active+' 个活跃',connectionTone));metrics.appendChild(databaseMetric('缓存命中率',databasePercent(health.cacheHitRatio,2),'自统计重置以来',(health.cacheHitRatio!=null&&health.cacheHitRatio<.95)?'warning':''));metrics.appendChild(databaseMetric('事务回滚率',databasePercent(health.transactionRollbackRatio,3),fmt(health.rollbacks)+' 回滚 / '+fmt(health.commits)+' 提交'));metrics.appendChild(databaseMetric('等待与慢查询',fmt(health.connections.waiting+health.connections.longRunning),health.connections.waiting+' 等待 · '+health.connections.longRunning+' 超过 30 秒',(health.connections.waiting>=5||health.connections.longRunning>=5)?'warning':''));metrics.appendChild(databaseMetric('Idle 事务',fmt(health.connections.idleInTransaction),fmt(health.deadlocks)+' 累计死锁 · 累计临时数据 '+databaseBytes(health.tempBytes),health.connections.idleInTransaction>=5?'critical':health.connections.idleInTransaction?'warning':''));root.appendChild(metrics);
        const relationship=make('details','detail-sections database-disclosure');relationship.id='database-relations-disclosure';const relationshipSummary=make('summary','detail-summary');add(relationshipSummary,'strong','','关系与 Schema');add(relationshipSummary,'span','',((data.relationshipGraph&&data.relationshipGraph.summary&&data.relationshipGraph.summary.tableCount)||0)+' 张表 · 外键与脱敏投影');relationship.appendChild(relationshipSummary);relationship.appendChild(renderDatabaseRelationshipGraph(data));root.appendChild(relationship);
        const tableCatalog=make('details','detail-sections database-disclosure');tableCatalog.id='database-table-disclosure';const tableSummary=make('summary','detail-summary');add(tableSummary,'strong','','表目录与维护');add(tableSummary,'span','',fmt((data.tables||[]).length)+' 张表 · 搜索、筛选与只读预览');tableCatalog.open=true;tableCatalog.appendChild(tableSummary);tableCatalog.appendChild(renderDatabaseTables(data));root.appendChild(tableCatalog);
      }
      function renderDatabaseViews(){
        renderDataHealthDashboard();renderPostgresDashboard();
      }
      async function loadPostgresDashboard(force=false){
        if(state.databaseLoading)return;if(!force&&state.database&&Date.now()-(state.databaseLoadedAt||0)<15000){renderDatabaseViews();return}state.databaseLoading=true;if(!state.database)renderDatabaseViews();
        try{const result=await request('/api/ops/observability/database?hours='+(state.databaseHours||24));state.database=result.database;state.databaseLoadedAt=Date.now();renderDatabaseViews()}catch(error){[['dataHealthContent','数据健康加载失败'],['databaseContent','数据库看板加载失败']].forEach(item=>{const root=$(item[0]);if(!root)return;root.removeAttribute('aria-busy');const box=make('section','panel database-error');box.setAttribute('role','alert');add(box,'strong','',item[1]);add(box,'span','',databaseFriendlyError(error.message));const retry=add(box,'button','btn','重试');retry.type='button';retry.addEventListener('click',()=>loadPostgresDashboard(true));root.replaceChildren(box)});if(error.message!=='not_authorized')toast('数据库数据加载失败：'+databaseFriendlyError(error.message),false)}finally{state.databaseLoading=false}
      }
`;
